### ISSUE TITLE
 Numbers larger than 9999 should be written with underscores

### ISSUE THREAD

**Issue by bougueil** [rrrene/credo#1009]
credo suggests Numbers larger than 9999 should be written with underscores: 12_345

However `mix format` formats 12345 as 12345.

see https://github.com/elixir-lang/elixir/blob/628df818bf3cac8fea9321bed9a12f1729bf856a/lib/elixir/lib/code/formatter.ex#L1633

shouldn't it harm if we increase the current limit of 9999 to be 9_9999 ?

**Comment by rrrene** [comment]
I completely understand why you are raising this issue. 

The Elixir formatter does it's own thing and while Credo does its best to not contradict it, I do not think that changing defaults on default checks should be taken lightly at this point. If we increase the default for this check, this would lead to inconsistent codebases for a lot of people.

For this reason, I am against changing the default.

**Comment by bougueil** [comment]
not a big problem for me to stay like this, just not forget to write my 12345 as 12_345.

People will continue to have this warning despite having run mix format, 

Thanks for this fantastic tool.
