### ISSUE TITLE
Exception naming consistency check produces unexpected reasoning

### ISSUE THREAD

**Issue by notinecrafter** [rrrene/credo#1012]
### Precheck

This issue occurs when having only two exceptions, and is therefore quite close to https://github.com/rrrene/credo/issues/969.
I personally feel that this is slightly different, as this is more about the explanation text rather than that it shows up at all, but feel free to disclose it.

### Environment

* Credo version (`mix credo -v`): 1.6.7-ref.main.bcd8bf6+uncommittedchanges
* Erlang/Elixir version (`elixir -v`): Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns] [dtrace]; Elixir 1.14.1 (compiled with Erlang/OTP 25)
* Operating system: MacOS 12.4

### What were you trying to do?

I had two custom exceptions defined: a `NotLoggedInError`, and a `TokenManagerExitException`.
I then ran `mix credo`.

### Expected outcome

Exception modules should be named consistently. It seems your strategy is to suffix them with  `Error`, but `TokenManagerExitException` does not follow that convention.

### Actual outcome

Exception modules should be named consistently. It seems your strategy is to prefix them with  `Not`, but `TokenManagerExitException` does not follow that convention.

### Notes

Renaming `TokenManagerExitException` to `TokenManagerExitError` resulted in this Exception being removed.

**Comment by rrrene** [comment]
@notinecrafter Does this happen on Credo 1.7.x as well? Could you check?

**Comment by rrrene** [comment]
@notinecrafter Checking in 👆

**Comment by rrrene** [comment]
Closing this because I suspect this has been fixed in Credo 1.7 - if I am wrong, please re-open! :+1:
