### ISSUE TITLE
oom/runs infinitely on with having when guard

### ISSUE THREAD

**Issue by ghost** [rrrene/credo#1013]
### Environment

* Credo version (`mix credo -v`):
* Erlang/Elixir version (`elixir -v`):
* Operating system:

### What were you trying to do?

run credo with the following snippet:
```
   with :ok when not(false) <- some_compute()
   do
     true
   else
     _ -> :error
   end
```

I can produce a more accurate snippet later if this doesn't reproduce it exactly.

### Expected outcome

not OOM

### Actual outcome

OOM

**Comment by rrrene** [comment]
Missed this one, sorry.

Both `mix credo` and `mix credo --strict` finish fine for me. Can you elaborate on your setup? (see the section "Environment" in the issue template)
