### ISSUE TITLE
Checking multiple files (not all the project) does not work

### ISSUE THREAD

**Issue by pierrelegall** [rrrene/credo#1016]
### Environment

* Credo version: 1.6.7
* Erlang/Elixir version: 1.14.0 (compiled with Erlang/OTP 25)
* Operating system: Archlinux (Linux kernel 6.0.10-arch2-1)

### What was I trying to do?

I am trying to check multiple files with Credo, not all my project.

When I use `mix credo file.ex`, it works as expected. However, this is not the case when you check multiple file (e.g. `mix credo file1.ex file2.ex`).

In my case, this is useful to speed up my pre-commit Git hook as below:

```sh
#!/bin/sh

set -e

STAGED_FILES=$(git diff --name-only --cached)

mix credo $STAGED_FILES
```

Bug or feature? That is the question.

### Expected outcome

Every listed files should be checked by Credo.

### Actual outcome

Only the first file is checked by Credo.

**Comment by rrrene** [comment]
This is now possible. Please re-open if you run into any issues 👍
