### ISSUE TITLE
Credo segfaults (Elixir 1.14.2, Credo 1.6.7, Ubuntu 22.04) 

### ISSUE THREAD

**Issue by wmnnd** [rrrene/credo#1019]
I’ve recently added Credo to a project, but about 8/10 times when I run `mix credo` or `mix credo suggest`, the application exits with a segmentation fault error:

```
$ mix credo suggest
Checking 104 source files (this might take a while) ...
Segmentation fault (core dumped)
```

Sporadically, however, the command does work and Credo successfully prints suggestions.

Other Credo commands 

I’m using Elixir 1.14.2 (installed via asdf) and Credo 1.6.7 on a machine with Ubuntu 22.04.

```
elixir -v
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 23)
```

**Comment by wmnnd** [comment]
I’ve now tried it with [Keila](https://github.com/pentacent/keila) which was still using Elixir 1.12 and no segfaults occurred. Then I upgraded to 1.14 (`asdf local elixir 1.14.2`) and Credo segfaults again.

**Comment by rrrene** [comment]
Might this somehow be a "Ubuntu thing"? 

I had to downgrade all my GitHub Actions workflows to `ubuntu-18.04` (instead of `ubuntu-latest`), because newer versions of Ubuntu did not work.

I am a bit at a loss here ...

**Comment by rrrene** [comment]
Closing this for age and "not being sure what can be done". 

If there are new developments, please feel free to re-open this 👍
