### ISSUE TITLE
Misinterpretation of pattern matches

### ISSUE THREAD

**Issue by ramonsnir** [rrrene/credo#102]
The easiest example of this is:

`var!(foo) = 4` which complains that `Assigned variable `var!` has same name as the `Kernel.var!` macro.`

**Comment by rrrene** [comment]
Thx for reporting! :+1:

**Comment by rrrene** [comment]
@ramonsnir could you check if this is still a problem with the current version?

**Comment by ramonsnir** [comment]
Resolved! (sorry, was abroad)
