### ISSUE TITLE
Ignore ansi_color metadata key

### ISSUE THREAD

**Issue by fuelen** [rrrene/credo#1036]
This key has a special behaviour: https://github.com/elixir-lang/elixir/commit/e0385040816e324832050e606fad859b8452011b

Additionally, I've created an issue here https://github.com/elixir-lang/elixir/issues/12489 to document this 

### Environment

* Credo version (`mix credo -v`): 1.7.0-ref.main.8d0e794+uncommittedchanges
* Erlang/Elixir version (`elixir -v`): OTP 25/1.14.2
* Operating system: Linux

### What were you trying to do?
```
Logger.debug("test", ansi_color: :yellow)
```

### Expected outcome
No warning

### Actual outcome
```
┃ [W] ↗ Logger metadata key ansi_color will be ignored in production
```

**Comment by rrrene** [comment]
This is part of `1.7.2-rc.3` :+1:

**Comment by rrrene** [comment]
This is part of Credo `1.7.2`. :+1:
