### ISSUE TITLE
Sarif output cannot be parsed by `github/codeql-action/upload-sarif@v2`

### ISSUE THREAD

**Issue by Kloenk** [rrrene/credo#1038]
### Environment

* Credo version (`mix credo -v`): 1.7.0-ref.oauth2.be3f0bb+uncommittedchanges
* Erlang/Elixir version (`elixir -v`):
```
Erlang/OTP 24 [erts-12.3.2.5] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```
* Operating system: linux (nixos, github:NixOS/nixpkgs/9ef6e7727f4c31507627815d4f8679c5841efb00)

### What were you trying to do?
Uploading the SARIF output to github via a CI to analyze the errors in the web ui.

### Expected outcome
The sarif output should be parsable by githubs codeql parser.

### Actual outcome
Github failes the pipeline with multiple instances of the following error:
```json
Error details: instance.runs[0].results[42].locations[0].physicalLocation.region.snippet.text is not of a type(s) string
  {
    "property": "instance.runs[0].results[42].locations[0].physicalLocation.region.snippet.text",
    "message": "is not of a type(s) string",
    "schema": {
      "description": "UTF-8-encoded content from a text artifact.",
      "type": "string"
    },
    "name": "type",
    "argument": [
      "string"
    ],
    "stack": "instance.runs[0].results[42].locations[0].physicalLocation.region.snippet.text is not of a type(s) string"
  }
```

Looking into the Sarif file, only some errors seems to create this error, one seems to be EX3033 (with contains only one clause)

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It should now be fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍  (and sorry that this took so long)

**Comment by rrrene** [comment]
Checking in: Any news?

**Comment by Kloenk** [comment]
Currently don't have an active elixir project, so not really anything to test sadly.

**Comment by rrrene** [comment]
Checked it. Seems to work. Thx for reporting!
