### ISSUE TITLE
Compilation error in file lib/credo/check/consistency/exception_names.ex

### ISSUE THREAD

**Issue by ivan-srsen** [rrrene/credo#1041]
### Precheck

== Compilation error in file lib/credo/check/consistency/exception_names.ex ==
** (RuntimeError) Could not find key `id` in [:base_priority, :category, :elixir_version, :exit_status, :explanations, :param_defaults, :run_on_all, :tags]
    lib/credo/check.ex:189: anonymous fn/1 in Credo.Check."MACRO-__using__"/2
    (elixir 1.13.4) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    expanding macro: Credo.Check.__using__/1
    lib/credo/check/consistency/exception_names.ex:2: Credo.Check.Consistency.ExceptionNames (module)
    (elixir 1.13.4) expanding macro: Kernel.use/2
    lib/credo/check/consistency/exception_names.ex:2: Credo.Check.Consistency.ExceptionNames (module)

### Environment

* 1.7.0
* Erlang/OTP 25 - Elixir 1.13.4
* Operating system: macOS

### What were you trying to do?
Trying to compile the project, but it fails

### Expected outcome
Compile passes

### Actual outcome
Compile fails

**Comment by rrrene** [comment]
I am closing this because I am fairly certain we fixed it. Sorry for being so late to respond.

If this is still an issue, please re-open this :+1:
