### ISSUE TITLE
Analyzing a single file through stdin is slow when individual check configs use `:excluded` option

### ISSUE THREAD

**Issue by doughsay** [rrrene/credo#1054]
### Environment

* Credo version (`mix credo -v`):

```
1.7.0-ref.version-updates.7b967c3d+uncommittedchanges
```

* Erlang/Elixir version (`elixir -v`):

```
Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.5 (compiled with Erlang/OTP 25)
```

* Operating system:

```
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

### What were you trying to do?

I'm using the new `lexical_credo` plugin for the new `lexical` language server, which uses the `--read-from-stdin` credo flag when analyzing the single file you have open. The plugin expects analysis to complete in 50ms or less or it times out and doesn't display results.  This works fine most of the time (analysis on a single file from stdin is 10's of ms or less usually).

But: if you have a `.credo.exs` file with excluded files configured for a specific check, e.g.:

```
{Credo.Check.Consistency.MultiAliasImportRequireUse, files: %{excluded: ["lib/my_app_web.ex"]}},
```

...then the analysis takes a lot longer (~100-200ms).

### Expected outcome

I expect that analysis of a single file from stdin should take the same amount of time with or without the `excluded` option set on a specific check.

### Actual outcome

It takes too long and the plugin cannot display realtime results.

### See also:

https://github.com/lexical-lsp/lexical/pull/254

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍
