### ISSUE TITLE
Deprecation warning for Regex.regex?/1

### ISSUE THREAD

**Issue by thomasdziedzic-calmwave** [rrrene/credo#1059]
### Environment

* Credo version (`mix credo -v`):
  ```
  1.7.0-ref.td-mindray-port.bd0dc55
  ```
* Erlang/Elixir version (`elixir -v`):
  ```
  Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

  Elixir 1.15.3 (compiled with Erlang/OTP 26)
  ```
* Operating system:
  ```
  macOS 13.4.1 (c) (22F770820d)
  ```

### What were you trying to do?

Compile credo, it's working, but with warnings.

### Expected outcome

No warnings when compiling credo.

### Actual outcome

```
==> credo
Compiling 251 files (.ex)
warning: Regex.regex?/1 is deprecated. Use Kernel.is_struct(term, Regex) or pattern match on %Regex{} instead
  lib/credo/check/config_comment.ex:124: Credo.Check.ConfigComment.check_tuple_ignores_issue?/2

Generated credo app
```

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by thomasdziedzic-calmwave** [comment]
I don't see any more warning when I tried out the master branch, thanks!
