### ISSUE TITLE
Changing color scheme in vs code

### ISSUE THREAD

**Issue by qeezqeez** [rrrene/credo#1060]
### Environment

* Operating system: Windows 10
* vs code: 1.80.1

### What were you trying to do?

I took a screenshot in the vs code. There was an extension icon on the screen.

### Expected outcome

Because of the icon in the screenshot, the color scheme has changed.

![image](https://github.com/rrrene/credo/assets/86105478/3173488a-99f9-4c9b-89da-c1e5e0252700)

### Actual outcome
The color scheme remains the same.

![image](https://github.com/rrrene/credo/assets/86105478/b5d8be3a-32bf-4d9b-ac4d-311be1a20720)

**Comment by qeezqeez** [comment]
This happens wherever there is an extension icon.
![image](https://github.com/rrrene/credo/assets/86105478/e4b848d6-da69-4fa5-9098-dca83b41c32d)

**Comment by rrrene** [comment]
Would love to help, but I am not really understanding what this is about and the VS Code Extension is maintained by somebody else (seemingly in this repo: https://github.com/pantajoe/vscode-elixir-credo/ )

Please file an issue with them as I have no authority over their extension 👍
