### ISSUE TITLE
Check running by default?

### ISSUE THREAD

**Issue by gemantzu** [rrrene/credo#1062]
### Environment

* Credo version (`mix credo -v`): 1.7.0
* Erlang/Elixir version (`elixir -v`): checked multiple versions
* Operating system: MacOS

### What were you trying to do?

I was trying to run all my checks, which do not include `Credo.Check.Warning.MissedMetadataKeyInLoggerConfig` at all, so this check shouldn't be giving me issues.

### Expected outcome

No issues

### Actual outcome

Logger.metadata will be ignored in production.

This seems like a 1.7.0 only issue, 1.6 versions didn't give me this problem.

**Comment by rrrene** [comment]
Can you post the `.credo.exs` of the project you are having this issue in?

**Comment by rrrene** [comment]
@gemantzu Checking in: Any news on this?

**Comment by brettbeatty** [comment]
I'm seeing this too. Also credo 1.7.0, elixir 1.15.6, erlang 26.1.1 on MacOS.

I can continue to have issues even with an empty list of checks:
```elixir
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: [
          "lib/",
          "src/",
          "test/",
          "web/",
          "apps/*/lib/",
          "apps/*/src/",
          "apps/*/test/",
          "apps/*/web/"
        ],
        excluded: [~r"/_build/", ~r"/deps/", ~r"/node_modules/"]
      },
      strict: true,
      parse_timeout: 5000,
      color: true,
      checks: [
        # if I uncomment these, credo passes
        # {Credo.Check.Refactor.RedundantWithClauseResult, false},
        # {Credo.Check.Warning.MissedMetadataKeyInLoggerConfig, false}
      ]
    }
  ]
}
```
It seems that RedundantWithClauseResult and MissedMetadataKeyInLoggerConfig (maybe others my project passes) are both on-by-default. But I seem to be able to make them go away by explicitly disabling them.

**Comment by brettbeatty** [comment]
I was seeing this too, but I realized some checks now have a "this check is enabled by default" banner that I hadn't known to look for.
https://hexdocs.pm/credo/Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.html

**Comment by rrrene** [comment]
Just to be clear: There has been a set of default checks from the start and which checks are "on by default" has been evolving over the years. 

An important feature, [introduced in Credo 1.6](https://hexdocs.pm/credo/changelog.html#pinning-checks-in-a-project-s-config), is the ability to explicitly enable only the checks you want. 

Closing this as accepted behaviour. Please re-open if you disagree! 👍
