### ISSUE TITLE
module dependency check errors

### ISSUE THREAD

**Issue by epinault** [rrrene/credo#1067]
### Precheck

* Proposals for new features should be submitted via: https://github.com/rrrene/credo-proposals
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 1.7.x
* Erlang/Elixir version (`elixir -v`): 1.14.x
* Operating system: OSX Ventyra

### What were you trying to do?

I am trying to set Module Dependency check to ignore all core module as really those don t matter to me as much

### Expected outcome

Ignore all module specified in this list

```
      checks: [
        {Credo.Check.Refactor.ModuleDependencies, excluded_namespaces: [         
          DateTime,
          Kernel,
          GenServer,
          ]}
```

### Actual outcome

 * 2nd argument: not a valid pattern

    (stdlib 4.3.1.1) :binary.match("MyModule", DateTime)
    (elixir 1.14.5) lib/string.ex:2358: String.starts_with?/2
    (elixir 1.14.5) lib/enum.ex:4136: Enum.any_list/2
    lib/credo/check/refactor/module_dependencies.ex:81: Credo.Check.Refactor.ModuleDependencies.traverse/6
    (elixir 1.14.5) lib/macro.ex:595: Macro.traverse/4
    lib/credo/code.ex:40: Credo.Code.prewalk/3
    lib/credo/check/refactor/module_dependencies.ex:2: Credo.Check.Refactor.ModuleDependencies.do_run_on_source_file/3
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Function: #Function<9.54731987/0 in Credo.Check.Refactor.ModuleDependencies.do_run_on_all_source_files/3>
    Args: []
    

What I am finding out is that specifying them as string works 
```
      checks: [
        {Credo.Check.Refactor.ModuleDependencies, excluded_namespaces: [         
          "DateTime",
          "Kernel",
          "GenServer",
          ]}
```

maybe the doc needs some example on how to specify it. Also it would be nice to have an option to just ignore Elixir core module really

**Comment by rrrene** [comment]
Thx for reporting! 👍

**Comment by rrrene** [comment]
Thanks again for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by rrrene** [comment]
This is part of `1.7.2-rc.3` :+1:

**Comment by rrrene** [comment]
This is part of Credo `1.7.2`. :+1:

**Comment by epinault** [comment]
Thanks! Sorry end of the year been busy . Will test that next week when I am back to work and a repo that I know breaks

**Comment by rrrene** [comment]
@epinault no worries :v:
