### ISSUE TITLE
MissedMetadataKeyInLoggerConfig is incorrect

### ISSUE THREAD

**Issue by Coffei** [rrrene/credo#1070]
### Environment

* Credo version (`mix credo -v`): `1.7.0-ref.initial.292d461+uncommittedchanges`
* Erlang/Elixir version (`elixir -v`): Elixir `1.15.4`, Erlang `26.0.2`
* Operating system: Fedora 38

Using default credo config, just installed as a dependency.

### The issue

I have this in my code

```elixir
    Logger.metadata(job: job.id)
```

which produces this credo warning

```
┃       Logger metadata key job will be ignored in production
````

I have this in my `config/config.exs`

```elixir
config :logger, :default_formatter,
  format: "$time [$level] $metadata $message\n",
  metadata: [:job]
```

and my `config/prod.exs` is empty.

So I'd say the metadata should work fine in prod too. I tried running the app with `MIX_ENV=prod` and surely I can see the metadata in the log.

### Expected outcome

Credo shouldn't generate a warning in this case.

**Comment by rrrene** [comment]
Credo uses the current `console` logger config for its defaults: https://hexdocs.pm/credo/Credo.Check.Warning.MissedMetadataKeyInLoggerConfig.html#module-metadata_keys

If the defaults don't suffice, you unfortunately need to configure them (by hand or by script).

**Comment by Coffei** [comment]
Hi, the logger configuration changed a bit in Elixir 15. You no longer specify a `console` logger but rather use `:default_formatter` as in my example above, see https://hexdocs.pm/logger/Logger.html#module-configuration. The old configuration is still supported as noted here https://hexdocs.pm/logger/Logger.html#module-backends-and-backwards-compatibility. My config is just whatever the docs say I should use, I just added the metadata.

I think this check should support the new config too, since it's the default in Elixir 15 and I suppose new projects will use the new configuration more and more often.

**Comment by elishagreenwald** [comment]
+1 to this. I encountered the same issue

**Comment by rrrene** [comment]
@Coffei @elishagreenwald Thanks for reporting this 😀  This should now be fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by Coffei** [comment]
Yes, this is fixed on master, thanks!
