### ISSUE TITLE
Consistency Check Idea: Pattern-match assignment on the left vs right

### ISSUE THREAD

**Issue by Qqwy** [rrrene/credo#108]
Sparked by [this discussion on the ElixirForum](http://elixirforum.com/t/refactor-a-pattern-match/778/8), whose end result is something along the lines of 'it is a case of personal preference' I thought that it would be interesting to have a consistency check.

To summarize:

```
def show(conn, %{"messenger" => messenger} = params) do
  # ...
end
```

is a valid function definition.

And so is

```
def show(conn, params = %{"messenger" => messenger}) do
  # ...
end
```

Some people find the first example clearer to read(the pattern comes first and thus is easier to read), others the second(follows the same order as when outside of pattern-match, languages like Haskell use this order as well). Using them interchangeably is however probably a bad idea. So this seems like a good idea for a consistency check to me.

Is this a good idea?

**Comment by rrrene** [comment]
This is a very good idea.

Coincidentally I was reading through the Ecto source one or two nights ago and thinking the same thing! :+1:

**Comment by sstern6** [comment]
@rrrene would like to help take this on if thats ok.  I saw you self assigned but then put the tag `help wanted`.  Are you open to additional collaborators for this?

Thanks

**Comment by sstern6** [comment]
@rrrene Should have a PR open for this in the next day or so.

**Comment by sstern6** [comment]
@rrrene after you have confirmed and are content with the implementation, this can be closed(the PR was just merged).

Thanks

**Comment by Qqwy** [comment]
Thank you very much, @sstern6 and @rrrene! :heart_eyes:
