### ISSUE TITLE
Consider including CHANGELOG.md in the package?

### ISSUE THREAD

**Issue by thbar** [rrrene/credo#1081]
For maintenance, we use a convenient script (https://github.com/etalab/transport-site/blob/master/generate_deps_changelogs.exs) on PR which is able to automate the generation of changes like seen here https://github.com/etalab/transport-site/pull/3561.

It relies on `diff.hex.pm` to let us review each individual change.

A lot of packages integrate their `CHANGELOG.md` inside the hex pm package, which is very convenient because you see it right away there:

https://diff.hex.pm/diff/csv/3.0.5..3.2.0

The diff for credo does not show this:

https://diff.hex.pm/diff/credo/1.7.0..1.7.1

I wonder if you'd be OK to add that to the release to ease maintenance work?

Thanks for considering this!

**Comment by rrrene** [comment]
Great idea. I would merge a PR for this :+1:

**Comment by rrrene** [comment]
This is now live on `master`. Starting with the next release, `CHANGELOG.md` will be included in the package: 4904a066

**Comment by rrrene** [comment]
This is part of `1.7.2-rc.3` :+1:
