### ISSUE TITLE
Question: Is it possible to define a .credo.exs in a dependency with custom checks and apply it when running mix credo in a project

### ISSUE THREAD

**Issue by jsolana** [rrrene/credo#1083]
Hi mates! I have a question related about if is possible to define an internal .credo.exs in a dependency library with custom checks, eg: `my_credo_checks`, add this dependency to a project, eg: `my_project` and when run `mix credo` run the default checks + custom checks defined in `my_credo_checks`. 

**The idea is to avoid (if is possible) create a .credo.exs file in every project defining the checks as is described** [here](https://hexdocs.pm/credo/adding_checks.html).

Thanks a lot!!

# Environment

## Credo version (mix credo -v):
Version 1.7.1

## Erlang/Elixir version (elixir -v):
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 23)

## Operating system (sw_vers):

ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83

# Expected outcome
Have a `my_custom_checks` project with a .credo.exs file with all checks configured as is described [here](https://hexdocs.pm/credo/adding_checks.html).
Add this dependency to a project, `my_project` and when run `mix credo` run all default checks + custom checks defined in `my_custom_check`.

# Actual outcome
Running `mix credo` in `my_project` only run default checks.
I need to add a .credo.exs config file with the custom checks  to run them when run `mix credo`

**Comment by rrrene** [comment]
You can do that by making `my_custom_checks` a [Credo plugin](https://hexdocs.pm/credo/creating_plugins.html) (which [has to be enabled in your config](https://hexdocs.pm/credo/using_plugins.html)). 

That plugin then has to add a default config via [`Credo.Plugin.register_default_config/2`](https://hexdocs.pm/credo/Credo.Plugin.html#register_default_config/2).

The config you're adding has to add your checks using the `:extra` key (the last part is important, see [here](https://hexdocs.pm/credo/config_file.html#checks) and scroll down to `:extra`).

Again: The plugin has to be enabled via a project config or a global one.

**Comment by jsolana** [comment]
Hi! I tried a different approach [in this example](https://github.com/jsolana/my_credo)
Define a lib with checks and a .credo.exs file.
Then in the project I want to apply those checks, I can run 
`    mix credo --config-name my-rules --config-file ./deps/my_credo/config/.credo.exs`

I can define [aliases](https://hexdocs.pm/mix/1.15.7/Mix.html#module-aliases) to run this

Wdyt?

It is better with the plugin approach? What I want to do is to use this new checks to be executed in CI/CD pipelines too, and the most seamlessly and less manual work to be done integration the best :)

Thanks a lot!!

**Comment by rrrene** [comment]
@jsolana your approach is fine and pragmatic. It might even be more transparent for someone new to a project 👍
