### ISSUE TITLE
Add list of standard checks to docs

### ISSUE THREAD

**Issue by tfwright** [rrrene/credo#1086]
I am actually guessing this is not a bug but I can't find any documentation/explanation around this behavior so I'm reporting it here first just in case.

Based on README my assumption all built in checks are applied and only custom checks, or checks with modified behavior need configuration.

Apologies if I've missed something but if it is expected that there are built in checks that must be included explicitly this should be front and center in the docs and additionally it would be helpful to have an easily accessible list of those checks.

### Environment

* Credo version 1.7

### What were you trying to do?

Run credo with all checks (strict)

### Expected outcome

All checks applied

### Actual outcome

PipeChainStart is not checked unless I add the following to my check config: `{Credo.Check.Refactor.PipeChainStart, []}`

**Comment by rrrene** [comment]
Hi, not all checks are enabled by default. 

Credo's documentation does not yet provide an overview for which checks are envaled by default 😢

Will use this issue to add that 👍

**Comment by rrrene** [comment]
Added a section "Default Checks" to the Config docs: https://hexdocs.pm/credo/1.7.2-rc.4/config_file.html#default-checks

:+1:
