### ISSUE TITLE
0.4 not reading .credo.exs correctly?

### ISSUE THREAD

**Issue by ramonsnir** [rrrene/credo#113]
I upgraded credo from 0.3.x to 0.4.x, and suddenly all the warnings/etc. I customized and tuned are back to their default settings.

The file is still there, but for some reason is ignored.

Upgraded by changing mix.exs to reference `~> 0.4` and running `mix deps.update --all`, then running again `mix credo --list`.

**Comment by ramonsnir** [comment]
Whoops!

**Comment by rrrene** [comment]
No problem! Never hesitate to open an issue! :+1:

I just released `v0.4.2` because I missed #112 so if you find something there is a high probability that I overlooked something and it's a valid issue. :grin:

**Comment by ramonsnir** [comment]
Yep, that's a better comment :smile:
