### ISSUE TITLE
Predicate function names should not start with 'is', and should end in a question mark flagged for :ets.whereis

### ISSUE THREAD

**Issue by simondelacourt** [rrrene/credo#1130]
After upgrading to Credo 1.7.6 from 1.7.5 I've noticed that the :ets.whereis function is flagged als following;

┃ [R] ↗ Predicate function names should not start with 'is', and should end in a 00:03
┃       question mark.

The issue, at least in the way I look at it, is that this function comes from OTP, and I don't really assume they'd be open to rename this function so it matches credo. I can ignore it locally of course, but I'd assume I'm not the only one using :ets.whereis

**Comment by rrrene** [comment]
This sounds strange. Can you provide a complete code sample that triggers this?

**Comment by simondelacourt** [comment]
> This sounds strange. Can you provide a complete code sample that triggers this?

@rrrene to be honest, I've completely misread my own code. My dearest apologies. Thanks for the response and credo itself :)
