### ISSUE TITLE
Dependency divergence on compile

### ISSUE THREAD

**Issue by fmarigarcia** [rrrene/credo#1134]
### Environment

* Credo version (`mix credo -v`): 1.7.6
* Erlang/Elixir version (`elixir -v`): 1.16.2 OTP 26

### What were you trying to do?

Run our scheduler app: `mix run --no-halt`

### Expected outcome

App running correctly

### Actual outcome

> Unchecked dependencies for environment dev:
> * jason (Hex package)
>   the :only option for dependency jason
> 
>   > In /elixir/deps/credo/mix.exs:
>     {:jason, "~> 1.1", [env: :prod, hex: "jason", repo: "hexpm", optional: false]}
> 
>   does not match the :only option calculated for
> 
>   > In /elixir/deps/goth/mix.exs:
>     {:jason, "~> 1.1", [env: :prod, hex: "jason", repo: "hexpm", optional: false]}
> 
>   Remove the :only restriction from your dep
> ** (Mix) Can't continue due to errors on dependencies

**Comment by rrrene** [comment]
I am not sure what the "problem" is ...

Goth has a [requirement for `:jason` of `~> 1.1`](https://github.com/peburrows/goth/blob/2eeff14288043407f41e6efdedb75b54d72a7a69/mix.exs#L43) and [`:credo` of `~1.0`](https://github.com/rrrene/credo/blob/91525ada8cf4f40d000f6b521d1df98b50c2ef9b/mix.exs#L153) ... 

Excuse my ignorance, but what is it you are asking us to do?

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.
