### ISSUE TITLE
quoted parentheses/brackets in heredocs

### ISSUE THREAD

**Issue by moccos** [rrrene/credo#114]
When heredocs contain quoted brackets:

    s = ~s"""
    "[ ]"
    """

credo 0.4.3 checks this string.

    ┃ [C] ↗ There is no whitespace around parentheses/brackets most of the time, but here there is.
    ┃
    ┃           "[ ]"

**Comment by rrrene** [comment]
Uh, yeah, that's a bug. Thx for reporting! :+1:

**Comment by sstern6** [comment]
@moccos thank you for the report.  Was able to reproduce with up to date version of `credo`.

@rrrene saw you self assigned, I am currently looking into it and have the capacity to get this out.

Are you ok with that?
