### ISSUE TITLE
By default each pin operator increases size in ABCSize refactor check 

### ISSUE THREAD

**Issue by Eiji7** [rrrene/credo#1155]
### Environment

* Credo version (`mix credo -v`):
```
$ mix credo -v
1.7.8-ref.main.1d74cf6+uncommittedchanges
```
* Erlang/Elixir version (`elixir -v`):
```
$ elixir -v
Erlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

Elixir 1.17.3 (compiled with Erlang/OTP 27)
```
* Operating system:
> Gentoo Linux using `desktop/plasma` profile for version `23.0` and with kernel version `6.6.41`.

### What were you trying to do?

I'm trying to add `pin` (`^`) operator to pattern-matching.

### Expected outcome

The pin operator does not affects `ABC` size or at least it should increase only by one no matter how much pin operators are used.

### Actual outcome

When calling `credo` on a simple function each **pin** (`^`) operator by default increases `ABC` size by `1` which is ridiculous. Using a pin operator does not makes code less clean/readable and is terribly important in pattern-matching.

**Comment by rrrene** [comment]
Thx for reporting! :+1:

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by Eiji7** [comment]
@rrrene I can confirm that message disappear when using `credo` from git, thanks! 👍
