### ISSUE TITLE
Argument error in latest stable version

### ISSUE THREAD

**Issue by acconrad** [rrrene/credo#116]
I upgraded from 0.1.9 to 0.4.3 and received this error when trying to run `mix credo` or `mix credo list` in the root folder of my Phoenix project:

``` shell
** (ArgumentError) argument error
    (stdlib) :ets.lookup(118821, :"$$installs2$$")
    (hex) lib/hex/registry.ex:58: Hex.Registry.info_installs/0
    lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
    lib/credo/cli.ex:92: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
```

**Comment by rrrene** [comment]
So, the error is emitted by Hex. Do you have the newest Hex version installed? Run `mix local.hex` to ensure. If the error persists, we have to dig further.

Thx for reporting! :+1:

**Comment by rrrene** [comment]
@acconrad any news on this?

**Comment by acconrad** [comment]
I will upgrade tonight and get back to you, thanks for following up!

**Comment by rrrene** [comment]
We had a related again and added a permanent fix. This should not be problem any longer. Thx for reporting! :+1:
