### ISSUE TITLE
Possibly ignore @spec on line length checks

### ISSUE THREAD

**Issue by sgtpepper43** [rrrene/credo#120]
There's currently on option to ignore function definitions when checking line length, and I think `@spec` kind of goes along with a function definition, and there should maybe be an option to ignore those as well. That might be a terrible practice though, I have no idea.

As a side note, I noticed there's also an option to ignore line length for strings, though that hasn't been implemented yet. Are there plans to add it in any time soon?

**Comment by rrrene** [comment]
:+1: I agree that should be an option.

Re: ignoring strings - please create a separate issue to pressure me into implementing it :wink:
