### ISSUE TITLE
unquote is misinterpreted within quote

### ISSUE THREAD

**Issue by stelcheck** [rrrene/credo#123]
```
Parameter `unquote` has same name as a function in the same module.
┃       lib/ops.ex:68:11 (Datanator.Ops.for_list)
┃
┃    __ CODE IN QUESTION
┃
┃       def unquote(name)(unquote(parent), unquote(subkey) = [head | _], unquote_splicing(args))
```

It seems like credo misses the fact that the name of the function is dynamically generated.

**Comment by rrrene** [comment]
Uh. That's look a bug :sweat_smile: Thx for reporting!

**Comment by stelcheck** [comment]
My pleasure. Let me know if I can provide you with additional information, can do Slack as well if needed.

P.S. Credo is pretty damn awesome :)

**Comment by rrrene** [comment]
Could you provide a complete code snippet which triggers this? I tried to reproduce this, but my first attempts weren't successful ...

**Comment by rrrene** [comment]
*push*

**Comment by stelcheck** [comment]
Sorry for the delay. 

I just upgraded credo, and everything seems fine now... apologies for wasting your time. 

For reference, here is the function that previously caused an issue:

```elixir
defp generate_function_signature(name, parent, subkey, args) do
  quote do
    unquote(name)(unquote(parent), unquote(subkey) = [head | _], unquote_splicing(args))
  end
end
```

**Comment by rrrene** [comment]
> apologies for wasting your time

Don't ever say that when it comes to bug-reporting. While I do believe in TDD, actual user testing in the wild is the oxygen of useful software. 

Thx for taking the time to write the bug report and never hesitate to write another! :+1:
