### ISSUE TITLE
Let me white-list functions for the RawValue check

### ISSUE THREAD

**Issue by sircharleswatson** [rrrene/credo#136]
The use case is that we're using RethinkDB and every update/insert/query command has to be started with getting the actual table first. so we have something like:

```elixir
table("users")
|> insert(%{name: "Bob Jones"})
|> DB.run
```

the suggested way to fix it is either:
```elixir
users_table = table("users")

users_table
|> insert(%{name: "Bob Jones"})
|> DB.run
```

or:

```elixir
"users"
|> table
|> insert(%{name: "Bob Jones"})
|> DB.run
```

But, arguably, the first snippet is cleaner and much easier to read

**Comment by hamiltop** [comment]
I'll chime in from the `RethinkDB` library perspective:

A ReQL pipeline is not a transformation of a string into data. Doing `"users" |> table` is indeed distracting and counter to the intent of the library. The subject of the query pipeline is `table("users")` and leading off with that is much clearer.

**Comment by rrrene** [comment]
This will be fixed in the next version (see commit reference above).

**Comment by rrrene** [comment]
Credo `v0.4.8` was just released and contains the fix.
