### ISSUE TITLE
Getting issues as return value from the task. 

### ISSUE THREAD

**Issue by Sbfrr** [rrrene/credo#139]
Hi,

Thanks for your great work. 
I'm trying to setup a unit test that basically runs credo and fails if an issue is returned from it.
Basically I'm just running the task programmatically with:

```elixir
Credo.CLI.main(["."])
```

and trying to expect something out of the return value. However looking at the code of `lib/credo/cli.ex`: 

```elixir
  def main(argv) do
    Credo.start nil, nil

    argv
    |> run()
    |> to_exit_status()
    |> halt_if_failed()
  end
```

it seems that the call to `halt_if_failed` makes the Erlang runtime system stop whenever Credo finds issues and makes it impossible to get it as a return value in order to make something out of it programmatically. I've tried to use the `--crash_on_error` options, thinking that it could just let the process crash instead of stopping the whole runtime system but I could not get it working. 

Can you please let me know if there is a way to get issues as return value from the mix task or if it's something you've already thought about. I'd be glad to help if it has not been done and if you consider it useful for the project. Thanks in advance.

**Comment by rrrene** [comment]
A Mix task is by definition a command line interface (and `Credo.CLI` is one as well :wink:).

What you most likely want to do is run Credo programmatically. Here is an example where people have done just that: https://github.com/inaka/credo_server/blob/4ad92e6db0c2f0a9b4f307fe291387e3bac0e1fa/lib/credo_webhook.ex#L34

Does that answer your (very well described :+1:) problem?

**Comment by Sbfrr** [comment]
Thanks a lot, that's exactly what I was looking for 👍
