### ISSUE TITLE
False positive on large numbers

### ISSUE THREAD

**Issue by AndrewDryga** [rrrene/credo#145]
https://travis-ci.org/Nebo15/bsoneach/jobs/150446288#L553
but it's already written correctly
https://github.com/Nebo15/bsoneach/blob/master/lib/bson/utils.ex#L32

**Comment by rrrene** [comment]
I just released Credo v0.4.8, which should fix this. Could you take a look?

**Comment by AndrewDryga** [comment]
Everything is ok now, thanks! 👍
