### ISSUE TITLE
Is there a way to use credo with syntastic?

### ISSUE THREAD

**Issue by squaresurf** [rrrene/credo#152]
I just have question in the title about whether or not there is a way to configure [syntastic](https://github.com/scrooloose/syntastic) to use credo in order to lint my elixir as I write it.

**Comment by rrrene** [comment]
Not that I know of, but take this with a large grain of salt, as I am not a vim user.

**Comment by squaresurf** [comment]
Do you have integration with the text editor you use? For example, credo running on files as they are saved, then highlighting the lines that need improvement. If you do have it integrated with your editor, then what editor do you use?

**Comment by rrrene** [comment]
I have not, but I have integrations with Emacs and Atom editor. I am pretty sure people are using Credo with Vim. 

Let's see if people will comment here with more information.

**Comment by OvermindDL1** [comment]
I'm not currently using credo with vim (actually using more atom than vim lately, this surprises me, but credo works fantastic with atom), but it should not be hard to add, basically just alter/copy https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/elixir/elixir.vim to add credo to its checking (if exists), then PR it into syntastic so everyone could use it instead of just using it yourself.  ^.^

**Comment by nburkley** [comment]
While it's not syntastic, it looks like it's you can use it in neovim through neomake https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/elixir.vim#L18

**Comment by squaresurf** [comment]
Thank you all for your comments. I'll see if I can get some time soon to contribute a PR to syntastic.

**Comment by squaresurf** [comment]
I wrote a syntastic checker for credo. It appears to be a bit of work to finish and may not make it in after all of my work either. We'll see. I may end up using another tool in the end such as neomake.

https://github.com/scrooloose/syntastic/pull/1891

**Comment by squaresurf** [comment]
I've decided to go with neomake for now as it works quite well. For future visitors, it should be noted that neomake works with vim and neovim.

**Comment by rrrene** [comment]
@squaresurf Just a note: From scrooloose/syntastic#1891 I get that you did not use the output of `mix credo --format=flycheck`. That one should be easier to parse (just for future reference). :+1:

**Comment by squaresurf** [comment]
I chose to go with `--format=oneline` so that I could parse the priority rather than the category. If `--format=flycheck` had the priority I would have used it :smile:
