### ISSUE TITLE
If-statements in combination with the pipe operator

### ISSUE THREAD

**Issue by TBK145** [rrrene/credo#163]
Credo gives a message about the if condition not needing parentheses when it is piped into. Eg:
```elixir
boolean |> if(do: :ok, else: :error)
```
Will output:
```
  Code Readability                                                              
┃ 
┃ [R] ↗ The condition of `if` should not be wrapped in parentheses.
```
While in this case the parentheses are needed, and there is no condition.

**Comment by rrrene** [comment]
I was in the Us for ElixirConf these last days and have done a poor job of responding to issues.

This is now fixed and will be released in a new version in the coming days. Thx for reporting! :+1:
