### ISSUE TITLE
Don't print "showing priority issues" if there are no issues

### ISSUE THREAD

**Issue by PragTob** [rrrene/credo#166]
```
tobi@airship ~/github/benchee $ mix credo
==> credo
Compiling 120 files (.ex)
Generated credo app
Checking 7 source files ...

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.1 seconds (0.00s to load, 0.1s running checks)
64 mods/funs, found no issues.

Showing priority issues: ↑ ↗ →  (use `--strict` to show all issues, `--help` for options).
```

Talking about the last bit with the arrows, I don't think it's needed when there are no issues (although the hint to `--strict` is still good to have).

Of course, fairly low priority :D
Tobi

**Comment by rrrene** [comment]
That's a good point! :+1:

**Comment by sstern6** [comment]
@rrrene I believe this has been resolved and can be closed?

**Comment by rrrene** [comment]
Not sure. If we [look at the current implementation](https://github.com/rrrene/credo/blob/61b4690d0418594a67afe1fed6e8f0198761a405/lib/credo/cli/output/summary.ex#L47), I think we have to accomodate a case where we found no issues, but are not running in `--strict` mode (meaning `min_priority >= 0`).

In these cases we should just display 

    Use `--strict` to show all issues, `--help` for options`

Do you agree?

**Comment by sstern6** [comment]
@rrrene very much so agree, working on a PR now for the use case you just described.  If theres any changes that need to be made we can hash those out on the PR!

To confirm the use case:

`if the user does NOT have errors AND they are not running in --strict mode, show them , "Use `--strict` to show all issues, `--help` for options`"`?

THANKS
