### ISSUE TITLE
is there a way to specify `strict` in a config?

### ISSUE THREAD

**Issue by ToadJamb** [rrrene/credo#168]
I have tinkered around and perused the source, but I'm not seeing a way to set `strict` in a config. It makes sense to me that any command line parameters should be configurable in a config. Is this possible currently? I also tried elevating the priority on the low priority checks, to no avail.

**Comment by rrrene** [comment]
Good catch! :+1:

**Comment by ToadJamb** [comment]
I'm willing to attempt this, but I don't have a lot of time and I just started tinkering with elixir this weekend, so it may not happen quickly.

**Comment by sstern6** [comment]
@ToadJamb any progress on this?
