### ISSUE TITLE
Mix claims there is a new version of credo but tagged code finishes at 0.4.10

### ISSUE THREAD

**Issue by hazardfn** [rrrene/credo#172]
A new Credo version is available (0.4.11), please update with `mix deps.update credo`...

**Comment by rrrene** [comment]
I forgot to push the tag, sorry. How are you depending on Credo? I am asking because `0.4.11` has been on Hex for a while now: https://hex.pm/packages/credo/0.4.11

**Comment by hazardfn** [comment]
Yeah we have seen the warning for some time just thought to ask here now. 

We use credo as part of our CI - we use docker images to test on which build credo from source and run mix archive.build and install.

I think we originally did it this way so we could mirror repos in our private git and skip external dependencies such as hex and github. 

We are experimenting with creating our own internal hex but it isn't complete yet :) thanks for your work on this great project and for replying so quickly!

**Comment by rrrene** [comment]
Ah, cool! :+1: As I explained, I forgot to push the last release, which is now fixed and was an oversight on my part!
