### ISSUE TITLE
function_name used for Stream.repeatedly includes argument

### ISSUE THREAD

**Issue by KronicDeth** [rrrene/credo#173]
I was trying to ignore `Stream.repeatedly` for `Credo.Check.Refactor.PipeChainStart` and I couldn't get it to work, so I added some print debugging and discovered the `function_name` includes the argument:

```
  defp valid_chain_start?({{:., _, _}, _, _} = ast, excluded_functions) do
    function_name = to_function_call_name(ast)

    if excluded_functions |> Enum.member?(function_name) do
      true
    else
      IO.puts "function_name = #{inspect function_name}"
      false
    end
  end
```

The `if` is the modification to the source.  The output:

```
function_name = "Stream.repeatedly(fn ->\n  {:ok, job_created_by_pid} = Client.Job.create_dag(interpreter_connection_created_by_pid, context)\n  {:ok, %{^job_client_pid => job}} = Client.Job.with_job_assignment_state(job_created_by_pid, context, %{}, \"invited\")\n  job\nend)"
```

From this test:

```
jobs = Stream.repeatedly(fn ->
             {:ok, job_created_by_pid} = Client.Job.create_dag(interpreter_connection_created_by_pid, context)
             {:ok, %{^job_client_pid => job}} = Client.Job.with_job_assignment_state(
               job_created_by_pid,
               context,
               %{},
               "invited"
             )

             job
           end)
           |> Enum.take(2)
```

**Comment by lucas-nelson** [comment]
I think the problem is at https://github.com/rrrene/credo/blob/2eb1094c37976dc855154d930d73c0d42d78cfeb/lib/credo/check/refactor/pipe_chain_start.ex#L68
```
    |> String.replace(~r/\.?\(.*\)$/, "")
```
The regex needs to include newlines in your case. I think the fix is:
```
    |> String.replace(~r/\.?\(.*\)$/s, "")
```
Adding the `s` modifier on the regex (*dotall*, see http://elixir-lang.org/docs/v1.3/elixir/Regex.html#module-modifiers) makes the `.` in the pattern include newlines in the match.

**Comment by rrrene** [comment]
@KronicDeth Thx for reporting!

@lucas-nelson Thx! That was the fix! :+1:
