### ISSUE TITLE
Ability to ignore length of @typedoc (or any @*doc) to support wide markdown tables

### ISSUE THREAD

**Issue by KronicDeth** [rrrene/credo#174]
I have a transition table in Markdown table format in a `@typedoc`.  It exceeds the normal `max_length: 120` I have setup for `Credo.Check.Readability.MaxLineLength`, but I can't use @lint because @lint doesn't attach to `@typedoc` or `defmodule`, so I'm left with ignoring the whole module.

**Comment by rrrene** [comment]
Good point! Maybe we want an option for `MaxLineLength` to ignore lines matching a user-defined regex?

**Comment by devonestes** [comment]
We now have an option in `MaxLineLength` to ignore strings, which we could expand to also ignore strings that are part of `@typedoc`, `@moduledoc` and even `@doc` attributes. Alternatively, we could include specific options to ignore any strings only in those attributes.

I can see good arguments for both options - what do you think? More configuration is kind of a bummer for the user (and it's more code for us to maintain), but I can see where users would still want to keep the line length check for non-documentation strings in a given project. Or, we could also do the "ignore a string matching a certain regex" option, too.

**Comment by rrrene** [comment]
In my opinion the `ignore_strings` option has us covered here. I'm not sure there is an argument like "I want to ignore certain long strings for some kinds of module attributes, BUT I want to get an issue for other strings in other situations".

Like always, I am open to be convinced otherwise; but I imagine the above position is not a very common one to hold.

**Comment by devonestes** [comment]
I'm cool with that logic!

**Comment by rrrene** [comment]
@KronicDeth I think this can be closed, as the (now existing) options should cover us here.

If this is not the case, please re-open! :+1:
