### ISSUE TITLE
Consistency check: let SpaceInParenthesis allow empty params without space

### ISSUE THREAD

**Issue by sriedel** [rrrene/credo#176]
It would be nice to allow things like %{} or def my_fun( [] ) even if the rest of the code uses spaces within parenthesis. This should only be allowed if an opening paren is followed by its corresponding closing paren.

I had a naive stab at implementing this by extending the create_issue? function for the (assumed) triggers "{}", "[]", "()", but this doesn't seem to be correct. If you could give me a pointer in how to correctly specify the triggers, I can have a go at implementing this functionality.

**Comment by Selvaticus** [comment]
Hi @sriedel,

Is this still an issue?

**Comment by rrrene** [comment]
Hi, thx again for this. Unfortunately, I am closing it due to "it being obsolete" IMHO. 

If you disagree, please re-open and elaborate! :+1:
