### ISSUE TITLE
Not possible to turn of Alias

### ISSUE THREAD

**Issue by olafura** [rrrene/credo#180]
I'm using an absolute path in a macro because I can't control what is aliased in the module the function is placed into so I tried turning doing 
@lint {Credo.Check.Design.AliasUsage, false}
in a couple of different places as well as trying to turn it off globally. We are using --strict, but the funny thing if I have these blocks on Alias explain stops telling me anything so it is working in some respect but not totally.

**Comment by rrrene** [comment]
FYI: `@lint`, much like `@doc`, only works on functions. There are no plans to change this behaviour. 

Could you post an excerpt of your code? The fact that global disabling doesn't work worries me.

**Comment by KronicDeth** [comment]
Here's a version where I couldn't `@lint` on either the `def` or `defp`:

```
 defp quoted_action(quoted_name, quoted_configuration) do
    quote do
      def unquote(quoted_name)(conn, params) do
        Calcinator.Controller.unquote(quoted_name)(conn, params, unquote(quoted_configuration))
      end
    end
  end
```

**Comment by rrrene** [comment]
Thx @KronicDeth! :+1:

**Comment by rrrene** [comment]
I am closing this, since the bug/behaviour/functionality described here is related to `@lint` attributes, which will be removed in favor of more flexible comment-based syntax.

Please refer to #291 for the related discussion :+1:
