### ISSUE TITLE
@lint rule exception does not disable checks on constants

### ISSUE THREAD

**Issue by robertpeacock22** [rrrene/credo#181]
Given a constant defined using a module attribute and annotated with a lint exception, the associated check is still performed and reported.

```
@lint {Credo.Check.Readability.LargeNumbers, false}
@some_constant 1000000
```

`[R] ↗ Large numbers should be written with underscores: 1_000_000`

**Comment by rrrene** [comment]
`@lint`, much like `@doc`, only works on functions. Unfortunately, there are no plans to change this behaviour. 

There was a discussion about adding a `@modulelint` attribute to exclude a check for a whole module. But I am not sure that would in this case, either 😞

**Comment by robertpeacock22** [comment]
Darn. Thanks @rrrene!
