### ISSUE TITLE
Double negative

### ISSUE THREAD

**Issue by pinx** [rrrene/credo#187]
You have a great sense of humor:
"If/else blocks should not have a negated condition in `if`."
May I propose:
"If/else blocks should have a positive condition in `if`."

**Comment by rrrene** [comment]
I was not sure if a "negated condition" is the same thing as a "negative condition" and therefore I was hesitant to call a "not negated conditions" a "positive" one ...

I am not a native speaker, therefore I am not entirely sure those expressions mean strictly the same thing (honestly, please correct me if I am wrong). :+1:

**Comment by pinx** [comment]
I'm not a native speaker, either. I checked a few linters. You could rephrase to "Avoid negated conditions in if-else blocks".

**Comment by rrrene** [comment]
:+1: thx!
