### ISSUE TITLE
Better support in umbrella projects

### ISSUE THREAD

**Issue by NobbZ** [rrrene/credo#194]
Currently the bahviour is, that credo just steps into `apps/` and analyzes all files recursively.

This causes, that I do need to exclude my `priv`-folder via a regular expression in the settings and my testfolder as well.

So it seems that in a standalone application we do whitelisting the folders which needs to get checked, and credo will ignore everything else, while in an umbrella project this actually turns into blacklisting stuff not to check.

It would be nice if there were the possibility to tell credo that we have an umbrella, tell it which is the `apps`-folder and from then on, `:include` and `:exclude` keys in the config are checked from the sub-app-root.

**Comment by rrrene** [comment]
This is indeed a problem, thx for bringing it up. I am currently on vacation (and a spotty wifi). Will be back next weekend.

btw: Aren't you from (around) Hamburg? Will we get a chance to meet at the November meeting?

**Comment by NobbZ** [comment]
Take your time! Maybe I can find some time to spare and take a look at it myself.

And yes, I am from around Hamburg and I got OKs from my wife and my son, but my unborn may veto 👶

**Comment by wpcarro** [comment]
Are there any updates related to enhanced umbrella app support?

**Comment by rrrene** [comment]
@wpcarro What kind of "enhanced support" would you like to see (except for the more convenient handling of app sub-folders)?

**Comment by wfgilman** [comment]
Being able to run credo dynamically for a specific app within an umbrella project would be awesome: `mix credit --myapp`

**Comment by rrrene** [comment]
I think this can be closed and any further enhancement requests should be opened as new issue, since very much has changed since the original issue was reported.

Thx for all the input and please do not hesitate to open new issue anytime you find something fishy in Credo :+1:
