### ISSUE TITLE
Repo Issue Organization Proposal/Discussion

### ISSUE THREAD

**Issue by sstern6** [rrrene/credo#200]
@rrrene I personally think it would be valuable for the project as more and more people continue to use credo and file issues to have a format of required information when submitting an issue.  We can document this on the main README.

To name a few things I think would be important: credo version, mix version???, elixir version???, hex version??, what you expected to happen, what actually happened etc.

I think this would streamline the issue patching process and prevent back and fourth when all necessary information is provided upfront.

Thoughts?

Thank you

**Comment by rrrene** [comment]
Agreed. I provided an `ISSUE_TEMPLATE.md` which we can modify to prefill new issues: https://github.com/rrrene/credo/issues/new

**Comment by sstern6** [comment]
Looks great!

Thanks @rrrene

**Comment by NobbZ** [comment]
There is a Github feature which copies the content of a certain file into
the text box of a new issue, this would be much better than just a
paragraph in the read me. But I do remember how this file was called. But
afair elixir does use this feature.

Scott Stern <notifications@github.com> schrieb am Mo., 24. Okt. 2016 23:33:

**Comment by rrrene** [comment]
Oops, forgot to close this. 

@NobbZ Yep, it's already done. See my comment above. ;-)
