### ISSUE TITLE
Default .credo.exs file from library always loaded / used?

### ISSUE THREAD

**Issue by svoynow** [rrrene/credo#202]
Elixir 1.3.2
Credo 0.4.12

For Credo development purposes I'm trying to run credo with a very stripped down config (i.e. only a couple of checks). I was seeing some weird behavior (unwanted checks running), so I poked around in the config code.

It looks to me like the .credo.exs that comes with the library (the intended purpose of which is just to be a template for the gen.config task, I believe) is actually loaded every time.

looks like this bit of `config.ex`
```
  @config_filename ".credo.exs"
  @default_config_name "default"
  @default_config_file File.read!(@config_filename)
```
results in @default_config_file always being the contents of that file and getting merged in to the runtime config.

Am I crazy?

**Comment by rrrene** [comment]
> Am I crazy?

Nope. :grin:

> ... (the intended purpose of which is just to be a template for the gen.config task, I believe) ...

The intended purpose is twofold: it is the template for the gen.config task, but it is also the default config into which your local config is merged. You can have several `.credo.exs` files in the file tree up until your home dir. Those and the default config will then be merged recursively.

What you want to do is deactivate undesired checks using `false` as second tuple-element. This is a completely deactivated setup (for your convenience):

      checks: [
        {Credo.Check.Consistency.ExceptionNames, false},
        {Credo.Check.Consistency.LineEndings, false},
        {Credo.Check.Consistency.SpaceAroundOperators, false},
        {Credo.Check.Consistency.SpaceInParentheses, false},
        {Credo.Check.Consistency.TabsOrSpaces, false},

        {Credo.Check.Design.AliasUsage, false},
        {Credo.Check.Design.DuplicatedCode, false},
        {Credo.Check.Design.TagTODO, false},
        {Credo.Check.Design.TagFIXME, false},

        {Credo.Check.Readability.FunctionNames, false},
        {Credo.Check.Readability.LargeNumbers, false},
        {Credo.Check.Readability.MaxLineLength, false},
        {Credo.Check.Readability.ModuleAttributeNames, false},
        {Credo.Check.Readability.ModuleDoc, false},
        {Credo.Check.Readability.ModuleNames, false},
        {Credo.Check.Readability.ParenthesesInCondition, false},
        {Credo.Check.Readability.PredicateFunctionNames, false},
        {Credo.Check.Readability.TrailingBlankLine, false},
        {Credo.Check.Readability.TrailingWhiteSpace, false},
        {Credo.Check.Readability.VariableNames, false},

        {Credo.Check.Refactor.ABCSize, false},
        {Credo.Check.Refactor.CondStatements, false},
        {Credo.Check.Refactor.FunctionArity, false},
        {Credo.Check.Refactor.MatchInCondition, false},
        {Credo.Check.Refactor.PipeChainStart, false},
        {Credo.Check.Refactor.CyclomaticComplexity, false},
        {Credo.Check.Refactor.NegatedConditionsInUnless, false},
        {Credo.Check.Refactor.NegatedConditionsWithElse, false},
        {Credo.Check.Refactor.Nesting, false},
        {Credo.Check.Refactor.UnlessWithElse, false},

        {Credo.Check.Warning.IExPry, false},
        {Credo.Check.Warning.IoInspect, false},
        {Credo.Check.Warning.NameRedeclarationByAssignment, false},
        {Credo.Check.Warning.NameRedeclarationByCase, false},
        {Credo.Check.Warning.NameRedeclarationByDef, false},
        {Credo.Check.Warning.NameRedeclarationByFn, false},
        {Credo.Check.Warning.OperationOnSameValues, false},
        {Credo.Check.Warning.BoolOperationOnSameValues, false},
        {Credo.Check.Warning.UnusedEnumOperation, false},
        {Credo.Check.Warning.UnusedKeywordOperation, false},
        {Credo.Check.Warning.UnusedListOperation, false},
        {Credo.Check.Warning.UnusedStringOperation, false},
        {Credo.Check.Warning.UnusedTupleOperation, false},
        {Credo.Check.Warning.OperationWithConstantResult, false},
      ]

**Comment by svoynow** [comment]
Got it. 
I still think this is mildly surprising.
I agree that it is good that there's a default so that there's always some config even if the user doesn't do anything. 
Maybe the least surprising thing would be to only use this default if no config files are found while traversing up from the project? Thoughts?

**Comment by rrrene** [comment]
I originally designed it the way you suggest. The behaviour was intentionally *changed* to this in `v0.4.0` after two insightful discussions (one [related discussion](https://github.com/rrrene/credo/issues/59), can't find the other one).

It basically comes down to: If you want to tweak a small number of checks to your liking, the new behaviour is preferable, because you do not have to know all check names and do not have to add new checks (from newer Credo versions) manually after updating.

**Comment by svoynow** [comment]
Yes, that makes sense.
