### ISSUE TITLE
Proposal: Missing @spec check for functions

### ISSUE THREAD

**Issue by asummers** [rrrene/credo#205]
Rationale: We love dialyzer. Being able to have our linter yell at us when we don't provide `@spec` annotations would be awesome. They serve as function documentation, as well as helping Dialyzer do its job better. Additionally, I think this rule would serve as amazing documentation on how one might check that all functions have a certain annotation (say Ecto with `@primary_key` and `@fields` or something). To me, these are both basically the same conceptual feature: given a module and it's functions, do all the `def`s and `defp`s have `@spec` annotations and for `@doc`, just `def`. 

Possible solution: Looking through some of the existing rules, I believe it can be accomplished relatively simply by traversing the AST by finding all `:def` and `:defp` function names/arity, making a set of those, and doing the same thing with `@spec`s, and then comparing those two sets. If they're not equal, you missed one. I tried extending the `@moduledoc` one but was unable to at first stab, however I think the approach above should get what is necessary for this.

**Comment by NobbZ** [comment]
At least the `@doc`-part is covered by [rrrene/inch_ex](https://github.com/rrrene/inch_ex) pretty well I think, but for the `@spec`-part of your proposal you get a very fat 👍. I was going to write just such a proposal ;)

**Comment by rrrene** [comment]
So basically require `@spec` on all functions?

**Comment by asummers** [comment]
Yep! Once that machinery is in place, there are more interesting things one can do like enforce consistency on use of parentheses after `map` or `atom` or use or `℅Struct{}` vs `Struct.t`, though I don't know if mainline Credo necessarily wants to be in the business of checking those.

**Comment by asummers** [comment]
Yep! Once that machinery is in place, there are more interesting things one
can do like enforce consistency on use of parentheses after map or atom or
use or ℅Struct{} vs Struct.t, though I don't know if mainline Credo
necessarily wants to be in the business of checking those.

**Comment by sorentwo** [comment]
I recently began working on @doc support (as I thought it would be easier than @spec). I managed to get a basic check working for `def`, `defmacro`, and `defcallback`, but it wasn't entirely accurate. After quite a bit of time looking at ex_doc and h I discovered they both use `Code.get_docs`. Unfortunately, `Code.get_docs` relies on a compiled .beam file for doc extraction, which isn't how Credo tests work currently.

After a lot of source diving I finally asked Jose, who said that trying to parse docs out of the source didn't make any sense, and suggested going the beam route. My guess is that the source parsing constraint only applies to credo's tests, and that we could work around that fairly easily by populating some compiled fixture modules into `test/fixtures`. The module doc check could use the same `get_docs/1` mechanism as well.

So far I've put a good bit of time into this and would like to see it through, However, I wanted to get your opinion @rrrene first.

**Comment by rrrene** [comment]
@sorentwo Thanks for your input. I really wish you would have talked to me in this issue first.

> My guess is that the source parsing constraint only applies to credo's tests

Unfortunately, this is wrong. Credo is a static analysis tool and will therefore *never* have features which require compiling the source. This is also why I have another project for that very use-case: [inch_ex](https://github.com/rrrene/inch_ex) (which was mentioned in this very threat)

> So far I've put a good bit of time into this and would like to see it through

As I said: I wish you would have asked me first (this issue was renamed from "Proposal: New rule - Missing @spec and @doc ..." to "Proposal: Missing @spec ..." for a reason). 😢 

That said: It would be immensely useful for Credo if you could apply the knowledge from your research to provide the proposed `@spec` check! 👍

**Comment by sorentwo** [comment]
@rrrene I know that inch_ex provides analysis for documentation, and it is a great tool. However, I happen to be one of those crazy people that use `strict` mode for CI and was trying to lock things down a bit.

Regardless, I learned a lot about Credo and Elixir documentation in general, so the experience was worthwhile. I'll apply the knowledge to a spec check soon.

**Comment by rrrene** [comment]
If it is any consolation: There is a plan to make Inch available as a Credo Plugin next year, which will bring the ability to run it on your CI through Credo. 
(We will just have to invent Credo plugins first ^_^)

**Comment by hauleth** [comment]
One more note. It would be great to have possibility to disable spec lint in some paths. For example it doesn't make much sense to have that lint on Phoenix controllers as their `@spec` should be well known and dialyzer will not be pointing that out.

**Comment by sorentwo** [comment]
@hauleth I agree, it should be configurable. I'll add some options for the checker that was merged in #279 and we can see if @rrrene agrees.

**Comment by rrrene** [comment]
Closing this. See #279 and #317
