### ISSUE TITLE
Non alphanumeric variable names

### ISSUE THREAD

**Issue by olafura** [rrrene/credo#208]
We are using ... as a variable name in a macro parameter and I think it doesn't make sense that it would be stopped for not being snake case. I added a no_case check.

**Comment by rrrene** [comment]
I did honestly not know that `... = parameter1` is valid Elixir.

Is that macro open sourced somewhere?

**Comment by olafura** [comment]
Not yet, but it will be maybe early next year. But `... = value` is valid. We are using:
`%{key: [%{key2: value}, ...] = subitem}`

I can make the PR so it's an optional parameter

**Comment by rrrene** [comment]
Okay, got it! Will review the PR.
