### ISSUE TITLE
Credo crashes with hex 0.14.0 due to using Hex.Utils.ensure_registry!/0

### ISSUE THREAD

**Issue by davydog187** [rrrene/credo#210]
### Precheck

* For proposing a new feature, be sure to name your issue "Proposal: ..."
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 0.4.13
* Erlang/Elixir version (`elixir -v`): 1.3.3
* Operating system: OSx El Capitan

### What where you trying to do?
Updated local.hex to 0.14.0, which breaks credo because its relying on a Hex Util thats no longer available.

### Expected outcome
It not to crash

### Actual outcome

```bash
$ mix credo
** (UndefinedFunctionError) function Hex.Utils.ensure_registry!/0 is undefined or private
    (hex) Hex.Utils.ensure_registry!()
    lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
    lib/credo/cli.ex:92: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by davydog187** [comment]
Looks like it was removed in this PR https://github.com/hexpm/hex/pull/300/files

It appears credo is relying on an undocumented API that it should not be.

**Comment by roehst** [comment]
Just happened to me.

** (UndefinedFunctionError) function Hex.Utils.ensure_registry!/0 is undefined or private
(hex) Hex.Utils.ensure_registry!()
lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
lib/credo/cli.ex:92: Credo.CLI.run/1
lib/credo/cli.ex:58: Credo.CLI.main/1
(mix) lib/mix/task.ex:296: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

**Comment by davydog187** [comment]
@roehst to revert back, `mix archive.install https://repo.hex.pm/installs/1.3.0/hex-0.13.2.ez`, FYI

**Comment by roehst** [comment]
@davydog187 tks a lot u just got my ass saved

**Comment by davydog187** [comment]
It looks like you can disable it in your credo config as well: https://github.com/rrrene/credo/blob/2c51773767fb4438403c4a6fac7422bbeba99c51/.credo.exs#L32

**Comment by rrrene** [comment]
@davydog187 @roehst Fixed in `0.5.0` - sorry this happened! 😭

**Comment by matteosister** [comment]
@rrrene awesome thanks!

**Comment by rrrene** [comment]
FYI: Credo `v0.5.1` now implements the Hex API lookup using an Erlang term media type, which means this won't happen in the future. Using Hex's private APIs was a bad idea to begin with.

I also released  `0.4.14`  for all those depending on `~> 0.4.0`, so their builds should heal without the need to update Credo. :+1:

**Comment by sobolevn** [comment]
I have faced some issues with the new release. Here's my configuration:

```elixir
defp deps do
      {:credo, "~> 0.4.14", only: [:dev, :test]},
end
```

Output:

> [11:59:53] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/ecto_autoslug_field ‹master› » mix local.hex
> Found existing archive: /Users/sobolev/.mix/archives/hex-0.12.1.ez.
> Are you sure you want to replace it with "https://repo.hex.pm/installs/1.3.0/hex-0.14.0.ez"? [Yn] y
> * creating /Users/sobolev/.mix/archives/hex-0.14.0
> [12:06:26] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/ecto_autoslug_field ‹master› » MIX_ENV=test mix deps.get && mix credo --strict
> Running dependency resolution
> Dependency resolution completed
>   bunt: 0.1.6
>   credo: 0.4.14
> * Updating credo (Hex package)
>   Checking package (https://repo.hex.pm/tarballs/credo-0.4.14.tar)
>   Fetched package
> 
> ...
> 
> [12:07:08] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/ecto_autoslug_field ‹master*› » mix credo                                                     1 ↵
> Checking 4 source files ...
> ** (EXIT from #PID<0.70.0>) an exception was raised:
>     ** (FunctionClauseError) no function clause matching in Regex.match?/2
>         (elixir) lib/regex.ex:159: Regex.match?(~r/(\.\w+Controller|\.Endpoint|\.Mixfile|\.Repo|\.Router|\.\w+Socket|\w+Test|\.\w+View)$/, nil)
>         (elixir) lib/enum.ex:2511: Enum.do_any?/2
>         lib/credo/check/readability/module_doc.ex:42: Credo.Check.Readability.ModuleDoc.traverse/4
>         (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
>         (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
>         (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
>         (elixir) lib/macro.ex:262: Macro.do_traverse/4
>         (elixir) lib/macro.ex:277: Macro.do_traverse/4
> 
> 12:07:50.528 [error] Task #PID<0.145.0> started from #PID<0.70.0> terminating
> ** (FunctionClauseError) no function clause matching in Regex.match?/2
>     (elixir) lib/regex.ex:159: Regex.match?(~r/(\.\w+Controller|\.Endpoint|\.Mixfile|\.Repo|\.Router|\.\w+Socket|\w+Test|\.\w+View)$/, nil)
>     (elixir) lib/enum.ex:2511: Enum.do_any?/2
>     lib/credo/check/readability/module_doc.ex:42: Credo.Check.Readability.ModuleDoc.traverse/4
>     (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
>     (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
>     (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
>     (elixir) lib/macro.ex:262: Macro.do_traverse/4
>     (elixir) lib/macro.ex:277: Macro.do_traverse/4
> Function: #Function<13.121687013/0 in Credo.Check.Runner.run/2>
>     Args: []
> 
> 12:07:50.529 [error] GenServer Credo.Supervisor terminating
> ** (FunctionClauseError) no function clause matching in Regex.match?/2
>     (elixir) lib/regex.ex:159: Regex.match?(~r/(\.\w+Controller|\.Endpoint|\.Mixfile|\.Repo|\.Router|\.\w+Socket|\w+Test|\.\w+View)$/, nil)
>     (elixir) lib/enum.ex:2511: Enum.do_any?/2
>     lib/credo/check/readability/module_doc.ex:42: Credo.Check.Readability.ModuleDoc.traverse/4
>     (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
>     (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
>     (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
>     (elixir) lib/macro.ex:262: Macro.do_traverse/4
>     (elixir) lib/macro.ex:277: Macro.do_traverse/4
> Last message: {:EXIT, #PID<0.70.0>, {:function_clause, [{Regex, :match?, [~r/(\.\w+Controller|\.Endpoint|\.Mixfile|\.Repo|\.Router|\.\w+Socket|\w+Test|\.\w+View)$/, nil], [file: 'lib/regex.ex', line: 159]}, {Enum, :do_any?, 2, [file: 'lib/enum.ex', line: 2511]}, {Credo.Check.Readability.ModuleDoc, :traverse, 4, [file: 'lib/credo/check/readability/module_doc.ex', line: 42]}, {Macro, :"-do_traverse_args/4-fun-0-", 4, [file: 'lib/macro.ex', line: 296]}, {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3, [file: 'lib/enum.ex', line: 1247]}, {Enum, :"-map_reduce/3-lists^mapfoldl/2-0-", 3, [file: 'lib/enum.ex', line: 1247]}, {Macro, :do_traverse, 4, [file: 'lib/macro.ex', line: 262]}, {Macro, :do_traverse, 4, [file: 'lib/macro.ex', line: 277]}]}}
> State: {:state, {:local, Credo.Supervisor}, :one_for_one, [{:child, #PID<0.127.0>, Credo.Service.SourceFileIssues, {Credo.Service.SourceFileIssues, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileIssues]}, {:child, #PID<0.126.0>, Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {:child, #PID<0.125.0>, Credo.Service.SourceFileCodeOnly, {Credo.Service.SourceFileCodeOnly, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileCodeOnly]}, {:child, #PID<0.124.0>, Credo.Service.SourceFileWithoutStringAndSigils, {Credo.Service.SourceFileWithoutStringAndSigils, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileWithoutStringAndSigils]}], :undefined, 3, 5, [], 0, Supervisor.Default, {:ok, {{:one_for_one, 3, 5}, [{Credo.Service.SourceFileWithoutStringAndSigils, {Credo.Service.SourceFileWithoutStringAndSigils, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileWithoutStringAndSigils]}, {Credo.Service.SourceFileCodeOnly, {Credo.Service.SourceFileCodeOnly, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileCodeOnly]}, {Credo.Service.SourceFileScopes, {Credo.Service.SourceFileScopes, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileScopes]}, {Credo.Service.SourceFileIssues, {Credo.Service.SourceFileIssues, :start_link, []}, :permanent, 5000, :worker, [Credo.Service.SourceFileIssues]}]}}}
> 

Here's the full source code: https://github.com/sobolevn/ecto_autoslug_field

**Comment by rrrene** [comment]
@sobolevn this *seems* unrelated to this issue, but I have an idea. Could you create a separate issue? :+1:

**Comment by sobolevn** [comment]
sure.

**Comment by x-ji** [comment]
Turns out I do have `bunt` and `credo` in `~/.mix/archives` folder for some reason. Removing them seems to have fixed it.

**Comment by rrrene** [comment]
@x-ji I was about to suggest that :grin: Glad you managed to get it to work again! :+1:
