### ISSUE TITLE
Bug: Credo missing hex function after upgrading to latest versions

### ISSUE THREAD

**Issue by Eiji7** [rrrene/credo#213]
### Environment
- Credo version (`mix credo -v`):
  Not work! Here is fragment of `mix deps` command:

``` elixir
* credo 0.4.13 (Hex package) (mix)
  locked at 0.4.13 (credo) 0e9d0479
  ok
```
- Erlang/Elixir version (`elixir -v`):

``` elixir
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10]

Elixir 1.3.4
```
- Operating system:

Funtoo Linux (Gentoo based) - Source based distribution with `emerge` package manager (*.ebuild packages). Output of `uname -a` command:

```
Linux funtoo 4.8.4-gentoo #1 SMP Mon Oct 24 23:50:22 CEST 2016 x86_64 Intel(R) Core(TM) i3 CPU M 370 @ 2.40GHz GenuineIntel GNU/Linux
```
- I add also output of `mix hex.info` command:

``` elixir
Hex:    0.14.0
Elixir: 1.3.4
OTP:    19.1

Built with: Elixir 1.3.4 and OTP 18.3.4.4
```
### What where you trying to do?

Run `credo` task.
### Expected outcome

A results returned by credo task
### Actual outcome

``` elixir
** (UndefinedFunctionError) function Hex.Utils.ensure_registry!/0 is undefined or private
    (hex) Hex.Utils.ensure_registry!()
    lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
    lib/credo/cli.ex:92: Credo.CLI.run/1
    lib/credo/cli.ex:58: Credo.CLI.main/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by rrrene** [comment]
Hi, please upgrade Credo with `mix deps.update credo`. Sorry for the trouble! 😞

**Comment by Eiji7** [comment]
No problem, thx for fast fix and response! 😄
