### ISSUE TITLE
Incorrect consistency report

### ISSUE THREAD

**Issue by joshprice** [rrrene/credo#22]
Credo is looking great! Got this somewhat confusing consistency error though:

```
  Consistency                                                                             
┃ 
┃ [C] ↗ Exception modules should be named consistently. It seems your strategy is to 
┃       prefix them with `Syntax`, but `GraphQL.SyntaxError` does not follow that 
┃       convention."
┃       lib/graphql/error/syntax_error.ex:1:11 (GraphQL.SyntaxError)
```

The only thing I can see that might be wrong is that the module name doesn't match the folder structure.

Code can be found here: https://github.com/joshprice/graphql-elixir/blob/master/lib/graphql/error/syntax_error.ex

**Comment by rrrene** [comment]
That's clearly an error. Will release a bugfix with 0.2.0! :+1:
