### ISSUE TITLE
Restrict to only functions of the same name and zero arity

### ISSUE THREAD

**Issue by josevalim** [rrrene/credo#220]
The checks done by  `Credo.Check.Warning.NameRedeclarationByDef` and friends can only happen today if the function contains airty of zero and from Elixir v1.4, Elixir will also warn, imposing at the language level that functions and variables only exist in two distinct namespaces.

Therefore, I believe it is counter-productive for Credo to warn on cases where arity != 0 since Elixir, guarantees as a language, a conflict will never happen there. My suggestion is to warn only if the arity of the function that clashes is zero. Eventually we should remove this warning altogether (as Elixir won't even compile). :)

**Comment by rrrene** [comment]
+1 for this being removed in the future. I would always prefer to have guarantees/warnings provided by the compiler rather than some optional tool (even if the tool was created by myself).

**Comment by josevalim** [comment]
@rrrene awesome. So checking only for zero-arity can be a good first-step to phase this out. :)

**Comment by sstern6** [comment]
@rrrene @josevalim Looking into this if thats alright.

Will let you know if I run into any issues or have any implementation questions.

Sound good?

**Comment by rrrene** [comment]
Sounds perfect :+1:

**Comment by sstern6** [comment]
Thanks!  Also, digging into the code a little bit, it seems like we should "quit" the consistency check as soon as we realize the arity is greater than 0 based on past conversation threads about the speed of consistency checks(taking a long time).  Which will make execution of this a little bit trickier and might take me a bit longer but I think itll be worth it in the long run.  If you have any objections or feedback please let me know.

Thanks

**Comment by sstern6** [comment]
@josevalim @rrrene I dug into this briefly and might be misunderstanding @josevalim issue, but from my understanding, the current implementation of `Credo.Check.Warning.NameRedeclarationByDef` and similar consistency checks already narrow down the `def_names` it applies the rule to by checking if the arity is in fact zero, found here:https://github.com/rrrene/credo/blob/master/lib/credo/check/warning/name_redeclaration_by_def.ex#L56.

Where `Module.def_names_with_op/2` takes an arity number as the second argument, which is `0` in all `NameRedeclaration` examples found here: https://github.com/rrrene/credo/blob/master/lib/credo/code/module.ex#L92

If I understand correctly, the implementation @josevalim recommended is currently implemented in those consistency checks?

Let me know your thoughts and if I am understanding this correctly.  If I am in fact understanding this correctly we would then need to find a time to remove/deprecate `Credo.Check.Warning.NameRedeclarationByX` rules in a major release. 😄 

Thank you

**Comment by rrrene** [comment]
I had a brief conversation with José and decided to deprecate `NameRedeclarationByX` in the next major release.

Let's keep this issue open to remind ourselves.
