### ISSUE TITLE
defmodule as an attribute crashes credo

### ISSUE THREAD

**Issue by novaugust** [rrrene/credo#228]
### Environment

* Credo version (`mix credo -v`): 0.5.1
* Erlang/Elixir version (`elixir -v`): 1.3.0
* Operating system: osx

### What where you trying to do?
I have a module that I meant to moduledoc, but because I had just typed `defmodule` I went ahead and typed it again, giving me code something like this

```elixir
defmodule MyModule do
  @defmodule """
  MyModule does stuff!
  """
end
```

It took me much longer than I'd like to admit to notice that I substituted `@defmodule` for `@moduledoc`. Anyways, along the way to figuring out what I had done wrong I PR'd #227.

### Expected outcome
Should run without issue

### Actual outcome
Task explodes

The stacktrace for this one-of-a-kind error:
```
11:45:35.817 [error] Task #PID<0.701.0> started from #PID<0.69.0> terminating
** (FunctionClauseError) no function clause matching in Regex.match?/2
    (elixir) lib/regex.ex:159: Regex.match?(~r/(\.\w+Controller|\.Endpoint|\.Mixfile|\.Repo|\.Router|\.\w+Socket|\w+Test|\.\w+View)$/, nil)
    (elixir) lib/enum.ex:2510: Enum.do_any?/2
    lib/credo/check/readability/module_doc.ex:42: Credo.Check.Readability.ModuleDoc.traverse/4
    (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1246: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:262: Macro.do_traverse/4
    (elixir) lib/enum.ex:1246: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:262: Macro.do_traverse/4
Function: #Function<13.132248372/0 in Credo.Check.Runner.run/2>
    Args: []
```

to help you match up line numbers, this is with credo commit 2395862b94628cadf0f5c68975c1440393f425b955f1e70ce1aea267e00187a1

**Comment by rrrene** [comment]
Thx for reporting this! :+1:

We need to catch module attribute declerations in all function headers which try to match `defmacro`, `defmodule`, `def` and `defp` calls.

**Comment by svoynow** [comment]
I can't reproduce this with the HEAD of master.
I *think* this was actually "fixed" by https://github.com/rrrene/credo/commit/39882ce2a6ff37e7ee91b3cfe65a21f604084ba8
What it's doing right now isn't actually totally correct but it doesn't blow up any more.
I think it's still interpreting `@defmodule` as a module declaration, but before it was getting a value of `nil` for the module name which was causing this error.

All that said, figuring out how to distinguish module attributes from uses of keywords is still worth doing, there's probably a series of whack-a-mole bugs related to this that will keep being found until then.

**Comment by rrrene** [comment]
@svoynow You are right. We have to catch all cases where we iterate on `@defops` and add a function head that catches the "module attribute"-case. ([example](https://github.com/rrrene/credo/blob/0f8f9c7311b685fc9620331518c07535a16e0228/lib/credo/check/readability/function_names.ex#L33))

**Comment by NobbZ** [comment]
I will try to get into this.

(that waldo shirted guy at the front)

**Comment by GustavoCaso** [comment]
@rrrene Hi Im getting started with elixir and I will like to contribute as much as possible, I don't know is this issue is suited for beginners, but I would like to help. So if you could point point to the right direction it would be really appreciated.
