### ISSUE TITLE
Missing word in `mix credo categories` help text

### ISSUE THREAD

**Issue by bakkdoor** [rrrene/credo#23]
https://github.com/rrrene/credo/blob/master/lib/credo/cli/output/categories.ex#L28

The above line should read:
```of your code, but how easy it is to digest.```

It's missing the word `how`.

**Comment by rrrene** [comment]
Thx for the bug report, published `v0.2.2` to fix this :grin: :+1:

**Comment by bakkdoor** [comment]
:+1:
