### ISSUE TITLE
Parens and operators check should not warn for unary operators

### ISSUE THREAD

**Issue by josevalim** [rrrene/credo#233]
Credo currently warns on this case:

    TestRepo.all(from p in Post, where: field(p, ^field) > datetime_add(^inserted_at, ^-3, ^"week"))

See the `^-3`.

Assuming the warning is because of precedence, there is no purpose in warning on multiple unary operators because there is never a precedence issue.

**Comment by rrrene** [comment]
:+1: Thx for reporting!

**Comment by svoynow** [comment]
I dug into this a little bit. It looks like it's actually warning here because the "^-<digit(s)> pattern isn't recognized as one of the cases where "-" needs to be interpreted as a unary operator.
I should have a PR for it presently.
