### ISSUE TITLE
MaxLineLength not running when priority set to normal

### ISSUE THREAD

**Issue by kelvinst** [rrrene/credo#241]
### Environment

* Credo version (`mix credo -v`): 0.5.3
* Erlang/Elixir version (`elixir -v`): 1.3.4
* Operating system: Mac OSX Sierra

### What where you trying to do?

I have the following in my `.credo.exs`:

```
# ...
{Credo.Check.Readability.MaxLineLength, priority: :normal},
# ...
```

### Expected outcome

I was expecting `mix  credo` to execute the max line length check, without the need of `--strict`

### Actual outcome

It didn't run the max line length check. 😢

**Comment by rrrene** [comment]
You are absolutly right. Thx for reporting! :+1:

**Comment by rrrene** [comment]
I was not able to reproduce this, could you provide a sample where this breaks?

**Comment by kelvinst** [comment]
Sorry, forgot the version up there, edited my original post.

And about more information, the only thing I did was to generate the config with `mix credo gen.config`, then I changed the line:

```
{Credo.Check.Readability.MaxLineLength, priority: :low, max_length: 80},
```

To:

```
{Credo.Check.Readability.MaxLineLength, priority: :normal},
```

Another important detail is that **my project is an umbrella project**.

**Comment by kelvinst** [comment]
I'll try to attack this problem here. A PR coming soon. :wink:

**Comment by rrrene** [comment]
That would be highly appreciated! :+1:
