### ISSUE TITLE
`Credo.Code.Name.full` crashes when module is referenced as an attribute

### ISSUE THREAD

**Issue by lucasmazza** [rrrene/credo#242]
Running credo when a module is referenced through an attribute fails due a lack of match of `Credo.Code.Name.full`. Here's a small snippet that replicates the error (although the code itself works as expected) and the matching stack trace:

```elixir
# test.exs
defmodule Parent.Nested do
  def hello, do: "Hello, World"
end

defmodule Other do
  @implementation Parent

  def hello do
    IO.puts @implementation.Nested.hello
  end
end

Other.hello
```

```
** (FunctionClauseError) no function clause matching in Credo.Code.Name.full/1
    (credo) lib/credo/code/name.ex:29: Credo.Code.Name.full({:@, [line: 8], [{:implementation, [line: 8], nil}]})
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (credo) lib/credo/code/name.ex:34: Credo.Code.Name.full/1
    (credo) lib/credo/code/module.ex:168: Credo.Code.Module.find_dependent_modules/2
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:262: Macro.do_traverse/4
    (elixir) lib/macro.ex:268: Macro.do_traverse/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
Function: #Function<13.14838968/0 in Credo.Check.Runner.run/2>
    Args: []
'
```

Tested with Elixir 1.3.1 and Credo 0.5.3

**Comment by rrrene** [comment]
Thanks for the bug report! :+1:

I will be giving an Elixir talk and Credo workshop on Tuesday. Maybe I'm brave enough to attempt fixing this in live-coding :grin:

**Comment by JoshSmith** [comment]
@rrrene any chance of `6b51c70` making it into a release on Hex? This issue is technically only fixed on `master`.

Thanks! 💜

**Comment by rrrene** [comment]
@JoshSmith `0.6.0-rc1` contains the fix! Please let me know if it works as expected. :+1:

**Comment by JoshSmith** [comment]
@rrrene just pulled down and tested – works great!
