### ISSUE TITLE
Proposal: DoubleBooleanNegation

### ISSUE THREAD

**Issue by rrrene** [rrrene/credo#245]
`!!some_value` ensures a boolean value as an outcome, but some people don't like this "double negative" because it loses the explicitness of matching the actual value exactly.

A check can warn in these instances that you might want to match on expected "falsy" values explicitly.

**Comment by devonestes** [comment]
I'm a big fan of this proposal! 👍

**Comment by h4cc** [comment]
Other way of writing is using `not`:

```elixir
iex(1)> !!true
true
iex(2)> not not true
true
iex(3)> !!false
false
iex(4)> not not false
false
```

**Comment by NobbZ** [comment]
`!/1` and `not/1` do behave differently:

```
iex(1)> !!nil
false
iex(2)> not not nil
** (ArgumentError) argument error
    :erlang.not(nil)
```

So `not/1` does only work for "real" booleans, while `!/1` does work for `any`.

**Comment by h4cc** [comment]
Good to know, thanks.
So checking for `not !var` should also be considered here.

**Comment by NobbZ** [comment]
Now I do understand the actual proposal behind your former post.

That in fact might be better placed as another check for self-undoing operations, we could then also add `list |> Enum.reverse |> Enum.reverse` and maybe others into the mix? I think it will be hard to recognize automatically that `x |> f |> f == x`... Not sure how to handle that, but if we decide to create another proposal we can discuss it over there.

**Comment by h4cc** [comment]
Started working on this :)

**Comment by rrrene** [comment]
Thx Julius!
