### ISSUE TITLE
Proposal: DuplicateKeywordKeys

### ISSUE THREAD

**Issue by rrrene** [rrrene/credo#246]
Although duplicate keys are explicitly allowed in keyword lists (as opposed to maps), you might want to check twice when using the same key more than once.

A check could warn when the same keyword list contains the same key twice. Since keyword lists are regularly used to capture named parameters for functions, this might prove a useful precaution for many codebases.

**Comment by h4cc** [comment]
Using Keyword Lists as "Sets" does not sound like a good idea.

As an alternative, this could be suggested:
http://elixir-lang.org/docs/stable/elixir/MapSet.html

Older Set Implementations are DEPRECATED:
http://elixir-lang.org/docs/stable/elixir/HashSet.html
http://elixir-lang.org/docs/stable/elixir/Set.html

**Comment by NobbZ** [comment]
Your proposed "alternatives" do only make sure that some value exists in the set, they are not capable of saving an associated value.

**Comment by josevalim** [comment]
I am growing worried about checks that are valid Elixir features, by design, but being restricted. For example, keywords are designed like this on purpose, so we can do things such as:

```
import Enum, only: [find: 2, find: 3]
```

Therefore I am a big :-1: on this check.

**Comment by josevalim** [comment]
The VariableRebinding one :) I can totally see it being useful but I am
also worried about sending conflicting messages to newcomers. If it is bad,
why didn't the language forbid it?

I don't think you should change the check, "growing worried" means more
like "I am keeping an eye on".

Thanks for asking on clarification. It was not nice of me to leave the
"growing worried" in the air.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by rrrene** [comment]
@josevalim No worries, I know you mean no harm 😄 Thanks for the clarification.

I will make a note about "Advanced Usage" checks, which the users will have to opt-in to before using them (this was a good suggestion of yours in another conversation). This way we could have people use a very "safe" subset of checks while they are newcomers, but still provide "controversial" options for those who are familar with the language.
