### ISSUE TITLE
Proposal: VariableRebinding

### ISSUE THREAD

**Issue by rrrene** [rrrene/credo#247]
Although it is possible in Elixir, some people might want to shy away from variable re-binding, since it reminds them too much of matuability in their previous programming language.

A check could warn whenever a variable is re-binded. An optional parameter could allow for function parameters to be rebinded once (since we might want to allow normalization of input parameters while retaining the name).

**Comment by narrowtux** [comment]
I'll try

**Comment by rrrene** [comment]
Thx again! :+1:
