### ISSUE TITLE
Proposal: StringSigils

### ISSUE THREAD

**Issue by rrrene** [rrrene/credo#248]
A check which reports an issue if a regular double-quoted string literal (`"`) contains more than three escaped double quotes:

```elixir
# this is fine:
text = "This is a double quote: \", nice isn't it?"

# this should be written using a sigil like ~S()
text = "<a href=\"http://example.org\" target=\"_blank\">Open in new tab</a>"

# should be written:
~S(<a href="http://example.org" target="_blank">Open in new tab</a>)
```

**Comment by NobbZ** [comment]
Perhaps do the same for single quoted strings and `~c[]`?

**Comment by certainty** [comment]
We will look at this one :D

**Comment by devonestes** [comment]
I'd argue that a single escaped double quote would be worthy of triggering an issue! But I'd certainly be cool with more than 3.
