### ISSUE TITLE
Proposal: AppendSingleItemList

### ISSUE THREAD

**Issue by rrrene** [rrrene/credo#250]
When building up large lists, it is faster to prepend than append. Therefore: It is sometimes best to prepend to the list during iteration and call Enum.reverse/1 at the end, as it is quite fast. 

```elixir
# we want to detect code like this:
list = list_so_far ++ [new_item]

# and suggest something like this:
list = [new_item] ++ list_so_far
...
Enum.reverse(list)
```

**Comment by h4cc** [comment]
The "sometimes" seems to too unspecific: https://pragtob.wordpress.com/2016/06/16/tail-call-optimization-in-elixir-erlang-not-as-efficient-and-important-as-you-probably-think/

**Comment by optikfluffel** [comment]
@PragTob maybe you could help with that one ^^

**Comment by PragTob** [comment]
Heyho, thanks for the mention :)

So, prepend and reverse should be faster imo/afaik (although I'd prepend using `[item | rest]`seems more idiomatic). 

In the blog post, all "serious" suggestions use prepend, the one that uses append is by FAR the slowest. So I'm :+1: on the check, although I'd add that sometimes the order may not matter so one could even omit the `Enum.reverse/1` call.

It's just body recursion that may be faster/more memory efficient than tail-recursion, but that's a whole other topic :)

PS: still need to update that blog post with the new Benchee Interface :)

**Comment by arjan** [comment]
I'm also willing to try to take this on. What should the module be called? Should this go in the "warnings" category? Of should we create a new one specifically focused on performance?

**Comment by josevalim** [comment]
Sorry for being too late but I don't think this should be merged. `++` is harmful when done inside a loop, however, for one case scenarios, it is completely fine. The Erlang Performance Myths even has a section exactly about this, called "Operator ++ is always bad": http://erlang.org/doc/efficiency_guide/myths.html

Unless Credo can detect the ++ operator is being used in an recursive environment, I would avoid such check.

What is Credo policy for false positives and false negatives? Is a check worth adding if it has false positives and false negatives? If so, at what rate?

**Comment by arjan** [comment]
Hmm yeah come to think of this.. It is of course possible to mute the check via `@lint`.
Detecting recursion is undoable, I think. (especially with modules calling each other (GenServers etc)).

**Comment by arjan** [comment]
Maybe we can tailor the check to be very specific, e.g. just looking at `for` blocks and the `Enum` functions, to check if the last call of those blocks use tail appends?
Another relatively easy one is to catch simple tail-call recursion constructs like these:

    def foo(list) do
      foo(list ++ [elem])
    end

**Comment by rrrene** [comment]
@josevalim Just to be sure we are talking about the same thing: 

This check is about building up a list by appending vs prepending:

* `list ++ [single_new_value]` vs 
* `[single_new_value] ++ list` (and then later `Enum.reverse/1` if order matters)

because we thought the strategy is faster for some cases. We are not condemning the use of `++` (although the message for the check is phrased in a confusing way).

Is your comment valid for this case as well?

**Comment by josevalim** [comment]
There are still cases where `list ++ [single_new_value]` is valid, although less common. The question is: do we want to warn on `list ++ [single_new_value]` given there is a chance it is valid?

**Comment by rrrene** [comment]
You are right asking about false positives vs. false negatives. I would err on the side of caution and avoid false positives (at least those which can't be eliminated through improvements in the check).

Since it seems we can't ever be sure with this check, it might be better to move it to the "opt-in" section of the configuration file. This way people who use it have to be aware that it is a YMMV type check.
