### ISSUE TITLE
Improve @moduledoc on lacking checks

### ISSUE THREAD

**Issue by rrrene** [rrrene/credo#257]
Some of the checks are lacking really good explanations.

For example `Credo.Check.Readability.FunctionNames` is a pretty good example for a comprehensive explanation.

`Credo.Check.Readability.TrailingBlankLine` is an example for a not-so-good one.

**Comment by GustavoCaso** [comment]
I"ve been playing with a Elixir for a while, and I have been looking for a project to contribute back, so I thought this project looks cool and want to help. So I would love to start by helping on this task, since is for Starter level.

**Comment by optikfluffel** [comment]
@GustavoCaso any updates on this? :)

**Comment by GustavoCaso** [comment]
@optikfluffel I added some documentation please feel free to comment out.

**Comment by pauloancheta** [comment]
I think this issue can be closed now?

**Comment by rrrene** [comment]
@pauloancheta :+1:
