### ISSUE TITLE
Configure Credo to use global .credo.exs file

### ISSUE THREAD

**Issue by mariusbutuc** [rrrene/credo#263]
Several projects are being added under the same umbrella project, and some of them leverage credo. 

[The docs](https://github.com/rrrene/credo#configuration-via-credoexs) mention that:

> Credo is configured via a file called `.credo.exs`. This file can live in your project's `config/` or root folder, both is fine.

In the sub-apps, how can Credo be configured to use the same, global `.credo.exs` file, say from the root of the umbrella project?
___

Also asked [on the forum](https://elixirforum.com/t/configure-credo-to-use-global-credo-exs-file/2707).

**Comment by mariusbutuc** [comment]
I would imagine a configuration similar to `config_path`, `lockfile` etc in:

```elixir
defmodule Foo.Mixfile do
  use Mix.Project

  def project do
    [
      app: :foo,
      version: "0.1.0",
      build_path: "../../_build",
      config_path: "../../config/config.exs",
      deps_path: "../../deps",
      lockfile: "../../mix.lock",
      # …
    ]
  end
end
```

**Comment by rrrene** [comment]
Have you tried simply putting a `.credo.exs` file in the root of the umbrella project like the README suggests?

**Comment by mariusbutuc** [comment]
> your project's […] root folder 

…that meant the root of the umbrella project. This works, thanks @rrrene!

**Comment by rrrene** [comment]
To clarify: Credo traverses your tree back up until your home dir. At each step of the way it looks for `./.credo.exs` as well as `./config/.credo.exs`. It then merges those configs recursively, with those "nearer" to your `cwd` taking precedence.

**Comment by rrrene** [comment]
This is why you can put a config file in your umbrella project's root dir. Or in your umbrella apps dir. Or both. ;-)
