### ISSUE TITLE
`list` command exits with a 0 when there are errors

### ISSUE THREAD

**Issue by sgtpepper43** [rrrene/credo#265]
### Precheck

* For proposing a new feature, be sure to name your issue "Proposal: ..."
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 0.5.3
* Erlang/Elixir version (`elixir -v`): Erlang/OTP 19, Elixir 1.3.4
* Operating system: Ubuntu

### What where you trying to do?

Run `mix credo list` in CI

### Expected outcome

Exits with a non-zero code and breaks the build

### Actual outcome

Exits with 0

**Comment by rrrene** [comment]
That moment when you investigate an error and find things like this: https://github.com/rrrene/credo/blob/8b0423e1aee73029ea501271f3bf390d270dccae/lib/credo/cli/command/list.ex#L22 :wink:

Thx for reporting! :+1:
