### ISSUE TITLE
Spaces around operators check: Pin on a negative number

### ISSUE THREAD

**Issue by shdblowers** [rrrene/credo#271]
### Environment

* Credo version (`mix credo -v`): 0.5.3
* Erlang/Elixir version (`elixir -v`): 1.3.4
* Operating system: Linux

### Issue

`^-1.0` will raise an issue, whereas `^1` will not.

Many examples in ecto:
[Example](https://ebertapp.io/github/elixir-ecto/ecto/reviews/109)

**Comment by rrrene** [comment]
:+1: Thx for reporting!

**Comment by optikfluffel** [comment]
I can't reproduce this behaviour using `HEAD`. I also run `mix credo` on Ecto using current `master` and the "spaces around operators" warnings didn't show up. Got it fixed already?

**Comment by rrrene** [comment]
Fixed. Added a test case. Thx for reporting! :+1:

**Comment by shdblowers** [comment]
thanks for writing credo :smile:
