### ISSUE TITLE
UndefinedFunctionError: undefined function String.to_charlist/1

### ISSUE THREAD

**Issue by sobolevn** [rrrene/credo#272]
### Precheck

- [x] For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 
> 0.5.3
* Erlang/Elixir version (`elixir -v`): 
> Elixir 1.2.6
> Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:32:32] [async-threads:10] [hipe] [kernel-poll:false]
* Operating system:
> Ubuntu 12.04.5 LTS on Travis CI

### What were you trying to do?

I am trying to run `mix credo --strict`

### Expected outcome

Listed issues or nothing.

### Actual outcome

> ** (UndefinedFunctionError) undefined function String.to_charlist/1
>     (elixir) String.to_charlist("https://hex.pm/api/packages/credo")
>     lib/credo/check_for_updates.ex:68: Credo.CheckForUpdates.fetch/1
>     lib/credo/check_for_updates.ex:59: Credo.CheckForUpdates.fetch_all_hex_versions/1
>     lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
>     lib/credo/cli.ex:92: Credo.CLI.run/1
>     lib/credo/cli.ex:58: Credo.CLI.main/1
>     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

It breaks only for `elixir->1.2` and works for `elixir->1.3`. Here's the link to the Travis job: https://travis-ci.org/samueljseay/recaptcha/jobs/182887175

Related to the https://github.com/samueljseay/recaptcha/pull/15

**Comment by rrrene** [comment]
Ouch ... thx for reporting!

**Comment by sobolevn** [comment]
Ok, if that's an entry-level issue and you want some help, I am on it.
