### ISSUE TITLE
Credo.Check.Readability.StringSigils.base_priority/0 is undefined

### ISSUE THREAD

**Issue by mkrogemann** [rrrene/credo#277]
### Environment

* Credo version (`mix credo -v`): 0.5.3
* Erlang/Elixir version (`elixir -v`): Elixir 1.4.0-rc.1 (16a14c1f6)
* Operating system: macOS 10.12.1 (16B2555)

### What were you trying to do?
Add .credo.exs to umbrella app config folder, using the provided full configuration example

### Expected outcome
successful execution of `mix credo --strict`

### Actual outcome
** (UndefinedFunctionError) function Credo.Check.Readability.StringSigils.base_priority/0 is undefined (module Credo.Check.Readability.StringSigils is not available)
    Credo.Check.Readability.StringSigils.base_priority()
    lib/credo/check/runner.ex:65: anonymous fn/2 in Credo.Check.Runner.exclude_low_priority_checks/2
    (elixir) lib/enum.ex:1833: anonymous fn/3 in Enum.reject/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1833: Enum.reject/2
    lib/credo/check/runner.ex:63: Credo.Check.Runner.exclude_low_priority_checks/2
    lib/credo/check/runner.ex:10: Credo.Check.Runner.run/2
    (stdlib) timer.erl:166: :timer.tc/1

So it looks like there is a module missing that the current config expects. Simple fix would be to remove that one line from the config for the time being.

**Comment by rrrene** [comment]
When installing Credo `0.5.3` and running `mix credo gen.config` I do not get those checks in the config.

Maybe you are using the bleeding-edge version of the config with a stable version of Credo?

**Comment by rrrene** [comment]
I just realized that the README wasn't very helpful in suggesting jus that (using the bleeding-edge version of the config). I updated the README.

Thx for bringing this up :+1:

**Comment by mkrogemann** [comment]
Yes, you are right. It turns out to be no bug but README improvement makes sense. Thx!
