### ISSUE TITLE
"readability" and "refactoring" tags are the same when using `--oneline`

### ISSUE THREAD

**Issue by rranelli** [rrrene/credo#29]
When I run `mix credo --one-line` I get both `readability` checks and `refactoring` checks tagged with `[R]`.

I'm currently writing a script to extract credo's output to format comments for Gitlab merge requests.
It would be great if I was able to differentiate between these categories while using the `--one-line` option. This would make my scripts much simpler.

I would suggest changing the `refactoring` tags to `[F]`. If you're okay with the change, I would gladly send a PR.

Also, thanks for the great project :+1:

**Comment by rrrene** [comment]
I would accept the PR you describe. It's clearly better than what we have now! :+1:

**Comment by rranelli** [comment]
Alright, I will work on it as soon as I get some extra time. :+1:
