### ISSUE TITLE
Bug with {check, false} in 0.6.0-rc1

### ISSUE THREAD

**Issue by bitwalker** [rrrene/credo#295]
### Environment

* Credo version (`mix credo -v`): 0.6.0-rc1
* Erlang/Elixir version (`elixir -v`): 1.4.0/19.1
* Operating system: OSX 10.11.6

### What were you trying to do?

I generated a default config and set a few checks to false, e.g. `{Credo.Check.Refactor.PipeChainStart, false}`. Running `mix credo --strict` (omitting the --strict flag makes no difference though), I get an exception:

```
** (FunctionClauseError) no function clause matching in Access.fetch/2
    (elixir) lib/access.ex:239: Access.fetch(false, :priority)
    (elixir) lib/access.ex:269: Access.get/3
    lib/credo/check/runner.ex:70: anonymous fn/2 in Credo.Check.Runner.exclude_low_priority_checks/2
    (elixir) lib/enum.ex:1833: anonymous fn/3 in Enum.reject/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1833: Enum.reject/2
    lib/credo/check/runner.ex:67: Credo.Check.Runner.exclude_low_priority_checks/2
    lib/credo/check/runner.ex:40: Credo.Check.Runner.prepare_config/2
```

I noticed that the problem is [here](https://github.com/rrrene/credo/blob/master/lib/credo/check/runner.ex#L70). The code incorrectly assumes that opts is always a key/value collection, adding a clause for false would probably be the best solution. I'll open a PR for that separately :)

**Comment by rrrene** [comment]
@bitwalker Thanks for the PRs Paul! It is great appreciated :)

**Comment by bitwalker** [comment]
No problem :) Glad I could contribute back!
