### ISSUE TITLE
Spaces around operator check: numerous captured functions

### ISSUE THREAD

**Issue by anup-2s** [rrrene/credo#298]
### Environment
* Credo version: 0.5.3
* Erlang/Elixir version: 1.3.4

Numerous captured functions (more than half the number of operators in the function) trigger the `There are no spaces around operators most of the time, but here there are.` consistency issue.
Can be demonstrated with the file:
```elixir
&round/2
&round/2
&round/2
c = 1 * 2
```

### Expected outcome
Spaces around operators should be considered normal.

### Actual outcome
No spaces around operators is considered normal.

**Comment by rrrene** [comment]
Ouch. Will have a look :+1:

**Comment by rrrene** [comment]
I can't reproduce this with the current version. 

I flagged this as solved, but please re-open if this has not been fixed for your use-case!

**Comment by lauraannwilliams** [comment]
I'm getting this behaviour with 0.7.3

Specifically

```
  field :slug, :string, description: @descs.slug <> " To force slug regeneration, set to an empty string."
 ```

triggers the warning on the <> operator if there are any function captures (like ```resolve &HubResolver.update/2```)  in the file.  

I can open a new ticket if preferred :)

**Comment by rrrene** [comment]
@lauraannwilliams A new issue with a sample file would be perfect! :+1:
