### ISSUE TITLE
file argument check fails when configuration contains exclusion for a different file

### ISSUE THREAD

**Issue by tsubery** [rrrene/credo#300]
### Environment
credo version 0.6.0-rc1
Elixir 1.4

.credo.exs contains exclusion: ["foo.ex"]
### What were you trying to do?
mix credo bar.ex

### Expected outcome
The file bar.ex being checked.

### Actual outcome
Nothing is checked and I see "No files found!" message.

More information:
The argument "bar.ex" ends up as "dir" parameter [here](https://github.com/rrrene/credo/blob/master/lib/credo/config.ex#L249) even though it is not a directory.
It ends up being returned as it is [here](https://github.com/rrrene/credo/blob/master/lib/credo/config.ex#L263) Causing the given parameter to be both included and excluded.

I can submit a PR for it but thought I might ask first. Seems to me this whole area of the code need to be rewritten. For example, the conditional whether the param is a directory is needlessly repeated for every pattern. It might be possible to simplify it by checking whether the argument is a directory and using ```File.cd``` to do everything in that directory instead of joining paths.

**Comment by rrrene** [comment]
Thanks for reporting this. You are right, this is easily reproducable.

There are three factors to consider when trying to work out which source files to load:

- current working directory
- given directory or file or glob as command line argument
- `included` and `excluded` keys from `.credo.exs`, which might contain directories, files or globs

If you want to give this a try, be sure to keep these in mind :+1:

**Comment by rrrene** [comment]
> It might be possible to simplify it by checking whether the argument is a directory and using File.cd to do everything in that directory instead of joining paths.

Oh and please don't do that. :grin: :+1:
