### ISSUE TITLE
ABC size for strings with interpolation in a function

### ISSUE THREAD

**Issue by SekiT** [rrrene/credo#319]
Elixir version: 1.4.1
credo at current master

`ABCSize.abc_size_for/1` counts 2 for a string with interpolation in a function:
```ex
iex(1)> code = """
...(1)> def fun(arg) do
...(1)>   "str with \#{arg}"
...(1)> end
...(1)> """
"def fun(arg) do\n  \"str with \#{arg}\"\nend\n"
iex(2)> {:ok, ast} = Credo.Code.ast(code); Credo.Check.Refactor.ABCSize.abc_size_for(ast)
2.0
```
while it doesn't count for a string with interpolation outside a function:
```ex
iex(1)> code = """
...(1)> "string with \#{arg}"
...(1)> """
"\"string with \#{arg}\"\n"
iex(2)> {:ok, ast} = Credo.Code.ast(code); Credo.Check.Refactor.ABCSize.abc_size_for(ast)
0
```

I think `0` for both case is correct.

**Comment by rrrene** [comment]
Ouch. Thanks for the report! :+1:

We are probably deprecating ABC-Size for 1.0 anyway, but this is a bug nonetheless!
