### ISSUE TITLE
What exactly is MultiAliasImportRequireUse checking for?

### ISSUE THREAD

**Issue by sgtpepper43** [rrrene/credo#320]
It seems like `MultiAliasImportRequireUse` is _very_ aggressive. In some cases the only way to satisfy it is to put _every_ import on the same line.

### What were you trying to do?

This is what we've _been_ doing
```elixir
import Ecto
import Ecto.Query
import Foo.{ErrorHelpers, Gettext}
```

This is the most I would want to combine them
```elixir
import Ecto, Ecto.Query
import Foo.{ErrorHelpers, Gettext}
```

And this is the only way to get rid of the warning
```elixir
import Ecto, Ecto.Query, Foo.{ErrorHelpers, Gettext}
```

### Expected outcome

When I saw this check, I thought it would just warn you to consolidate any alias/imports/use statements that were on the same module, and at the same depth, using curly braces.

### Actual outcome

I don't know if that's how this check is supposed to work or not. Seems a bit excessive.

Whatever the case may be, I think that there should be an option to force the check one way or the other. It would've been much easier to figure out what was going on if I could just tell it that I want to use the multi-alias syntax everywhere and then correct everyone that it's not doing it.

And now it's complaining about this function (yes it's the whole function)
```elixir
  def router do
    quote do
      use Phoenix.Router
    end
  end
```
Where it apparently wants me to do this
```elixir
  use Phoenix.{Router}
```

**Comment by rrrene** [comment]
This seems like a bug, the check should behave like you thought at first. Thanks for the (very good) bug report! :+1:

**Comment by mneumark** [comment]
To expand further on this, since this error clearly checks for something that is contextual to the whole code base, when running `mix credo explain <location>:<line_number>` it does not find any issues because now you are only checking in one place and the error does not exist in a vacuum.

**Comment by rrrene** [comment]
@mneumark Yes. This unfortunate behaviour of Credo will have to be fixed in the future. See #253 :+1:

**Comment by jeremyowensboggs** [comment]
I'm seeing an issue where I use aliasing
```
alias ModuleName.Api.Rest, as: RestApi
alias ModuleName.Api.Types, as ApiTypes
```
and now, everywhere I have
```
alias ModuleName.ModX.{Mod1, Mod2}
```
It's being flagged because:
```
Most of the time you are using the multiple single line
┃       alias/require/import/use directives but here you are using the
┃       multi-alias/require/import/use syntax
```

**Comment by rrrene** [comment]
@sgtpepper43 @jeremyowensboggs can you please test against `master`? 

You can do so by using this deps entry:

```elixir
{:credo, github: "rrrene/credo"}
```

**Comment by jeremyowensboggs** [comment]
It is still flagging my web.ex file
```
...
┃ [C] ↗ Most of the time you are using the multi-alias/require/import/use
┃       syntax, but here you are using multiple single directives
┃       apps/tractor_beam/web/web.ex:59 (TractorBeam.Web.channel)
┃ [C] ↗ Most of the time you are using the multi-alias/require/import/use
┃       syntax, but here you are using multiple single directives
┃       apps/tractor_beam/web/web.ex:58 (TractorBeam.Web.channel)
┃ [C] ↗ Most of the time you are using the multi-alias/require/import/use
┃       syntax, but here you are using multiple single directives
┃       apps/tractor_beam/web/web.ex:45 (TractorBeam.Web.view)
...
```
and here is the web.ex file
```
defmodule TractorBeam.Web do
  @moduledoc """
  A module that keeps using definitions for controllers,
  views and so on.

  This can be used in your application as:

      use TractorBeam.Web, :controller
      use TractorBeam.Web, :view

  The definitions below will be executed for every view,
  controller, etc, so keep them short and clean, focused
  on imports, uses and aliases.

  Do NOT define functions inside the quoted expressions
  below.
  """

  def model do
    quote do
      # Define common model functionality
    end
  end

  def controller do
    quote do
      use Phoenix.Controller

      import TractorBeam.Router.Helpers
      import TractorBeam.Gettext

    end
  end

  def view do
    quote do
      use Phoenix.View, root: "web/templates"

      # Import convenience functions from controllers
      import Phoenix.Controller, only: [get_csrf_token: 0, get_flash: 2, view_module: 1]

      # Use all HTML functionality (forms, tags, etc)
      use Phoenix.HTML

      import TractorBeam.Router.Helpers
      import TractorBeam.{ErrorHelpers, Gettext, Session}
    end
  end

  def router do
    quote do
      use Phoenix.Router
    end
  end

  def channel do
    quote do
      use Phoenix.Channel
      import TractorBeam.Gettext
    end
  end

  @doc """
  When used, dispatch to the appropriate controller/view/etc.
  """
  defmacro __using__(which) when is_atom(which) do
    apply(__MODULE__, which, [])
  end
end

```

I notice it is not flagging all of the imports, but just the ones starting at line 45.

**Comment by rrrene** [comment]
I decided to disable the `MultiAliasImportRequireUse` check by default. It is not up to speed (yet) and in need of a big refactoring/re-implementation.

Everybody, thx for your reports! Community contribution is what makes this project breathe :+1:
