### ISSUE TITLE
Pipeline raw value check fails on for loops

### ISSUE THREAD

**Issue by CaptChrisD** [rrrene/credo#323]
### Environment

* Credo version (`mix credo -v`): "0.5.3", "0c405b36e7651245a8ed63c09e2d52c2e2b89b6d02b1570c4d611e0fcbecf4a2"
* Erlang/Elixir version (`elixir -v`): 1.3.4
* Operating system: OSX

### What were you trying to do?

```elixir
for i <- 1..4 do
  i
end
|> Enum.map(fn(i) -> i + 2 end)
```
or (out of desperation)
```elixir
(i <- 1..4)
|> for do
  i
end
|> Enum.map(fn(i) -> i + 2 end)
```
### Expected outcome

No warning

### Actual outcome

Warning of pipeline starting without raw value

**Comment by rrrene** [comment]
Thanks for reporting this! :+1:
