### ISSUE TITLE
Proposal: Warn when missing spaces after commas (lists, params, etc)

### ISSUE THREAD

**Issue by christiannelson** [rrrene/credo#324]
### Environment

* Credo version (`mix credo -v`): 0.6.1
* Erlang/Elixir version (`elixir -v`): 1.4.1
* Operating system: macOS 10.2.4

### What were you trying to do?

Add a new check that will report when spaces are missing after parameters in a variety of contexts.

Example:

```
defmodule Module do
  alias Project.{A,B} # WARN: missing space after comma

  @attr [1,2,3,4,5] # WARN:  missing space after comma

  def a_func(first_name,last_name) do # WARN: missing space after comma
    Map.merge(%{a: first_name,b: last_name},%{a: 3, d: 4}) # WARN: missing space after comma
  end
end
```

FWIW, I currently can't think of any exceptions where a commas separates values or params that the check would not trigger the code style check.

**Comment by rrrene** [comment]
Yep, this seems like a good idea. Not sure if this *has* to be a consistency check. WDYT?

**Comment by christiannelson** [comment]
> Not sure if this has to be a consistency check. WDYT?

Sorry, I'm not exactly sure what you mean with the question.

I would describe this check as something teams might only care about if they're detailed oriented, or pedantic about consistency. Perhaps it's disabled at first and folks can opt-in?

I hope to take a shot at implementing this -- and possibly the other proposal I sent -- one of these days when I have some free time. TBH, it might be a while though. If you (or anyone else) feels the inspiration to do it, I certainly won't be upset about it. :)

**Comment by rrrene** [comment]
> Sorry, I'm not exactly sure what you mean with the question.

In Credo, there is a concept called "concistency checks", which are not checking a specific behaviour (use tabs for indentation) but rather look at your project and examine it for consistency ("you seem to be using tabs for the majority of your code, but in these 5 lines use spaces").

What I wanted to say is that your proposal *might* fit that scheme, but I'm not sure.

**Comment by christiannelson** [comment]
@rrrene Oh yeah, I totally know what you mean. I'll think about it some more, I could see it going either way.

Do consistency checks work across files, or do they look for consistency within the current file only?

**Comment by rrrene** [comment]
They work on all files. But - after some introspection - I think this check might just be a regular one, which is also easier to implement ;-)
