### ISSUE TITLE
Proposal: Alias-Check Occurrence Threshold

### ISSUE THREAD

**Issue by philippneugebauer** [rrrene/credo#327]
I would like to have an option to criticize the alias problem only when it is used more than a specific limit. I don't see the point of using an alias when I just use another module once in a module

**Comment by rrrene** [comment]
:+1 Thx for suggesting this!

**Comment by rrrene** [comment]
@philippneugebauer This was implemented and is part of the current release candidates for Credo `v0.8.0` and will be part of that minor release. 

Thx for your suggestion! :+1:

**Comment by philippneugebauer** [comment]
I wanted to implement this, but I couldn't find any statement in the changelog or documentation
