### ISSUE TITLE
Proposal: Update README to point to a resource that has more info on what exactly mix.exs is for a beginner to Elixir

### ISSUE THREAD

**Issue by boddhisattva** [rrrene/credo#328]
### Environment

* Credo version (`mix credo -v`): 0.6.1
* Erlang/Elixir version (`elixir -v`): 1.4.0
* Operating system: Mac OS X El Capitan 10.11.5

### What were you trying to do?

**In short** - Setup credo as a beginner to Elixir

#### Some more context

As a beginner to Elixir, I wasn't quite sure what exactly the `mix.exs` file was and couldn't immediately figure out that it was a file that is generally generated by the `mix` build tool. I knew for sure that I wanted to set up `credo`(have previous experience of setting up similar tools for `ruby` in the past) as soon as I was getting started with some small exercises to get a better understanding of Elixir but I wasn't immediately able to leverage the insights I could get from `credo` as I didn't know what `mix.exs` was in the first place.

### Expected outcome

To be able to setup credo as a beginner more easily

### Actual outcome

Wasn't able to setup credo as early as I wanted to leverage it's insights

### Proposed Change

Update the *Installation* section of the current README file from -

#### From

Add as a dependency in your mix.exs file:

```elixir
defp deps do
  [
    {:credo, "~> 0.5", only: [:dev, :test]}
  ]
end
```

#### To

Add the below as a dependency in your mix.exs file. In case you're new to Elixir and don't know what the `mix.exs` file is, you can read more about the same [here](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html).

```elixir
defp deps do
  [
    {:credo, "~> 0.5", only: [:dev, :test]}
  ]
end
```

Please let me know your thoughts on the above proposal and I could accordingly work on a PR for the same.

Thank you.

**Comment by rrrene** [comment]
@boddhisattva Thx for reporting this! :+1:

**Comment by boddhisattva** [comment]
@rrrene Glad to know you found it useful :) I was planning to submit a PR to fix this myself but looks like you've already done that :)

**Comment by NobbZ** [comment]
Ok credo has some info in its read me, other tools don't, will you issue there as well? I think that a library maintainer has to assume some level of knowledge about the language and its tool chain or he could start copying the official documentation. 

Everyone who has worked through the official tutorial should know what mix.exs is and how to create an empty project.

**Comment by boddhisattva** [comment]
This was just a proposal of something that is good to have in the README for someone who may not know about `mix.exs`. 

My intention was to only make it more easier for any other beginner who may not know about this file but would want to get started with using credo at the earliest. 

I think it should be fine as long René understood where I was coming from. About issuing it in other tools, as far as I see it, this is only a discussion on how to make a library more easily usable to beginners and nothing else and if the library maintainer can relate to this then it's all good right?
