### ISSUE TITLE
Issues are presented in apparently random order

### ISSUE THREAD

**Issue by scouten** [rrrene/credo#339]
### Environment

* Credo version (`mix credo -v`): 0.6.1
* Erlang/Elixir version (`elixir -v`): 1.4.1
* Operating system: MacOS 10.12.3

### What were you trying to do?

Run `mix credo --all` on a project with a few dozen issues left to address.

### Expected outcome

Issues (within any given class "Refactoring opportunities", etc.) are sorted by file path and then line number.

### Actual outcome

Within any given class, issues appear to be grouped by file path, but the file paths themselves are in an apparently random order. Within any given file, issues appear in a somewhat random order. To the extent that there is (sometimes) a sequence, it appears to be sorted by _descending_ line number.

**Comment by rrrene** [comment]
@scouten The issues are sorted by "priority". To address your concern, I added the filename and line number to the list of sort criteria.
