### ISSUE TITLE
Problem: suggested alias is not possible

### ISSUE THREAD

**Issue by c-rack** [rrrene/credo#35]
In [exzmq](https://github.com/zeromq/exzmq), we have the following modules: `Exzmq.Socket` and `Exzmq.Tcp.Socket`. Now the following code still recommends to alias `Tcp.Socket`, which would conflict with the first `Exzmq.Socket` alias:

```elixir
defmodule Test do
  alias Exzmq.Socket
  alias Exzmq.Tcp

  def just_an_example do
    Socket.test1  # Exzmq.Socket.test
    Tcp.Socket.test2 # Exzmq.Tcp.Socket.test – how can this be further aliased?
  end

end
```
We do not want to alias as `TcpSocket`.

**Comment by rrrene** [comment]
Thanks for the bug report. Will look into detecting cases like this! :+1:

**Comment by rrrene** [comment]
Finally got around to implementing this. Thanks again for reporting! :+1:
