### ISSUE TITLE
Credo.Check.Readability.NoParenthesesWhenZeroArity.base_priority/0 is undefined

### ISSUE THREAD

**Issue by rawkode** [rrrene/credo#351]
### Environment

I've tried `rm -rf ~/.mix ~/.hex deps _build` and it doesn't help

* Credo version (`mix credo -v`): 0.7.1
* Erlang/Elixir version (`elixir -v`): 1.4.1
* Operating system: Linux

### What were you trying to do?
`mix credo`

### Expected outcome

Credo stuff

### Actual outcome

```
@lint attributes will be deprecated in the Credo v0.8 because they trigger
compiler warnings on Elixir v1.4.

Please consider reporting the cases where you needed @lint attributes
to help us devise a new solution: https://github.com/rrrene/credo/issues/new

** (UndefinedFunctionError) function Credo.Check.Readability.NoParenthesesWhenZeroArity.base_priority/0 is undefined (module Credo.Check.Readability.NoParenthesesWhenZeroArity is not available)
    Credo.Check.Readability.NoParenthesesWhenZeroArity.base_priority()
    lib/credo/check/runner.ex:85: anonymous fn/2 in Credo.Check.Runner.exclude_low_priority_checks/2
    (elixir) lib/enum.ex:1833: anonymous fn/3 in Enum.reject/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1833: Enum.reject/2
    lib/credo/check/runner.ex:81: Credo.Check.Runner.exclude_low_priority_checks/2
    lib/credo/check/runner.ex:44: Credo.Check.Runner.prepare_config/2
    lib/credo/cli/command/suggest.ex:19: Credo.CLI.Command.Suggest.run/1
```

**Comment by nikolauska** [comment]
To fix that error you need to rename `NoParenthesesWhenZeroArity` to `ParenthesesOnZeroArityDefs` in .credo.exs. This is due to module rename in version 0.7.

**Comment by rawkode** [comment]
I don't have a `.credo.exs`

**Comment by rrrene** [comment]
@rawkode Niko is correct: There seems to be a `credo.exs` mentioning the old name somewhere. 

Please consider that Credo looks for a `.credo.exs` file in the current directory, each parent directory up to the root directory and in `config/` sub-directories at each level.

**Comment by jacknoble** [comment]
Would it be a good idea to add better error messages for mistakes in `.credo.exs` -- something to validate that all the checks exist? There error message could include the path to the config file.

**Comment by rrrene** [comment]
@jacknoble Absolutely. Please create an issue for this.
