### ISSUE TITLE
excluded list not working as expected

### ISSUE THREAD

**Issue by nathanhornby** [rrrene/credo#359]
### Precheck

Can't seem to find anything on this issue, I assume it must be user error but I can't see where…

Here is my config:

```elixir
%{
  configs: [
    %{
      files: %{
        included: ["lib/"],
        excluded: [~r"/_build/", ~r"/deps/", ~r"/doc/"]
      },
      checks: [
        {Credo.Check.Readability.MaxLineLength, priority: :low, max_length: 80, ignore_string: true, ignore_specs: true}
      ]
    }
  ]
}
```

But on running `mix credo` all files are checked, included those in the 'excluded' directories.

### Environment

* Credo version (`mix credo -v`): 0.7
* Erlang/Elixir version (`elixir -v`): 1.4
* Operating system: OSX 10.11.6

### What were you trying to do?

Exclude directories.

### Expected outcome

Directories are excluded from the code analysis.

### Actual outcome

The directories are included in the code analysis.

**Comment by rrrene** [comment]
Thx for the bug report! :+1: 

Your config is missing the required "name" field. I created an issue for that.

**Comment by rrrene** [comment]
@nathanhornby To elaborate:

Just put `name: "default",` above the `files: %{` line and you're fine!

**Comment by nathanhornby** [comment]
@rrrene

Ah thank you! Nice and simple. I must have misunderstood this line from the packages own .credo.exs:

> If no config name is given "default" is used.

I assumed this to mean it was an optional attribute.

**Comment by rrrene** [comment]
@nathanhornby I thought about making it take the only config present (if there is only one), but then I remembered that I like Elixir's motto of "explicitness over implicit behaviour" very much and decided against it. So you're not crazy 😆  👍
