### ISSUE TITLE
Credo does not respect strict mode in config file

### ISSUE THREAD

**Issue by szlend** [rrrene/credo#366]
### Environment

* Credo version: 0.7.3
* Erlang/Elixir version: Erlang/OTP 19 [erts-8.2] / Elixir 1.4.2
* Operating system: OS X Sierra

### What were you trying to do?

I generated the credo config file, set `strict: true` and ran `mix credo`.

### Expected outcome

It should show low priority issues like MaxLineLength.

### Actual outcome

Strict mode is not respected. It works only if I pass the `--strict` flag explicitly.

You can reproduce the issue by cloning https://github.com/szlend/credo_test

**Comment by rrrene** [comment]
Ouch, thanks for the bug report :+1:

**Comment by kaiyote** [comment]
I actually just ran into this same issue...., had a go at fixing it too.
