### ISSUE TITLE
Using Credo For Pull Request Checks

### ISSUE THREAD

**Issue by odannyc** [rrrene/credo#372]
Is there a way to use credo to check when a pull request is opened in a project within Github?
Kind of like `travis-ci`.

**Comment by devonestes** [comment]
It's possible to add credo to your CI (depending on your CI provider). I know, for example, that you can set custom checks in Travis, and Credo will exit with the appropriate exit code (meaning it will exit with 0 if there are no issues).

Here's an example of someone's travis config to do just that: https://github.com/cpjk/canary/blob/9bfee2ab9990773573e108caaeeeb332ee4b0c27/.travis.yml

**Comment by rrrene** [comment]
@odannyc Thanks for your question!

To add to @devonestes' answer: If you are looking for a dedicated service, there is https://ebertapp.io/ by Plataformatec, which uses Credo for Elixir.

I am closing this for now, but please do not hesitate to ask additional questions if our answers were not sufficient! :+1:
