### ISSUE TITLE
"Space Missing after comma" in interpolation 

### ISSUE THREAD

**Issue by leifg** [rrrene/credo#380]
### Environment

* Credo version (`mix credo -v`): master
* Erlang/Elixir version (`elixir -v`): 1.4.4
* Operating system: Mac OS

### What were you trying to do?

Having the construct `"#{Enum.join(list, ",")}"`

### Expected outcome

No warning

### Actual outcome

Warning is `Space missing after comma`

This might be related to #357 and #373 that's why I retested it in master. might be another edge case

**Comment by rrrene** [comment]
Yepp, this seems like another edge case. Thx for reporting! :+1:

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by leifg** [comment]
Tested it. Issue is resolved.
