### ISSUE TITLE
Proposal: warn on raise inside rescue

### ISSUE THREAD

**Issue by arjan** [rrrene/credo#381]
An error that I see happening many times is people doing `raise` inside a caught exception, because they are unaware of the `reraise` function:

```elixir
try do
  # .. some stuff
rescue
  e ->
    Logger.warn("Something bad happened!")
    raise e
end
```

Pattern like this swallows stack trace of where the original exception occurred and replaces it with the stacktrace of the new `raise`, leaving you in the dark. Would it be an idea to emit a warning when a pattern like this is discovered?

**Comment by rrrene** [comment]
@arjan Sounds good to me! :+1:

**Comment by arjan** [comment]
Awesome, thanks @little-bobby-tables :-D
