### ISSUE TITLE
Compilation warning on Elixir 1.4.4

### ISSUE THREAD

**Issue by ggpasqualino** [rrrene/credo#383]
### Environment

* Credo version (`mix credo -v`):
0.7.4
* Erlang/Elixir version (`elixir -v`):
Erlang/OTP 19
Elixir 1.4.4
* Operating system:
OSX 10.11.6

### What were you trying to do?
Compile the dependencies of my project `mix deps.compile`

### Expected outcome
Compile without warnings

### Actual outcome
Compile with lots of warnings, all in the same line, like the following
`warning: this clause cannot match because a previous clause at line 31 always matches
  lib/credo/code/sigils.ex:31`

**Comment by rrrene** [comment]
@ggpasqualino I got this as well recently (while working on Credo itself), but can't reproduce it after cleaning my build ...

Can you remove the `_build` and `deps` directories and try again?

**Comment by ggpasqualino** [comment]
Okay, I tried it and I still get the warnings

**Comment by leifg** [comment]
I get this error as well. Looking into it, it seems like there are a lot of functions created redundantly.

I inspected the contents of [@removable_sigils](https://github.com/rrrene/credo/blob/master/lib/credo/code/sigils.ex#L13). here an excerpt:

```
{"~g'", "'"}
{"~g'", "'"}
{"~G'", "'"}
{"~G'", "'"}
{"~h'", "'"}
{"~h'", "'"}
{"~H'", "'"}
{"~H'", "'"}
```

seems to be twice as many as there should be.

So for every of these tuples a new function will be created.

I suppose a simple `Enum.uniq` will be fine. I submitted a [PR](https://github.com/rrrene/credo/issues/384) for that

**Comment by rrrene** [comment]
@ggpasqualino @leifg I released `v0.8.0-rc7` (which is hopefully the last RC for 0.8.0 ^_^).

Could you test it and give feedback if the problem was fixed/if you find any other issues?

**Comment by leifg** [comment]
Checked. The issue was solved.

**Comment by ggpasqualino** [comment]
Thanks! LGTM :)
