### ISSUE TITLE
Failed to use Credo

### ISSUE THREAD

**Issue by dsslimshaddy** [rrrene/credo#385]
Failed to use "credo" because
  mix.exs specifies ~> 0.8

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}

I'm using 
`{:credo, "~> 0.8", only: [:dev, :test], runtime: false,override: true}`

**Comment by rrrene** [comment]
You are referring to the `master` README, wich currently contains the release candidate for Credo `v0.8.0`. It might seem unfortunate that we updated the README before the final release, but that's the way the release process goes. :+1:

The last stable version is `v0.7.4` or you can try `v0.8.0-rc6` if you want to test the lastest an greatest. :wink:
