### ISSUE TITLE
Line length calculation is incorrect on lines containing strings

### ISSUE THREAD

**Issue by lee-dohm** [rrrene/credo#389]
### Precheck

* For proposing a new feature, be sure to name your issue "Proposal: ..."
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 0.8.0
* Erlang/Elixir version (`elixir -v`): Erlang/OTC 19 [erts-8.3] Elixir 1.4.4
* Operating system: Mac OS X 10.12.5

### What were you trying to do?

On code:

```elixir
defmodule CredoSampleModule do
  use ExUnit.Case
  def some_fun do
    assert "1" <> "1" <> "1" <> "1" <> "1" <> "1" <> "1" <> "1" <> "1" <> "1" <> "1" <> "1" <> "1" <> "1" == "2"
  end
end
```

Run `mix credo test.ex`

### Expected outcome

Line is too long (max is 80, was 113).

### Actual outcome

line is too long (max is 80, was 97).

Also, if I raise the max line length to 100, I won't get a warning at all.

**Comment by NobbZ** [comment]
Skimmed over it, and it seems related to this bit of code:

https://github.com/rrrene/credo/blob/master/lib/credo/check/readability/max_line_length.ex#L40-L45

```
    source =
      if ignore_strings do
        Credo.Code.Strings.replace_with_spaces(source, "")
      else
        source
      end
```

I do not have an Elixir capable environment at hands right now. But I think it should be sufficient to change the `Credo.Code.Strings.replace_with_spaces(source, "")` to `Credo.Code.Strings.replace_with_spaces(source)`

**Comment by rrrene** [comment]
Yeah, this should be `Credo.Code.Strings.replace_with_spaces(source, ".")`. Good catch!

@lee-dohm If you want to contribute this to Credo, feel welcome to submit a PR. :+1:

**Comment by NobbZ** [comment]
`Credo.Code.Strings.replace_with_spaces/2` has already a default of `" "` for the second argument, so just omitting it should totally be sufficient.

**Comment by rrrene** [comment]
@NobbZ on second thought, this was probably intentional to "cut" strings from line length.

Maybe we should rethink this solution.

**Comment by NobbZ** [comment]
Hmmm... I think I see what you are about.

We need to recognize constructs as in the example as too long while still not reporting a line that has a single very long string in it, because one might probably not be able to alter a long literal string easily into multiple lines...

**Comment by rrrene** [comment]
@NobbZ exactly.

**Comment by lee-dohm** [comment]
From the test cases, it appears that the intent is to not report a violation if the line contains _only_ string content. So if we eliminate the string, delimiters and all, the only thing left on the line should be whitespace. If there is anything on the line other than whitespace, then it is still a violation and the original line should be used for reporting length, etc.

**Violations**

```elixir
text = "blah blah blah blah blah blah blah blah blah blah blah blah"
foo = "bar" <> "bar" <> "bar" <> "bar" <> "bar" <> "bar" <> "bar" <> "bar"
baz = ~s{blah blah blah blah blah blah blah blah blah blah blah blah}
```

**Not Violations**

```elixir
text =
  "blah blah blah blah blah blah blah blah blah blah blah blah"
baz =
  ~s{blah blah blah blah blah blah blah blah blah blah blah blah}
```

Would this be a correct assessment?

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍
