### ISSUE TITLE
`--only` and `--ignore` not working as expected

### ISSUE THREAD

**Issue by jvf** [rrrene/credo#404]
### Environment

* Credo version (`mix credo -v`): 0.8.1 and 0.8.2
* Erlang/Elixir version (`elixir -v`): Elixir 1.4.2
* Operating system: macOS 10.12.5

### What were you trying to do?

I was trying to only running selected checks to reduce runtime of credo, using the `--only` and `--ignore` option.

For example, running `mix credo` on [phoenixframework](https://github.com/phoenixframework/phoenix), took ~12 seconds. Running `mix credo --only consistency` reports `Analysis took 0.6 seconds (0.1s to load, 0.5s running checks)` but the overall runtime of the command is still ~12 seconds.

### Expected outcome

The expected behaviour (cp https://github.com/rrrene/credo/issues/84#issuecomment-221386058)  would be that the runtime of the `mix credo` command is reduced to something close to 1 second for the example above.

### Actual outcome

Running `mix credo --only consistency` reports `Analysis took 0.6 seconds (0.1s to load, 0.5s running checks)` but the overall runtime of the command is ~12 seconds. The reporting of the line `Analysis took 0.6 seconds (0.1s to load, 0.5s running checks)` was fast (~1 second), but the command keeps running for ~11 more seconds until it reports `845 mods/funs, found 3 consistency issues`.

**Comment by philipdexter** [comment]
As for the command still running after it reports its analysis time: running with ExProf shows that most time is spent in `Elixir.Credo.Code.Scope':find_scope/4`. This function is used to print the "845 mods/funs" statistic.

Could one solution be to add a `--stats`/`--no-stats` switch? For example, the patch pasted below (which would need work still) allows me to run `mix credo --only consistency` on phoenix in...
```bash
$ time mix credo --only consistency --no-stats
Checking 72 source files (this might take a while) ... 
[snip]
Analysis took 1.5 seconds (0.1s to load, 1.3s running checks)  
found 3 consistency issues.    

mix credo --only consistency --no-stats  3.76s user 0.30s system 52% cpu 7.805 total
```
and `mix credo --only consistency --stats` in...
```bash
$ time mix credo --only consistency --stats
Checking 72 source files (this might take a while) ...
[snip]
Analysis took 1.5 seconds (0.1s to load, 1.4s running checks)  
845 mods/funs, found 3 consistency issues.                     

mix credo --only consistency --stats  15.74s user 0.29s system 108% cpu 14.809 total
```

The patch:
```diff
diff --git a/lib/credo/cli/options.ex b/lib/credo/cli/options.ex
index c3b9521..126a753 100644
--- a/lib/credo/cli/options.ex
+++ b/lib/credo/cli/options.ex
@@ -21,6 +21,7 @@ defmodule Credo.CLI.Options do
     min_priority: :integer,
     only: :string,
     read_from_stdin: :boolean,
+    stats: :boolean,
     strict: :boolean,
     verbose: :boolean,
     version: :boolean
diff --git a/lib/credo/cli/output/summary.ex b/lib/credo/cli/output/summary.ex
index 83505d8..fb519c4 100644
--- a/lib/credo/cli/output/summary.ex
+++ b/lib/credo/cli/output/summary.ex
@@ -1,6 +1,7 @@
 defmodule Credo.CLI.Output.Summary do
   alias Credo.CLI.Filter
   alias Credo.CLI.Output
+  alias Credo.CLI.Options
   alias Credo.CLI.Output.UI
   alias Credo.Execution
   alias Credo.Check.CodeHelper
@@ -33,7 +34,7 @@ defmodule Credo.CLI.Output.Summary do
     UI.puts
     UI.puts [:faint, format_time_spent(time_load, time_run)]
 
-    UI.puts summary_parts(source_files, shown_issues)
+    UI.puts summary_parts(source_files, shown_issues, exec)
 
     # print_badge(source_files, issues)
     UI.puts
@@ -120,7 +121,7 @@ defmodule Credo.CLI.Output.Summary do
     |> Enum.count
   end
 
-  defp summary_parts(source_files, issues) do
+  defp summary_parts(source_files, issues, %Execution{cli_options: %Options{switches: switches}}) do
     parts =
       @category_wording
       |> Enum.flat_map(&summary_part(&1, issues))
@@ -137,9 +138,11 @@ defmodule Credo.CLI.Output.Summary do
         parts
       end
 
+    print_stats = Map.get switches, :stats, false
+
     [
       :green,
-      "#{scope_count(source_files)} mods/funs, ",
+      (if print_stats, do: "#{scope_count(source_files)} mods/funs, ", else: ""),
       :reset,
       "found ",
       parts,

``
