### ISSUE TITLE
False positive when piping functions into HOFs

### ISSUE THREAD

**Issue by expede** [rrrene/credo#417]
### Precheck

* For proposing a new feature, be sure to name your issue "Proposal: ..."
* For bugs, please do a quick search and make sure the bug has not yet been reported here

There is a _possibly_ similar closed issue (#48), but I'm pretty sure that this is a different case, since they cite an example...

`do_something() |> then_something_else() |> and_last_step()`

...and I'm trying for...

`fn x -> stuff end |> hof_a() |> hof_b() |> ...`

### Environment

* Credo version (`mix credo -v`): 0.8.4
* Erlang/Elixir version (`elixir -v`): Elixir 1.5.0
* Operating system: macOS 10.12.6 

### What were you trying to do?

Pipe a function into a higher order function

### Expected outcome

No warning

### Actual outcome

Credo complains with `Credo.Check.Refactor.PipeChainStart`.

The library that I'm working on is full of higher order functions. Unapplied functions _are_ values. It's a bit of "stuck between a rock and a hard place", since applying the HOF directly causes the exact same issue, because then the form is `hof(fun) |> more() |> ...` (yuck).

I've been [peppering my code](https://github.com/expede/witchcraft/search?utf8=✓&q=Credo.Check.Refactor.PipeChainStart&type=) with `# credo:disable-for-lines:<LINES> Credo.Check.Refactor.PipeChainStart` because I _like_ the rule when it actually applies (ex. `foo(val) |> bar()`), so I don't want to disable it globally. Credo is just being a bit overzealous in this case IMHO 😉 

### Letter of Appreciation

Long time user, first time writer. Thanks for creating and maintaining such a great library! I use it in _every_ project, recommend it to companies that I train, promote it at meet up, &c.`credo --strict` has saved many codebases 🙏 Thanks for all the effort!

**Comment by rrrene** [comment]
@expede Thx for reporting! :+1: This has been resolved in Credo `v0.8.6`.

And thank you for your ind words! Its Credo's contributors and users like you who deserve most of the credit, since well versed bug reports like this one are a huge help in maintaining this project. Thank you! 🥇
