### ISSUE TITLE
Can't include custom checks when Credo is installed globally

### ISSUE THREAD

**Issue by wende** [rrrene/credo#429]
### Environment

* Credo version (`mix credo -v`): 0.8.6
* Erlang/Elixir version (`elixir -v`): 1.5.1
* Operating system: MacOs Sierra

Hello there!

I'm trying to run credo after installing it globally. I've got my `.credo.exs` file that describes which checks to use, one of which is our custom made check. The problem is, we really need credo globally to work with our 3rd party tools, but whenever it is installed globally and ran inside the project it can't find the custom rule module.

<img width="480" alt="screen shot 2017-08-21 at 15 39 48" src="https://user-images.githubusercontent.com/4634386/29524171-006cd698-8687-11e7-9f8b-936b9db21681.png">

Is there a way to run Credo globally AND have our custom checks working?

**Comment by rrrene** [comment]
@wende Ouh... This sounds like a bug. Thx for reporting!

We will have to investigate this further! :+1:

**Comment by rrrene** [comment]
Thx for reporting this! :+1: It should be be fixed in the latest version of Credo.

If it is not, please feel free to re-open this issue!
