### ISSUE TITLE
[.credo.exs] Support excluding `_build` in umbrella e.g. "apps/myapp/_build"

### ISSUE THREAD

**Issue by seantanly** [rrrene/credo#44]
Tried setting `excluded` in `.credo.exs` with `**/_build/` but it didn't work. `_build` folders in `apps/` folders are still being evaluated.

  

```elixir
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["lib/", "src/", "web/", "apps/"],
        excluded: ["**/_build/"]
      },
...
```

**Comment by dpehrson** [comment]
Just hit this as well, it also seems to be doing `apps/*/deps`.

Strangely I have credo in a project at work that doesn't behave this way and I have no idea why.

**Comment by rrrene** [comment]
This was released as part of `v0.4.0-beta1`. Please report any further issues you might find.

**Comment by seantanly** [comment]
@rrrene thanks, going with v0.4.0-beta1 and changing the `excluded` configuration as suggested by the commit above fixes the issue.

@dpehrson The following updated config works correctly now. :)

```elixir
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["lib/", "src/", "web/", "apps/"],
        excluded: [~r"/_build/", ~r"/deps/"]
      },
```

**Comment by rrrene** [comment]
@seantanly @dpehrson Just to be clear, you don't have to change your config with `v0.4.0-beta1` since the snippet you provided is now [part of the default config](https://github.com/rrrene/credo/blob/d0b9145f292ac93f8a8eef340cc1aceea50eee76/.credo.exs#L25) :yellow_heart: :+1:
