### ISSUE TITLE
Cond statement check incorrectly rejects certain conditions

### ISSUE THREAD

**Issue by jlarigakis** [rrrene/credo#440]
### Environment

* Credo version (`mix credo -v`): 0.8.6
* Erlang/Elixir version (`elixir -v`): 1.5.1
* Operating system: macOS Sierra

### What were you trying to do?
Run credo with default settings on the following file:
```elixir
module MyMod do
  def first(thing) do
    cond do
      is_bitstring(thing) -> String.first(thing)
      is_list(thing) -> List.first(thing)
    end
  end
end
```

### Expected outcome
The cond statement is acceptable

### Actual outcome
```
Cond statements should contain at least two conditions besides `true`.
```

As far as I know this is a perfectly legitimate usage of `cond` statements, and neither of those conditions are simply `true`.

**Comment by rrrene** [comment]
Like all Credo issues, this is just a suggestion.

This code 

```elixir
module MyMod do
  def first(thing) do
    cond do
      is_bitstring(thing) -> String.first(thing)
      is_list(thing) -> List.first(thing)
      true -> nil
    end
  end
end
```

is more explicit in that you can see that the default return value of `&first/1` is `nil`.

I will close this issue as the check does work as expected.

**Comment by jlarigakis** [comment]
I see, I just misunderstood the message! I didn't realize it meant "should contain two conditions besides true, and also the condition true". My example does contain two conditions that are not true, which is why I was so confused.

**Comment by rrrene** [comment]
@jlarigakis I see your point, but I am unsure how to phrase this more clearly. Any suggestions?

**Comment by jlarigakis** [comment]
Hmm... 'cond statements should have a default (true) condition, and at
least two other options'?

**Comment by turion** [comment]
To me it seems those are two separate issues. In this case, the error should just be `cond statements should have a default (true) condition.' (though I disagree that they should). The `at least two other options` error only needs to be thrown when it actually occurs (which it doesn't here).

**Comment by Odaeus** [comment]
I just hit this slightly confusing message and found this issue, thanks! Would be great if the error messages could be separated or clarified. I see the issue was closed without resolution, perhaps it could be reopened?

**Comment by lasseebert** [comment]
The example code from above:

```elixir
module MyMod do
  def first(thing) do
    cond do
      is_bitstring(thing) -> String.first(thing)
      is_list(thing) -> List.first(thing)
      true -> nil
    end
  end
end
```

is not just more explicit than

```elixir
module MyMod do
  def first(thing) do
    cond do
      is_bitstring(thing) -> String.first(thing)
      is_list(thing) -> List.first(thing)
    end
  end
end
```

It is different. I have similar code in my project, and I want it to fail (runtime error) if an unexpected `thing` is provided.
I don't know how to rewrite that into something that is not a `cond` with two conditions.

Looking at the error message, it make sense to never use this, since it can be written as an `if`

```elixir
cond do
  is_bitstring(thing) -> String.first(thing)
  true -> nil
end
```

And it also makes sense to never use

```elixir
cond do
  is_bitstring(thing) -> String.first(thing)
end
```

Any suggestions on how to rewrite the `cond` with two clauses of which none is the `true` default?

**Comment by whatyouhide** [comment]
@lasseebert you can have a `true` catch-all clause at the end and explicitly `raise` there. That's what I would go for.

**Comment by lasseebert** [comment]
Thanks @whatyouhide. For now I have just disabled that check, since I would only `raise` to satisfy credo. It is not a code branch I would ever expect, so it would be hard to test, which makes it a good candidate for the built-in `CondClauseError` in my book.
