### ISSUE TITLE
KeyError when running gen.check

### ISSUE THREAD

**Issue by nealfax** [rrrene/credo#442]
Running 'mix credo gen.check' or 'mix credo gen.check foo.ex' results in an error:

`
** (KeyError) key :args not found in: %Credo.Execution{all: false, argv: [], assigns: %{"credo.time.group.convert_cli_options_to_config" => 105698, "credo.time.group.resolve_config" => 36641, "credo.time.group.validate_config" => 27458}, check_for_updates: false, checks: [{Credo.Check.Consistency.ExceptionNames, []}, {Credo.Check.Consistency.LineEndings, []}, {Credo.Check.Consistency.ParameterPatternMatching, []}, {Credo.Check.Consistency.SpaceAroundOperators, []}, {Credo.Check.Consistency.SpaceInParentheses, []}, {Credo.Check.Consistency.TabsOrSpaces, []}, {Credo.Check.Design.AliasUsage, [priority: :low]}, {Credo.Check.Design.DuplicatedCode, [excluded_macros: []]}, {Credo.Check.Design.TagTODO, [exit_status: 2]}, {Credo.Check.Design.TagFIXME, []}, {Credo.Check.Readability.FunctionNames, []}, {Credo.Check.Readability.LargeNumbers, []}, {Credo.Check.Readability.MaxLineLength, [priority: :low, max_length: 80]}, {Credo.Check.Readability.ModuleAttributeNames, []}, {Credo.Check.Readability.ModuleDoc, []}, {Credo.Check.Readability.ModuleNames, []}, {Credo.Check.Readability.ParenthesesOnZeroArityDefs, []}, {Credo.Check.Readability.ParenthesesInCondition, []}, {Credo.Check.Readability.PredicateFunctionNames, []}, {Credo.Check.Readability.PreferImplicitTry, []}, {Credo.Check.Readability.RedundantBlankLines, []}, {Credo.Check.Readability.StringSigils, []}, {Credo.Check.Readability.TrailingBlankLine, []}, {Credo.Check.Readability.TrailingWhiteSpace, []}, {Credo.Check.Readability.VariableNames, []}, {Credo.Check.Readability.Semicolons, []}, {Credo.Check.Readability.SpaceAfterCommas, []}, {Credo.Check.Refactor.DoubleBooleanNegation, []}, {Credo.Check.Refactor.CondStatements, []}, {Credo.Check.Refactor.CyclomaticComplexity, []}, {Credo.Check.Refactor.FunctionArity, []}, {Credo.Check.Refactor.LongQuoteBlocks, []}, {Credo.Check.Refactor.MatchInCondition, []}, {Credo.Check.Refactor.NegatedConditionsInUnless, []}, {Credo.Check.Refactor.NegatedConditionsWithElse, []}, {Credo.Check.Refactor.Nesting, []}, {Credo.Check.Refactor.PipeChainStart, []}, {Credo.Check.Refactor.UnlessWithElse, []}, {Credo.Check.Warning.BoolOperationOnSameValues, []}, {Credo.Check.Warning.IExPry, []}, {Credo.Check.Warning.IoInspect, []}, {Credo.Check.Warning.LazyLogging, []}, {Credo.Check.Warning.OperationOnSameValues, []}, {Credo.Check.Warning.OperationWithConstantResult, ...}, {...}, ...], cli_options: %Credo.CLI.Options{args: [], command: "gen.check", path: "/opt/projectfoo", switches: %{}, unknown_args: [], unknown_switches: []}, color: true, config_comment_map: %{}, crash_on_error: true, files: %{excluded: [~r/\/fixtures\//, ~r/\/_build\//, ~r/\/deps\//], included: ["/opt/projectfoo/lib/**/*.{ex,exs}", "/opt/projectfoo/src", "/opt/projectfoo/web", "/opt/projectfoo/apps/**/*.{ex,exs}"]}, format: nil, halted: false, help: false, ignore_checks: nil, issues_pid: #PID<0.328.0>, lint_attribute_map: %{}, min_priority: 0, mute_exit_status: false, only_checks: nil, read_from_stdin: false, requires: [], results: %{}, skipped_checks: nil, source_files_pid: #PID<0.327.0>, strict: false, verbose: false, version: false}
    lib/credo/cli/command/gen.check.ex:11: Credo.CLI.Command.GenCheck.run/1
    lib/credo/execution/task.ex:36: Credo.Execution.Task.run/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) timer.erl:166: :timer.tc/1
    lib/credo/execution/task_group.ex:52: Credo.Execution.TaskGroup.run/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
`

It looks like gen.check.ex's run() uses exec.args when it should be using exec.cli_options.args.

### Environment

* Credo version (`mix credo -v`): 0.8.6
* Erlang/Elixir version (`elixir -v`): 1.4.4
* Operating system: Ubuntu 14.04

**Comment by rrrene** [comment]
This has been fixed by #445 - thx for reporting! :+1:
