### ISSUE TITLE
SpaceAroundOperators thinks -> as operator

### ISSUE THREAD

**Issue by chulkilee** [rrrene/credo#446]
### Environment

* Credo version (`mix credo -v`): 0.8.6
* Erlang/Elixir version (`elixir -v`): Elixir 1.5.1
* Operating system: Mac

### What were you trying to do?

Running `mix credo` to check files, formatted by https://github.com/whatyouhide/code_formatter

```elixir
@type config_or_func :: Config.t() | (-> Config.t())
```

### Expected outcome

No error

### Actual outcome

Got "There are spaces around operators most of the time, but not here."

`->` in the `@type` is not operator :)

**Comment by rrrene** [comment]
Thx for reporting! :+1:

**Comment by OvermindDL1** [comment]
'Technically' `->/2` is an operator in the AST.  However something like `-> blah` is inferred like `() -> blah`.  The bug here is that it seems that Credo wants a space between `(` and `->`, which does indeed seem superfluous to me.  ^.^;

**Comment by rrrene** [comment]
@chulkilee Thanks for reporting this 😀

@OvermindDL1 It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍
