### ISSUE TITLE
Bug: Incorrect "There should be no unused return values for Enum.join" when immediately returned in function

### ISSUE THREAD

**Issue by Gyllsdorff** [rrrene/credo#457]
### Environment

* Credo version (`mix credo -v`): 
```
0.8.6
```
* Erlang/Elixir version (`elixir -v`):
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:72:72] [ds:72:72:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```
* Operating system:
Centos 7

### What were you trying to do?
```elixir
    Logger.info(fn ->
      [method, status, request_path, formatted_diff(run_time)]
      |> Enum.join(" ")
    end)
```

### Expected outcome
No warning

### Actual outcome
When I ran `credo list --strict` I got a warning that the code ignored the return value of the `Enum.join` call.
```bash
12:27:13 ▶ PATH=build/elixir-1.5.1-otp-20/bin:build/erlang-20.0/bin:$PATH mix credo list --strict

[SNIP]
┃ [W] ↗ There should be no unused return values for Enum.join().
┃       [PROJECT NAME AND PATH TO FILE]/request_logger.ex:38:10 ([PROJECT NAME].RequestLogger.log_request)
┃
┃             |> Enum.join(" ")
┃          ^^^^^^^^^
┃
```

### Workaround
```elixir
    Logger.info(fn ->
      message =
        [method, status, request_path, formatted_diff(run_time)]
        |> Enum.join(" ")

      message
    end)
```

**Comment by rrrene** [comment]
Thx for reporting! :+1:

**Comment by rrrene** [comment]
Could you test this against the current version? It seems to me that Credo `v0.8.8` does solve this issue.

**Comment by rrrene** [comment]
@Gyllsdorff I am closing this for now. If the problem persists, please re-open! :+1:

**Comment by the-mikedavis** [comment]
@andrelip this is a late comment, but aren't you leaving that `Enum.to_list/1` value unused? If you're trying to realize the stream, you can just use `Stream.run/1` and match it to `:ok` if you like.
