### ISSUE TITLE
Unused `Enum.reduce` return values shouldn't trigger `UnusedEnumOperation`

### ISSUE THREAD

**Issue by glittershark** [rrrene/credo#462]
I have a case right now where I'm running a side-effect-only function in a `reduce`, and using the accumulator to keep a memo of metadata about operations I've done so far. Obviously, since the accumulator is a local memo, I never have to use it outside of the `reduce` call, but of course this then triggers Credo's `UnusedEnumOperation`. Unlike `map`, however, there's no version of `reduce` which indicates that it's being executed only for side effects (and there'd be no point in having one, since there's no optimization to be gained from discarding the return value).

In light of this situation, I'd like to suggest that `reduce` be removed from the list of functions which will trigger `UnusedEnumOperation`, as in situations like this there's no real way to rewrite the behavior short of either raw recursion (ick) or an Agent (double ick).

**Comment by OvermindDL1** [comment]
I'd personally prefer this to definitely trigger on `Enum.reduce` as I don't want to forget about the return values (I minimize side-effects).  Can't you just do `_ = Enum.reduce(...)`?

**Comment by rrrene** [comment]
I am closing this, since @OvermindDL1 has suggested a great workaround and I do not - at this point - see any reason to modify the check.

P.S. Please use the provided Issue template, it is really not there to annoy you. It makes the whole process more ... whole. :+1:
