### ISSUE TITLE
`mix credo.gen.config` leaves erroneous comment for AliasUsage

### ISSUE THREAD

**Issue by AaronJamesKing** [rrrene/credo#465]
With the Credo dep specified as follows:
`{:credo, "~> 0.8", only: [:dev, :test], runtime: false}`

After running `mix credo.gen.config`, the generated config file includes the following comment on line 58:

`# For some checks, like AliasUsage, you can only customize the priority`

And on [line 61](https://github.com/rrrene/credo/blob/master/.credo.exs#L61), the `AliasUsage` check indeed has the priority set to `:low`. However, the [AliasUsage](https://github.com/rrrene/credo/blob/master/lib/credo/check/design/alias_usage.ex#L35-L36) module allows two other parameters (`:if_nested_deeper_than` and `:if_nested_deeper_than`).

So the comment should be removed, or placed above a check that doesn't have custom parameters. Note that the next two blocks of comments ([lines 63-74](https://github.com/rrrene/credo/blob/master/.credo.exs#L63-L74)) are continuations of the erroneous comment, so the best option is to swap the AliasUsage check. I'd be happy to find a better one and submit a PR!

**Comment by rrrene** [comment]
@AaronJamesKing Ouch! If you are still up for the task, I will gladly merge a PR improving this! :+1:

**Comment by AaronJamesKing** [comment]
Just submitted #470 :)
