### ISSUE TITLE
Wrong assumption when subtracting `:rand.uniform` from itself

### ISSUE THREAD

**Issue by vasspilka** [rrrene/credo#476]
On the following piece of code I get 
```
Float.round(((:rand.uniform - :rand.uniform) / 100), 13)
```
`Operation will always return 0.` That is not the case, but it is an understandable assumption.

In case anyone wonders, it is used to give a deviance from -0.001 to 0.001

**Comment by NobbZ** [comment]
Have you tried `:rand.uniform()`? As far as I remember you need this for credo to tell it if a function call is expected to return a constant value or not.

**Comment by rrrene** [comment]
We might want to add an option to exclude certain triggers on these types of checks.

Thanks for reporting! :+1:

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by vasspilka** [comment]
Hey, yes the issue is solved, thanks for closing :)
