### ISSUE TITLE
Pipe chain should start with a raw value.

### ISSUE THREAD

**Issue by stevedomin** [rrrene/credo#48]
The following line of code triggers a "refactoring opportunity":

```elixir
do_something() |> then_something_else() |> and_last_step()

# [F] → Pipe chain should start with a raw value.
```

It feels like this a valid use case for a pipe, and that credo should say anything about this code. Is that right?

Apologies if this was discussed previously, I searched on the repo but couldn't find anything.

**Comment by rrrene** [comment]
That's clearly a bug in Credo. Thx for reporting!

**Comment by stevedomin** [comment]
You're welcome, thanks for your awesome work on this tool

**Comment by rrrene** [comment]
Hi Steve, `v0.3.6` contains a patch for this! Thx for reporting :+1:

**Comment by stevedomin** [comment]
Great, thank you @rrrene!
