### ISSUE TITLE
How do I add credo as a dependency to be installed during CI checks?

### ISSUE THREAD

**Issue by palash25** [rrrene/credo#482]
### What were you trying to do?
I am trying to write a Linter bear(a wrapper for an external tool to be integrated with coala) for credo. To test my wrapper I need credo to be collected and installed as a dependency during CI checks. But I can't seem to figure it out?
For e.g. in case of python dependencies, we add them all to a `requirements.txt` file in case of javascript we add them to `package.json`. So what do I do in case of credo? And are there any other dependencies to be installed for credo to run apart from mix?

PR Link: https://github.com/coala/coala-bears/pull/2172

**Comment by NobbZ** [comment]
As for every elixir dependency you specify them in mix.exs as [described in the README](https://github.com/rrrene/credo/blob/master/README.md#installation).

**Comment by palash25** [comment]
And then I run that mix.exs file by including it in my CI config files?

**Comment by NobbZ** [comment]
You just run `mix deps.get; mix deps.compile; mix credo` but that's all in the README and all pretty much as you do it everywhere for elixir...

**Comment by rrrene** [comment]
@palash25 It seems that your problem was related to the installation of Erlang, not Elixir or Credo.

I answered your email regarding this matter and will close this issue. :+1:
