### ISSUE TITLE
Credo.Check.Readability.VariableNames dont work on function parameter variables

### ISSUE THREAD

**Issue by enotsimon** [rrrene/credo#483]
### Environment

* Credo version: 0.8.10
* Erlang/Elixir version: Erlang/OTP 18 [erts-7.3] / Elixir 1.4.2

### What were you trying to do?
suppose we have code like this
```
def some_func(notSnakeCase) do
  notSnakeCase + 1
end
```

### Expected outcome
Code Readability.
Variable names should be written in snake_case.

### Actual outcome
nothing

**Comment by rrrene** [comment]
Thanks for reporting this! :+1:
