### ISSUE TITLE
mix deps.get returns error: (Mix) No matching version for credo ~> 0.9

### ISSUE THREAD

**Issue by SirajKakeh** [rrrene/credo#489]
### Environment

* Credo version (`mix credo -v`): 0.8.10
* Erlang/Elixir version (`elixir -v`): Erlang/OTP 20, Elixir 1.5.2
* Operating system: Ubuntu 16.04 Xenial

### What were you trying to do?
Just created a new Phoenix project using `mix phx.new` command. Tried to integrate Credo by copying the line in the Readme: `{:credo, "~> 0.9", only: [:dev, :test], runtime: false}`. Then ran `mix deps.get` and got this error `** (Mix) No matching version for credo ~> 0.9 (from: mix.exs) in registry`

### Expected outcome
`mix deps.get` should install Credo successfully

### Actual outcome
** (Mix) No matching version for credo ~> 0.9 (from: mix.exs) in registry

**Comment by rrrene** [comment]
@SirajKakeh Thx for reporting this. I fixed the README. :+1:
