### ISSUE TITLE
incorrect `Variable was declared more than once`

### ISSUE THREAD

**Issue by tim2CF** [rrrene/credo#510]
### Environment

* Credo version (`mix credo -v`):  0.8.10
* Erlang/Elixir version (`elixir -v`): 1.6.1
* Operating system: macOS 10.13.3

### What were you trying to do?

I'm trying to run style checks for source code containing function like

```
def recode(data = %struct{}, from, to) when is_binary(from) and is_binary(to) do
    from_size = byte_size(from)
    <<^from::binary-size(from_size), subname::binary>> = struct |> Atom.to_string
    ...
```

`mix credo` task gives me warning

```
  Refactoring opportunities
┃
┃ [F] → Variable "from_size" was declared more than once.
```

But as you can see, variable `from_size` was declared only once.

**Comment by rrrene** [comment]
@tim2CF 
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍
