### ISSUE TITLE
Proposal for moduledoc emptiness check

### ISSUE THREAD

**Issue by Mehonoshin** [rrrene/credo#519]
### What were you trying to do?

Check not just presence of `@moduledoc` but also its contents, to prevent having empty docs.

### Expected outcome

Warning when module doc is an empty string

### Actual outcome

No warning.

**Comment by rrrene** [comment]
@Mehonoshin 
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by Mehonoshin** [comment]
@rrrene ah, you are fast :-D I've just started doing that by myself

**Comment by Mehonoshin** [comment]
It works! Thanks for instant fix 👍
