### ISSUE TITLE
Bug: custom defguard functions can only include kernel functions

### ISSUE THREAD

**Issue by mrdougwright** [rrrene/credo#524]
### Environment

* Credo version: 0.9.0
* Erlang/Elixir version:  1.6.4
* Operating system: MacOS High Sierra

### What were you trying to do?
```elixir
  defguard is_empty?(value) when is_list(value) and length(value) == 0
```

### Expected outcome
Credo should be happy with this.

### Actual outcome
 length(value) == 0 is expensive. Prefer Enum.empty?/1 or list == []

Unfortunately, we cannot use Enum and other modules inside of guard functions.

**Comment by OvermindDL1** [comment]
Credo absolutely should *not* be happy with this!  `length(value) == 0` is very *slooooow* and instead `list == []` should be used instead (or more smartly `defguard is_empty?([])` if `defguard` was programmed better, which it wasn't...).

**Comment by mrdougwright** [comment]
👍
