### ISSUE TITLE
Bunt installation instruction for stand alone installation is missing from credo-ci.org

### ISSUE THREAD

**Issue by fapdash** [rrrene/credo#525]
The bunt installation instruction added [here](https://github.com/rrrene/credo/pull/395) are missing from [credo-ci.org](http://credo-ci.org/):

![selection_206](https://user-images.githubusercontent.com/459631/38678547-98976f04-3e61-11e8-9ca0-18b422ba30b3.png)

**Comment by rrrene** [comment]
Thx for reporting this! :+1:

For the time being, the website has been reconfigured to redirect to this repository on GitHub, which (kind of) solves this issue.
