### ISSUE TITLE
Proposal - Filter out checks to run by priority too

### ISSUE THREAD

**Issue by techgaun** [rrrene/credo#532]
### Environment

* Credo version (`mix credo -v`): 0.9.1
* Erlang/Elixir version (`elixir -v`): OTP20 / 1.6.4
* Operating system: Ubuntu

### What were you trying to do?

I was trying to run checks based on priorities only. 

### Expected outcome

Be able to filter out the checks to run based on the priorities

### Actual outcome

Can not filter out the checks based on the priorities

### Use Case

While the `--only warning,refactor` does work to filter out the checks based on the type, sometimes it is convenient to be able to run only the checks that have priority higher than certain value such as >= `high`. For example, I want to fail on `PipeChainStart` but not on other readability issues in my CI environment but I still want to gradually fix other pipelines so I can not really disable other checks under readability category.

Something like below:

`mix credo --priority high` -> can run `high` or `higher` checks

Alternatively, we could do:
`mix credo --priority high,higher`

I could not find any relevant docs but I am sorry if I am overlooking certain things

**Comment by dotboris** [comment]
There's already a flag for this. It's not documented and it's a little convoluted.

You can use `--min-priority {n}` where `{n}` is the minimum priority number. The mapping between the priority name and it's number is in: https://github.com/rrrene/credo/blob/master/lib/credo/check.ex#L6-L12

If your case, to include high and higher issues, you'd do

```sh
mix credo --min-priority 10
```

**Comment by rrrene** [comment]
@dotboris Wow, you really know your credo 😄 👍 

That said, we should probably document that switch and allow the named values @techgaun mentioned above.
