### ISSUE TITLE
A usability note

### ISSUE THREAD

**Issue by deadtrickster** [rrrene/credo#548]
Hi, First I would like to thank you for credo. I use it with every project.

However I came here to complain about versioning (not sure there) :-). 
We had this in our mix.exs: `~> 0.8`, then for some reason 0.9.3 was downloaded and our builds started to fail because of new alias ordering check.

So now we are really confused because with thought `-> 0.8` is `0.8.x` and because
builds failed for "no reason". 

So we ended up disabling AliasOrder and pinning credo to `0.9.3`. But we want bug fixes! Any suggestions on this? how to get the version right, so we will get bug fixes, but not new checks?

Thank you

**Comment by OvermindDL1** [comment]
`~> 0.8` means `>= 0.8 and < 1.0`.  If you wanted to be constrained to 0.8.x then should do `~> 0.8.0` (or whatever specific patch version minimum you want).  The `~>` means update the lowest specified up to but not including the next prior.

**Comment by deadtrickster** [comment]
yea, thanks I new it's something stupid here. But AliasOrder was added to patch version

**Comment by rrrene** [comment]
> But AliasOrder was added to patch version

@deadtrickster You are right. I'm sorry about this and will be more considerate in the future!

**Comment by deadtrickster** [comment]
@rrrene no problem, thanks again for awesome tool. closing
