### ISSUE TITLE
Slow loading in umbrella

### ISSUE THREAD

**Issue by MvanDiemen** [rrrene/credo#559]
Hi there,

We are avid users of credo in our codebase, thanks for the project BTW

A couple of months ago we decided to move our project over to an umbrella, but as the umbrella started to grow we noticed the loading times for credo getting slower, whilst run time stays roughly the same. I am not sure what causes the issue and have tried some tweaking in the selection of paths to load but to no avail. I was wondering if you had any idea how to correct this, I can't find anything about the loading time issue.

### Environment

I am running on Arch Linux and my coworkers are using macOS 10.13

```
> uname -r
4.16.13-2-ARCH
> mix credo -v
0.9.2
>  elixir -v
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.5 (compiled with OTP 20)
```

### What were you trying to do?

I am trying to start credo without loading times above 10 seconds.

#### The old monolith
```
> mix credo --strict
Checking 154 source files (this might take a while) ...

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 3.3 seconds (0.09s to load, 3.2s running checks)
941 mods/funs, found no issues.
```

#### The new umbrella
```
> mix credo --strict
Checking 247 source files (this might take a while) ...

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 13.2 seconds (11.0s to load, 2.2s running checks)
668 mods/funs, found 1 software design suggestion.
```

As you can see the loading time has grown massively, I am not sure what the solution would be.

This is the old `.credo.exs`
```elixir
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["lib/", "src/", "web/", "apps/"],
        excluded: []
      },
      checks: [...] # Same as the new
    }
  ]
}

```

This is the new `credo.exs`
```elixir
%{
  configs: [
    %{ 
      name: "default",
      files: %{
        included: ["lib/", "src/", "test/", "web/", "apps/"],
        excluded: [~r"/_build/", ~r"/deps/", ~r"/config/", "**/node_modules/"]
      },
      requires: [],
      strict: false,
      color: true,
      checks: [...] # Same as the old
    }
  ]
}
```

**Comment by rrrene** [comment]
@MvanDiemen `**/node_modules/` causes Credo to use `Path.wildcard/1` which can take a long time in large directory trees (a.k.a. node/js projects).

Try this line:

> excluded: [~r"/_build/", ~r"/deps/", ~r"/config/", "**/node_modules/"]

Replace the glob at the end with a regular expression:

> excluded: [~r"/_build/", ~r"/deps/", ~r"/config/", **~r"/node_modules/"**]

**Comment by MvanDiemen** [comment]
Using `~r"/node_modules/"` or `~r"/assets/"` improves the speed a bit, but not by the amount I'd expect.

With the following config:
```elixir
      files: %{
        included: ["apps/"],
        excluded: [~r"/_build/", ~r"/deps/", ~r"/config/", ~r"/assets/", ~r"/priv/"]
      },
```

It still takes 3.8 seconds to load compared to 0.09 for the monolith:
```
> mix credo --strict                                                                                                                                                                                                                        10:31.02
Checking 234 source files (this might take a while) ...

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 6.1 seconds (3.8s to load, 2.2s running checks)
661 mods/funs, found no issues.
```

**Comment by TheFirstAvenger** [comment]
@MvanDiemen could you try the new default I proposed in https://github.com/rrrene/credo/pull/723 ?
