### ISSUE TITLE
Proposal: replace case with true/false with an if

### ISSUE THREAD

**Issue by whatyouhide** [rrrene/credo#564]
In some codebases, I often see an heritage from Erlang:

```elixir
case foo do
  true -> :a
  false -> :b
end
```

In Elixir, this often is not necessary because we have `if`. The case above can be rewritten to

```elixir
if foo do
  :a
else
  :b
end
```

I think a check for this would help. If you agree, I can give it a shot!

**Comment by rrrene** [comment]
@whatyouhide I agree :+1:

**Comment by OvermindDL1** [comment]
It's not a direct translation though as then the typespecs change.  `if` allows for truthy/falsey values, where the original case only allows for the specific `true`/`false` atoms, thus extra things that could be passed in that would pass typing that would not have with the original case.

**Comment by rrrene** [comment]
@whatyouhide After thinking about this, I think we already have [a check like the one you described](https://github.com/rrrene/credo/blob/d67029dd543541f7a6ef62b31b62f5f02505ef77/lib/credo/check/refactor/case_trivial_matches.ex) which we deprecated [after this discussion](https://github.com/rrrene/credo/issues/65).

WDYT?

**Comment by whatyouhide** [comment]
Yeah the arguments for not having it are compelling. I'll retreat :) Thanks for the help!
