### ISSUE TITLE
Clean up `mix test` warnings

### ISSUE THREAD

**Issue by winterchord** [rrrene/credo#578]
### Precheck

There are two sets of warnings that pop up when running `mix test`:

1. quoted keyword warnings
1. `not expr1 in expr2` warnings

Would be nice to clean them up; reduce the output noise.

### Environment

* Credo version (`mix credo -v`): 0.10.0
* Erlang/Elixir version (`elixir -v`): 1.7.3
* Operating system: MacOS 10.13.6

### Notes

This issue will include two separate PRs that address the warnings cleanup separately.

**Comment by rrrene** [comment]
@winterchord Thx for reporting (and fixing)! 😄 :+1:
