### ISSUE TITLE
Ignore white-space after a trailing comma in a list

### ISSUE THREAD

**Issue by eksperimental** [rrrene/credo#61]
I found to be good practice to leave lists to contain a trailing comma,
`@options [foo: 1, bar: 2, ]`
so it's implied that more elements can be added to this list,

but when running `mix credo --strict` I will get a warning:
> [C] ↗ There is no whitespace around parentheses/brackets most of the time, but here there is.

The warning is gone when I remove the trailing white space
would it be possible to ignore the trailing space when it's presided by a comma, and just judge the list by whether it starts with a white-space or not.

thank you for creating such a beautiful tool

**Comment by rrrene** [comment]
Ah, did not think of this. Thanks for reporting! :+1:

**Comment by rrrene** [comment]
@eksperimental I released a fix in `v0.3.12` :shipit: 

I'm not really sure if it was a good idea that `[]`, `{}` and `()` pairs are all treated by [the same check](https://github.com/rrrene/credo/blob/35fef8ece287a15b56ebe196eb309d1b4e188e6c/lib/credo/check/consistency/space_in_parentheses.ex) inside Credo. Your case above makes it clear that there are subtle differences in their semantics, so I think I should separate each of these into their own  checks for `v0.4.0`.

Thoughts?

**Comment by eksperimental** [comment]
thank you!

**Comment by eksperimental** [comment]
I think I missed your previous comment,
I think `[ ]` and `{ }` are fine to have the rule, parentesis are a special case as I cannot think a case where you would use a comma at the end.
