### ISSUE TITLE
Proposal: Module Report Card

### ISSUE THREAD

**Issue by TreyE** [rrrene/credo#620]
Add a new command.

report_card - generates a report card grading your modules.
It supports both console and HTML output formats.
The HTML output will add a file in credo/index.html.

This code is already implemented as pull request #619.

Please Note:  This proposal does not include the Code Coverage check introduced in the previous proposal, #613.

**Comment by rrrene** [comment]
Please refer to https://github.com/rrrene/credo/pull/619
