### ISSUE TITLE
MapInto warning when already using Enum.into/3

### ISSUE THREAD

**Issue by lasseebert** [rrrene/credo#627]
### Environment

* Credo version (`mix credo -v`): 1.0.0
* Erlang/Elixir version (`elixir -v`): 1.8.0 / 21.2.3
* Operating system: Ubuntu

### What were you trying to do?

```elixir
my_list
|> Enum.map(&square/1)
|> Enum.into(%{}, &to_tuple/1)
```

### Expected outcome

No warning

### Actual outcome

It warns that "`Enum.into/3` is more efficient than `Enum.map/2 |> Enum.into/2`".
This seems like a bug, since I'm already using `Enum.into/3` and not `Enum.into/2`.

If this is verified, I will be happy to provide a PR.

**Comment by lasseebert** [comment]
By the way, this is `Credo.Check.Refactor.MapInto` ;)

**Comment by rrrene** [comment]
Thx for reporting! :+1:

**Comment by lasseebert** [comment]
Thanks! ❤️
