### ISSUE TITLE
`not in` is not available in Elixir 1.4

### ISSUE THREAD

**Issue by princemaple** [rrrene/credo#631]
### Environment

* Credo version (`mix credo -v`): 1.0.1
* Erlang/Elixir version (`elixir -v`): 1.4
* Operating system: travis CI

### What were you trying to do?
compile credo on Elixir 1.4

### Expected outcome
compiles fine

### Actual outcome
```
== Compilation error on file lib/credo/check/refactor/abc_size.ex ==
** (SyntaxError) lib/credo/check/refactor/abc_size.ex:194: syntax error before: in
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

https://github.com/swoosh/swoosh/pull/336
https://travis-ci.org/swoosh/swoosh/jobs/485319511

**Comment by rrrene** [comment]
@princemaple 
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍
