### ISSUE TITLE
 no function clause matching in Credo.Code.Name.full/1

### ISSUE THREAD

**Issue by mtarnovan** [rrrene/credo#637]
There's a repo that reproduces the issue: https://github.com/mtarnovan/credo_issue

#242 looks related

**Comment by rrrene** [comment]
@mtarnovan Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by mtarnovan** [comment]
Thank you kindly René. We'll try out master and report back.

**Comment by mtarnovan** [comment]
Confirming the issue is fixed. Thanks again.
