### ISSUE TITLE
Credo can support find functions that is directly call in module ?

### ISSUE THREAD

**Issue by developerworks** [rrrene/credo#64]
Fully qualified function call is ok in hot upgrade, 
Add a new feature that could scan what directly functions call exists in a module

**Comment by rrrene** [comment]
Hi there,

`v0.4.0` which is currently in the works will add support for custom checks. This will allow you to do what you want.

I will leave this issue open and ping you once `v0.4.0` is released! :+1:

**Comment by rrrene** [comment]
This has been added in the meantime. Sorry for the delay!
