### ISSUE TITLE
Proposal: Experimental "Avoid Multi Alias" Rule

### ISSUE THREAD

**Issue by asummers** [rrrene/credo#641]
### What were you trying to do?
One thing that I find when entering a new large code base for the first time is that having multi-aliases, e.g.

```elixir
alias Foo.{Bar, Baz}
```

makes the code significantly harder to grep for things. While I recognize not everyone shares my opinion here (same as with the `@spec` rule, for example), I would like to propose an off-by-default rule to disallow multi aliases. In the example above, it would encourage the use of:

```elixir
alias Foo.Bar
alias Foo.Baz
```

**Comment by rrrene** [comment]
I would merge a PR for the proposed check. :+1:
