### ISSUE TITLE
Proposal: Toggle ignoring multiline strings in RedundantBlankLines check

### ISSUE THREAD

**Issue by sadir** [rrrene/credo#643]
Hey, thanks for maintaining this library! Just reporting a feature I would find helpful. For now I'm going to turn off the RedundantBlankLines check for certain files which is fine, so I don't view this as a high priority issue. More just feedback in case others are running into it too.

### Environment

* Credo version (`mix credo -v`):

```
-> mix credo -v
Ignoring an undefined check: Credo.Check.Warning.NameRedeclarationByAssignment
Ignoring an undefined check: Credo.Check.Warning.NameRedeclarationByCase
Ignoring an undefined check: Credo.Check.Warning.NameRedeclarationByDef
Ignoring an undefined check: Credo.Check.Warning.NameRedeclarationByFn
1.0.3
```

* Erlang/Elixir version (`elixir -v`):

```
-> elixir -v
Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```

* Operating system:

```
-> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

### What were you trying to do?

I have a test file with a big multiline string in it, which represents an argument a webhook of mine will be called with. It's something like this:

```
@body """
Dear team,
You have a new thing you should know about
Please parse the details below


---


APPLICANT'S DETAILS


More stuff below...
"""
```

### Expected outcome

I want to disable this multiline check for multiline strings, because they tend to have intentional extra lines in them.

### Actual outcome

I can't do this right now.

**Comment by rrrene** [comment]
Thx for reporting! :+1: 

I think we can assume all white-space in heredocs to be intentional and added a test reproducing this issue.

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by sadir** [comment]
Reporting back: resolved!

Thanks for the quick turnaround mate. Appreciate it. Keep doing you 👍 

Will this go into a release soon?

**Comment by rrrene** [comment]
@sadir Credo `v1.0.4` was just published and contains this fix.
