### ISSUE TITLE
Proposal: Support configuration file as command-line argument

### ISSUE THREAD

**Issue by crertel** [rrrene/credo#653]
I think it would be helpful to add the ability to manually specify a config file for Credo from the command line.

This would, for example, make it easy to do multiple configs for CI, dev, etc. if the settings are sufficiently different.

**Comment by gylaz** [comment]
Can't you already do that with `--config-name` cli option?

**Comment by rrrene** [comment]
@crertel You should be able to do that using the existing options. 

To quote from the output of `mix credo suggest --help`:

```
      --config-file       Use the given config file
  -C, --config-name       Use the given config instead of "default"
```

Does this solve your problem?

**Comment by crertel** [comment]
That does indeed solve my problem! I didn't spot that in my reading of the docs. Thank you very much, closing this issue. :)
