### ISSUE TITLE
Question: Is there a way to increase the timeout?

### ISSUE THREAD

**Issue by pavellishin** [rrrene/credo#656]
Is there a way to increase the amount of time credo is willing to wait for parsing to complete? I would much rather wait an extra 20 seconds than see that some files weren't parsed, since I end up needing to run credo again anyway.

I tried running `mix credo gen.config`, but didn't see any obvious options related to this.

### Environment

* Credo version: 0.10.1
* Erlang version: Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
* Elixir version: Elixir 1.6.6 (compiled with OTP 19)
* Operating system: CentOS release 6.10 (Final)

### What were you trying to do?
Run credo on all the files in our codebase.

### Expected outcome
All files are checked.

### Actual outcome
```
info: Some source files were not parsed in the time allotted:
...
followed by a list of files, which varies in size from run to run
```

**Comment by rrrene** [comment]
@pavellishin There is not at the moment. 5000 ms is just the default timeout for Tasks in Elixir. This behaviour was added in #576 to prevent builds from crashing, but I see that our current implementation is not ideal. 

What would you propose?

**Comment by pavellishin** [comment]
I'm still fairly new to Elixir, but I'd propose either a flag to specify how long it should wait before giving up, or a tag to never give up (_never surrender!_) to err on the side of checking all the files.

**Comment by robotpistol** [comment]
Something that would probably help alleviate this would be to add the ability to run credo on a given path. Giving it a directory rather than a single file which seems to be the current only alternative.

**Comment by TMSCH** [comment]
Hi! I'd also really like to see it configurable - @rrrene could this be an option?

**Comment by TheFirstAvenger** [comment]
@pavellishin Submitted a pull request that allows you to change the parse timeout.
