### ISSUE TITLE
Proposal: Checking "with" clauses

### ISSUE THREAD

**Issue by whatyouhide** [rrrene/credo#658]
I have been playing with a check that I believe is important, I called it `WithClauses`.

In a lot of codebases I've seen examples like this:

```elixir
with {:ok, result} <- fun() do
  # ...
else
  {:error, reason} ->
    # ...
end
```

I always complain about this because using a `with` in this case makes the code more obscure and harder to read since I search for the semantics of `with` when what is actually happening is a `case`:

```elixir
case fun() do
  {:ok, result} ->
    # ...

  {:error, reason} ->
    # ...
end
```

Furthermore, I sometimes see this:

```elixir
with var1 = fun1(),
     {:ok, var2} <- fun2(),
     {:ok, var3} <- fun3(),
     fun3() do
  # ...
end
```

This is confusing to read: I will think that there's a reason why the first `=` clause and the last `fun4()` clause are part of the clauses of the `with`, when in fact there's no reason. I think it's much better to be explicit and only write `with`s where the first and last clause are `<-` clauses. The clauses before the first `<-` clause can be moved outside of the `with`, and the ones after can be moved in the body of the `with`.

```elixir
var1 = fun1()

with {:ok, var2} <- fun2(),
     {:ok, var3} <- fun3() do
  fun4()
  # ...
end
```

@rrrene are you interested in a check like this being introduced into Credo itself? I have the code ready and working and we're using it already, but wanted to see if it could be contributed upstream :)

**Comment by rrrene** [comment]
> @rrrene are you interested in a check like this being introduced into Credo itself?

@whatyouhide Absolutely :+1:

Are these two separate checks? It would seem so from your description (and it seems to me like two different "use cases").

**Comment by whatyouhide** [comment]
@rrrene right now it's a single check and I think it belongs to a single check because as I see it you're either interested in having a correct `with` statement or you are not. If you want to separate the concerns, I think I would still go for options in the `WithClauses` check. Wdyt?

**Comment by rrrene** [comment]
@whatyouhide Now I see what you mean. It's about clean `with` usage, just the recommended changes differ.

Fine with me :+1:

**Comment by whatyouhide** [comment]
PR incoming!
