### ISSUE TITLE
Bug: Incorrectly finds references to module in a comment

### ISSUE THREAD

**Issue by pavellishin** [rrrene/credo#663]
### Environment

* Credo version: 0.10.1
* Erlang version: Erlang/OTP 20 [erts-9.3.3.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
* Elixir version: Elixir 1.6.6 (compiled with OTP 20)
* OS: 10.13.6

### What were you trying to do?
Run credo on our project.

### Expected outcome
👍 

### Actual outcome

```
Checking 1302 source files (this might take a while) ...

  Consistency
┃
┃ [C] ↗ The Bugsnag module is being accessed outside of BugsnagReporter
┃       lib/tpt_api/organization/organization.ex:557:20 #(TptApi.Organization.create_org_admin_result)

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 32.9 seconds (1.5s to load, 31.4s running checks)
```

But line 557 actually contains a comment:

```
556:    # An organization already existing for a given school edit ID should not
557:    # alert us via Bugsnag; it just means someone tried to register as an admin
558:    # for a school that already has an organization.
```

**Comment by rrrene** [comment]
@pavellishin Thx for reporting this!

Unfortunately, I am a bit at a loss. Two aspects:

1) I do not recognize the Credo check - is it a custom one?
2) This might still be an error in Credo's utility functions: Could you update Credo to 1.1.0 and try again?

**Comment by pavellishin** [comment]
> I do not recognize the Credo check - is it a custom one?

Hm, I'm going to have to check at work and get back to you. I'll also check about upgrading.

**Comment by TheFirstAvenger** [comment]
@pavellishin Do you have an update on this, or can the issue be closed?

**Comment by pavellishin** [comment]
I don't have an update, and given that it's been half a year, I'm not likely to follow up - I don't work with elixir that much anymore.

(Though, you know - murphy's law. I'm going to click "close", and then someone's going to run over to my desk and ask how much I know about credo...)
