### ISSUE TITLE
Bug: false positive of "[R] → Space missing after comma"

### ISSUE THREAD

**Issue by RichMorin** [rrrene/credo#671]
### Precheck

Done

### Environment

* Credo version (`mix credo -v`): 1.1.0
* Erlang/Elixir version (`elixir -v`): 1.9.0
* Operating system: macOS High Sierra (version 10.13.6)

### What were you trying to do?

    $ mix credo

### Expected outcome

    <crickets>

### Actual outcome

    [R] → Space missing after comma
      apps/info_files/lib/info_files/cnt_any.ex:193:50
       # (InfoFiles.CntAny.add_file_paths)

### Source code

    file_patt   = "*.{#{ Enum.join(file_exts, ",") }}"

### Discussion

The offending comma is not code; rather, it is located in a text string, which is data. I suspect that credo is getting confused because of the layering of contexts:

- code
- data (string `"..."`))
- code (interpolated `join/2`)
- data (parameter `","`)

**Comment by TheFirstAvenger** [comment]
I was able to reproduce this issue on `v1.1.0` on elixir `v1.9.0`, but not on `v1.1.1`. @RichMorin can you verify that it is working as expected for you on a newer version?

**Comment by RichMorin** [comment]
Running credo 1.1.5 on elixir 1.9.0, I'm still able to reproduce the issue:

 [R] → Space missing after comma
┃       apps/info_files/lib/info_files/cnt_any.ex:162:50 #(InfoFiles.CntAny.add_file_paths)

**Comment by TheFirstAvenger** [comment]
@RichMorin Still unable to reproduce this on v1.1.5, but I see it on v1.1.0. Can you run `mix deps.clean credo` and `mix deps.get credo` and retry?

**Comment by RichMorin** [comment]
Hmmm.  I guess I didn't do a `mix deps.clean credo` last time.  Anyway, the problem seems to have disappeared in v1.1.5; thanks!

**Comment by rrrene** [comment]
@RichMorin Glad your issue  has been solved. Thx again for reporting! 👍

**Comment by RichMorin** [comment]
Thanks for creating and supporting this software!

-r
