### ISSUE TITLE
Question: Can credo also just run after macro expansion?

### ISSUE THREAD

**Issue by turion** [rrrene/credo#674]
Assume I have some macro that generates the contents of a module for me:

```
defmodule FooMacro do
  @moduledoc false
  defmacro __using__(args) do
      @moduledoc """
      Automatically generated from args `#{inspect(args)}`.
      """
  end
end

defmodule Foo do
  use FooMacro, [foo: "Foo"]
end
```

Then `credo` will complain about `Foo` not having a `@moduledoc`, although the macro generates one. For example, `mix docs` will correctly create this documentation:

> "Automatically generated from args `[foo: "Foo"]`."

Is anything like this possible for `credo`? I.e. can't `credo` detect that the macro will create the `@moduledoc`?

**Comment by NobbZ** [comment]
How far do you want to expand?

After a full expansion not even `defmodule` and `def` exist anymore…

The only way I see is to either disable the check for the project or the module.

**Comment by turion** [comment]
I don't know what the typical stages are, but e.g. for `mix docs` it does expand `defmacro`, but not `defmodule` and `def`, so I guess about as far as `mix docs` does.

**Comment by NobbZ** [comment]
`ex_docs` doesn't expand anything, it just pretty prints informations that are in the BEAM file after compilation into a nice HTML view.

I really think disabling the check per module is the best you can do.

Credo does not need other modules to be compiled or there source code available at all, this would change once macros gets expanded.

Also, sometimes the expanded macros would then introduce issues credo would complain about, but that you can not change…

In my opinion, expanding macros is a bad idea.

**Comment by turion** [comment]
Ah, I didn't know `ex_docs` worked that way.

Yes, I suspected that there isn't any good resolution by partially expanding some macros. Still, I wanted to at least document the issue.
