### ISSUE TITLE
Proposal: warn if function name contains uppercase letters

### ISSUE THREAD

**Issue by sasa1977** [rrrene/credo#675]
Recently I've encountered a situation in a code review where the author named the function `to_CSV`. This immediately stroke me as unusual/non-idiomatic (see e.g. [Plug.HTML.html_escape](https://hexdocs.pm/plug/Plug.HTML.html#html_escape/1) as a counterexample). After thinking a bit about it, I can't really come up with an example where using uppercase name would be idiomatic, so I thought of writing a credo check. I have a basic first draft (code is available [here](https://gist.github.com/sasa1977/3c39400c4c4e6cc45f41714a0c76f0ee)), and I wanted to see if you'd be interested in moving this check to credo? If so, let me know and I'll prep a PR where we can discuss the details.

**Comment by NobbZ** [comment]
Shouldn't this be handled by https://github.com/rrrene/credo/blob/master/lib/credo/check/readability/function_names.ex?

**Comment by sasa1977** [comment]
Oh, I totally missed that because the error is not reported (I just double checked, and it's indeed not reported). Since credo didn't complain about it, I just assumed that this is not verified. It appears there is a bug in this check, so I'll close this issue and investigate further.

Thanks!

**Comment by sasa1977** [comment]
FYI, I submitted a fix (and a couple of other improvements) in #676
