### ISSUE TITLE
Check "Trailing white-space at end of a line" with Windows

### ISSUE THREAD

**Issue by Nefcairon** [rrrene/credo#698]
### Environment
* Credo version (`mix credo -v`): 1.1.4
* Erlang/Elixir version (`elixir -v`): 1.7.1
* Operating system: Windows 10

### What were you trying to do?

I am running 'mix credo --strict' on my elixir project. I am using Visual Studio Code which saves my files with line endings in Windows style.

### Expected outcome

The check "There should be no trailing white-space at the end of a line" should not tell me my files have trailing whitespaces as they do not have them.

### Actual outcome

The check "There should be no trailing white-space at the end of a line" tells me my files have trailing whitespaces.

Workaround: I can set in Visual Studio Code to save my files with line endings in Linux style. Got this advise from [Elixir Forum](https://elixirforum.com/t/please-help-me-using-credo/). Of course I would rather keep my files with line endings in Windows style as I am using Windows.

**Comment by rrrene** [comment]
This is clearly a problem. Thx for reporting this :+1:
