### ISSUE TITLE
Proposal: warn on Mix.env usage in runtime files

### ISSUE THREAD

**Issue by Odaeus** [rrrene/credo#699]
Hi, I hope this proposal makes sense, I'm relatively new to Elixir!

### Environment

* Credo version (`mix credo -v`): 1.1.4
* Erlang/Elixir version (`elixir -v`): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating system: Ubuntu Linux

### What were you trying to do?

My program failed upon deployment because `Mix.env` was called inside runtime code. This works fine in dev and test environments because Mix is available, as well as in the config during build. So it can cause unexpected failures if Mix is unavailable in production as [recommend](https://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html#environments). It seems like Credo would be a good place to catch such a mistake?

### Expected outcome

Credo emits a warning that `Mix.env` is being used in code where it won't be available at runtime.

### Actual outcome

Credo is silent on the issue.

**Comment by rrrene** [comment]
This seems like a great addition!

**Comment by TheFirstAvenger** [comment]
@Odaeus @rrrene I put together a check that warns on `Mix.env` based on the `IO.inspect` check:

https://github.com/rrrene/credo/pull/721
