### ISSUE TITLE
Incorrect operator detected when used inside a binary

### ISSUE THREAD

**Issue by zackehh** [rrrene/credo#70]
Credo is yelling at me about this (below is an example only):

```elixir
def gen_name(name) when is_binary(name),
do: "#{String.replace_suffix(name, "-test", "")}_name"
```

Invoked as `gen_name("my-test") == "my_name"`.

```
[C] ↗ lib/project/text.ex:155:40 There are spaces around operators most of the time, but not here.
```

Assuming that it's looking at the `-` in the binary and getting mad that there are no spaces, but naturally I can't add spaces because that would change the output.

I can disable, sure, just reporting in case this is a bug which needs fixing.

**Comment by rrrene** [comment]
Ouch, this definitely looks like a bug. Thx for reporting! :+1:

**Comment by rrrene** [comment]
@zackehh Could you re-test this using `v0.4.0-beta1`?

**Comment by zackehh** [comment]
@rrrene perfect, works just fine :)

**Comment by rrrene** [comment]
@zackehh Great. Thx for reporting! :+1:
