### ISSUE TITLE
Time consumed by AliasUsage seems to be exponential

### ISSUE THREAD

**Issue by lasseebert** [rrrene/credo#702]
### Environment

* Credo version (`mix credo -v`): 1.1.4
* Erlang/Elixir version (`elixir -v`): Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Operating system: Ubuntu

### What were you trying to do?

`mix credo` a large test file of around 4,000 lines

### Expected outcome

Be done in around a second

### Actual outcome

It took 65 seconds

### Minimal example

I have reproduced the issue with this:

```elixir
# some_file.ex
defmodule AliasTest do
  def test do
    [
      :a,
      :a,
      :a,
      # Add 1000 or 2000 lines here with :a 
    ]
    Any.Thing.test()
  end
end
```

Running `mix credo some_file.ex` with AliasUsage enabled in config now takes a long time.

I have tried to debug the AliasUsage code, but I can not figure out where the problem is.

**Comment by NobbZ** [comment]
I'm not sure if this is related, but what I realised quickly was, that there have been at least two occurences of `list_passed_into_function ++ new_items`.

This is a clear danger sign to me.

**Comment by rrrene** [comment]
@lasseebert @NobbZ Ouch. Could you try my fix as described in #704? Thx for reporting! 👍

**Comment by lasseebert** [comment]
@rrrene 

I have measurered the wall time spent in my project with AliasUsage enabled:

Time spent in 1.1.4: 53s474
Time spent in fix branch: 3s405

:tada: Good job! 

By the way:
When updating credo with mix `deps.get` or mix `deps.update` and then run `mix credo`, it runs on the old (previously compiled) version. I need to explicitly `mix deps.compile credo` to use the updated version if it was not compiled for any other reason, e.g. `mix test` or `iex -S mix`.
Is this expected behaviour?

**Comment by rrrene** [comment]
> I need to explicitly `mix deps.compile credo` to use the updated version if it was not compiled for any other reason, e.g. `mix test` or `iex -S mix`.
> Is this expected behaviour?

I think this is a Hex thing. I also have to do this when I use deps locally with the `path:` keyword.

I will clean up the branch with the fix and release a patch soon. :+1:
