### ISSUE TITLE
credo should also check *.exs files in the test folders, of umbrella apps

### ISSUE THREAD

**Issue by bbtdev** [rrrene/credo#719]
Hi,

So I have an umbrella app, and I would like to have credo check the test files as well. What am I suppose to add in the config, to make this work?
 included: ["apps/"],
 excluded: ["_build/", "deps/"]

Considering the test folders are in their respective apps folder.

**Comment by TheFirstAvenger** [comment]
@bbtdev What check is not succeeding? I just verified in a test .exs in our umbrella that a `String.to_atom` threw a credo warning. We are using the default config:
https://github.com/rrrene/credo/blob/master/.credo.exs#L24-L25

**Comment by TheFirstAvenger** [comment]
@bbtdev could you let us know which check you had that wasn't succeeding for you?

**Comment by TheFirstAvenger** [comment]
@rrrene I recommend closing this one until more information is provided.
