### ISSUE TITLE
@lint rules ignores macros

### ISSUE THREAD

**Issue by tomekowal** [rrrene/credo#73]
I am using Credo with Phoenix application and I have two models that have the same fields and validations, but different semantics. For example:
    
      @lint {Credo.Check.Design.DuplicatedCode, false} #this doesn't work
      embedded_schema do
        field :field1, :integer
        field :field2
        field :field3
      end

      @required_fields [:field1, :field2, :field3]
      @optional_fields []

      @lint {Credo.Check.Design.DuplicatedCode, false} #this works fine
      def changeset(model, params \\ :empty) do
        model
        |> cast(params, @required_fields, @optional_fields)
        |> validate_number(:field1, greater_than_or_equal_to: 0)
      end

In the near future the two models will probably have different fields, so I want to keep them separate. The `@lint` attribute works fine with a function, but it doesn't work for macros.
It would be great if there was possibility to disable duplicated code check for macros the same way as for functions.

**Comment by rrrene** [comment]
Thx for reporting! :+1: We briefly talked at ElixirConf, right?

**Comment by tomekowal** [comment]
That is right :) Nice event and I really enjoyed your talk :)

**Comment by rrrene** [comment]
Thanks! I also enjoyed the conference very much. Such a great community.

**Comment by rrrene** [comment]
Just released `v0.4.0-beta5`. 

Some notable changes to the duplicate code detection:

- The minimal mass was increased from 16 to 40 (an unscientific study of elixir codebases yielded a mean of 30 with a stddev of 20 in reported DuplicatedCode issues, so I followed my gut in picking 40)
- `@lint` should now work on macros.
- You can now additionally configure DuplicatedCode with a `excluded_macros` parameter to exclude e.g. the `embedded_schema` macro by default (so you don't have to anntotate them all with `@lint`).

An example configuration could be:

        {Credo.Check.Design.DuplicatedCode, excluded_macros: [:embedded_schema, :schema, :setup, :test]},
