### ISSUE TITLE
Credo 1.2 still giving bad results in VS code:  File is using windows line endings while most of the files use unix line endings.

### ISSUE THREAD

**Issue by zaherh8** [rrrene/credo#741]
### Precheck

* Proposals for new features should be submitted via: https://github.com/rrrene/credo-proposals
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`):
* Erlang/Elixir version (`elixir -v`):
* Operating system:

**Comment by AkhileshNegi** [comment]
@zaherh8 @rrrene I'm still getting this error. 

- Credo version (mix credo -v): 1.4
- Erlang/Elixir version (elixir -v): Erlang/OTP 21 [erts-10.3] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
- Operating system: OSX 10.10.5

![image](https://user-images.githubusercontent.com/40158831/100243230-ab747e80-2f5b-11eb-8fac-b719d5cd2c93.png)

**Comment by rrrene** [comment]
This comes up from time to time and in 100% of the cases, the error had something to do with the files/encoding/line endings.

Can you make sure that the files in question do not use unix-style line endings?
