### ISSUE TITLE
Credo 1.2.1 still giving bad results in VS code.File is using windows line endings while most of the files use unix line endings.

### ISSUE THREAD

**Issue by zaherh8** [rrrene/credo#742]
### Precheck

* Proposals for new features should be submitted via: https://github.com/rrrene/credo-proposals
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 1.2.1
* Erlang/Elixir version (`elixir -v`):1.8.2
* Operating system:
Windows 10
### What were you trying to do?
mix credo --strict

### Actual outcome

File is using windows line endings while most of the files use unix line endings.
in a another issue you mentioned that this issue is fixed in the newest version of credo however I am still encountering the issue in this version(1.2.1).

**Comment by TheFirstAvenger** [comment]
@zaher8 Do you have an example repo that I can pull down to reproduce this?

**Comment by zaherh8** [comment]
I solved this using the "mix format" command. It happened when I switched OS from Unix to windows. 
@TheFirstAvenger thank you for trying.

**Comment by rrrene** [comment]
@zaherh8 Glad this got sorted out!
