### ISSUE TITLE
Excluding type of check globally

### ISSUE THREAD

**Issue by leifg** [rrrene/credo#75]
Is there a way to run the checks that are configured by default and exclude checks that should not be run.

From the documentation I see only the possibility to explicitly specify which checks can be run (so I have to copy all the default checks and then delete the ones I don't want)

**Comment by rrrene** [comment]
Hi,

two ways: 

1. Use `--ignore <check-name-or-part-of-checkname>` from the command-line.
2. Wait until tonight, I will release a beta for Credo `v0.4.0` which contains a breaking change that will enable you to do precisely what you want. See the [preliminary CHANGELOG](https://github.com/rrrene/credo/blob/release-0.4.0/CHANGELOG.md#breaking-change-checks-listed-in-credoexs) for details.

**Comment by rrrene** [comment]
`v0.4.0-beta1` is available now.

**Comment by leifg** [comment]
That was perfect timing. Thanks a lot will try it out ASAP.

**Comment by leifg** [comment]
Works like a charm. This ticket can be closed.

**Comment by rrrene** [comment]
:+1:
