### ISSUE TITLE
Unable to find configuration options for 'Function body is nested too deep'

### ISSUE THREAD

**Issue by cantiero** [rrrene/credo#751]
### Environment
* Credo version (`mix credo -v`): 1.2.2
* Erlang/Elixir version (`elixir -v`): 1.9.1
* Operating system: Mac Os

### What were you trying to do?
Disable or change the rule that outputs "Function body is nested too deep".

### Expected outcome
Change max depth from 2 to 3 or disable this rule.

### Actual outcome
Not being able to do so.

I could not find anywhere how to change configuration for this specific case in .credo.exs.

Suggestion: maybe create a dictionary that links all messages with their respective NAME_OF_CONFIG and configuration options. If this already exists, I could not find it in the docs or issues.

**Comment by rrrene** [comment]
You can use `mix explain <location-of-issue>` to get the options, but you are of course right: This is not very user friendly and we should definitely improve it :+1:

Thx for reporting!

**Comment by cantiero** [comment]
Got it. Thank you!
