### ISSUE TITLE
Ambiguous aliases

### ISSUE THREAD

**Issue by TBK145** [rrrene/credo#76]
When using credo with the `--strict` parameter, it will suggest you alias modules. However, if you use `Foo.Bar` and `Baz.Bar` in the same module, maybe credo should not suggest aliasing, because it will result in an ambiguous alias.

**Comment by rrrene** [comment]
Ouch, this should have been fixed in #35 - I guess we missed a case.

Can you provide a small code example which I can include in a test?

**Comment by TBK145** [comment]
(Just to be sure, I'm using the master branch)

This is the specific piece of code:
```
Switch.Uri.parse Sip.Uri.generate!(uri)
```

**Comment by rrrene** [comment]
Very good. `master` contains the current stable version (`v0.3.13`).

What we did fix back in February was this (where you aliased one of the alternatives). 

```elixir
defmodule Test do
  alias Switch.Uri

  def just_an_example do
    Uri.parse Sip.Uri.generate!(uri)
  end
end
```

I will try to fix your case as well! :+1:

**Comment by TBK145** [comment]
I could fix it as well by aliasing one of the two, however, I think in cases like this it is clearer to not alias the parent module.

**Comment by rrrene** [comment]
Totally agree.

**Comment by TBK145** [comment]
Also, maybe a bit unrelated, but if a module is only called once, would it really be better practice to alias it?

**Comment by rrrene** [comment]
The reason for the aliases (and there are different opinions about this) is to have all "module dependencies" at the top of your module. This way, you can spot what the relations between modules are. For example you could see 

> Oh crap, I am calling a database module from inside my view module. That can't be right!

I certainly spotted design flaws in my code using this method.

However: It is a check in the "Software Design" category, which are all a bit controversial and YMMV. Never let a tool dictate your coding style. Always be skeptical of tools, including Credo :wink:

**Comment by TBK145** [comment]
Of course, and that relations between modules is indeed a good point. I thought it was more a message to prevent code duplication.

**Comment by rrrene** [comment]
Credo `v0.4.8` was just released and contains the fix. Big thanks to @DavydenkovM :+1:
