### ISSUE TITLE
Can't use StrictModuleLayout

### ISSUE THREAD

**Issue by doughsay** [rrrene/credo#764]
### Environment

* Credo version (`mix credo -v`): 1.3.0
* Erlang/Elixir version (`elixir -v`): 1.10.2
* Operating system: Linux 5.5.8

### What were you trying to do?

Changed credo config from:

```elixir
{Credo.Check.Readability.StrictModuleLayout, false}
```

to:

```elixir
{Credo.Check.Readability.StrictModuleLayout, []}
```

### Expected outcome

It yells at me a lot for inconsistent modules.

### Actual outcome

** (UndefinedFunctionError) function Credo.Check.Readability.StrictModuleLayout.run/3 is undefined or private

**Comment by rrrene** [comment]
Ouch! Fix in `v1.3.1`. Thx for reporting! :+1:
