### ISSUE TITLE
problem with {Credo.Check.Readability.ParenthesesOnZeroArityDefs, parens: true} and special chars

### ISSUE THREAD

**Issue by jlgeering** [rrrene/credo#765]
### Environment

* Credo version (`mix credo -v`): 1.3.1
* Erlang/Elixir version (`elixir -v`): 1.10.2 (compiled with Erlang/OTP 22)
* Operating system: macOS

### What were you trying to do?

run `mix credo` with `{Credo.Check.Readability.ParenthesesOnZeroArityDefs, parens: true}` in config, with the following function defs:

```
def good?() do
  :ok
end

def bang!() do
  :nok
end
```

### Expected outcome

should pass

### Actual outcome

`[R] ↘ Use parentheses () when defining a function which has no arguments.`

**Comment by rrrene** [comment]
The fix for this is part of Credo `v1.3.2`. Thx for reporting it!

**Comment by NickNeck** [comment]
Hello,

I have still this problem with the following code:
```
  def foo!, do: impl().foo!()
  def foo?, do: impl().foo?()
```
```
$> mix credo -v         
1.3.2
```

**Comment by rrrene** [comment]
@NickNeck should be fixed in `1.4.0-rc.1`. Could you check?

**Comment by NickNeck** [comment]
@rrrene everything works fine again. Thank you.

**Comment by jlgeering** [comment]
thx

**Comment by rrrene** [comment]
@NickNeck @jlgeering Thank you for reporting these glitches. This project would not work without your contributions! :+1:
