### ISSUE TITLE
"Variable names should be written in snake_case" alerting for "latency_μs"

### ISSUE THREAD

**Issue by thiagogsr** [rrrene/credo#766]
### Precheck

* Proposals for new features should be submitted via: https://github.com/rrrene/credo-proposals
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 1.3.1
* Erlang/Elixir version (`elixir -v`): 1.10.1
* Operating system: Ubuntu 18

### What were you trying to do?
Credo is alerting for code readability issue when the variable name is "latency_μs":

> [R] ↗ Variable names should be written in snake_case.

### Expected outcome
The variable is snake case, I don't expect warnings.

### Actual outcome
Credo is alerting for a variable already snake_case.

**Comment by rrrene** [comment]
The fix for this is part of Credo `v1.3.2`. Thx for reporting it!
