### ISSUE TITLE
"trailing white-space at the end of a line" issue on comments  

### ISSUE THREAD

**Issue by floodico** [rrrene/credo#772]
### Environment

* Credo version (`mix credo -v`): 1.3.2
* Erlang/Elixir version (`elixir -v`): Elixir 1.10.2 (compiled with Erlang/OTP 21)
* Operating system: Ubuntu 18.04.4 LTS

### What were you trying to do?
I have some lines of comments in my module. 
![2020-04-21 18 25 56](https://user-images.githubusercontent.com/12949777/79885120-eed3a100-83fe-11ea-8392-8042ac4a145f.jpg)
 When i run `mix credo --strict`, i get some code readability issues

### Expected outcome
Just nothing.

### Actual outcome
<img width="708" alt="Screenshot 2020-04-21 at 18 10 12" src="https://user-images.githubusercontent.com/12949777/79886110-e0868480-8400-11ea-9ae0-6e95f0370629.png">

**Comment by rrrene** [comment]
Thx for reporting! :+1:

I've tried reproducing this in 03879f4 but was unsuccessful so far.

**Comment by floodico** [comment]
@rrrene, actually it's my fail. I had some "." characters in my comments, but I don't see it in my VSCode editor, just through Vim. So i needed to clean that.
<img width="838" alt="Screenshot 2020-04-23 at 17 37 06" src="https://user-images.githubusercontent.com/12949777/80112992-66820700-858a-11ea-9b0b-5d672cf49211.png">

Now it works as expected. Very thankful for your response
