### ISSUE TITLE
Error "Cond statements should contain at least two conditions" while there are two conditions

### ISSUE THREAD

**Issue by aripovula** [rrrene/credo#776]
### Precheck

* Proposals for new features should be submitted via: https://github.com/rrrene/credo-proposals
* For bugs, please do a quick search and make sure the bug has not yet been reported here

I do not know if this is an error.
I have this code:

`
cond do
      is_asc == true ->
        Repo.all(
          from u in LPEvent,
            order_by: [asc: ^field],
            offset: ^((current_page - 1) * per_page),
            limit: ^per_page
        )

      is_asc == false ->
        Repo.all(
          from u in LPEvent,
            order_by: [desc: ^field],
            offset: ^((current_page - 1) * per_page),
            limit: ^per_page
        )
    end
`

I get error "Cond statements should contain at least two conditions besides `true`, consider using `if`  instead."

### Environment

* Credo version (`mix credo -v`):
* Erlang/Elixir version (`elixir -v`):
* Operating system:

**Comment by rrrene** [comment]
@aripovula I'll close this. If you have any more questions, please ask!
