### ISSUE TITLE
Doesn't catch parentheses around a condition, which seems to hide other issues

### ISSUE THREAD

**Issue by stevelove** [rrrene/credo#78]
Saw the following during a code review and was surprised that Credo found no issues:

    if (!some_condition) do
      # ...
    else
      # ...
    end

Given the code above, I would expect:
1. An issue to be raised about parentheses around the condition;
2. "If/else blocks should not have a negated condition in `if`" to be raised.

Actual results were that Credo reported no issues.

If it matters, I'm using Credo 0.4.0-beta1 with Elixir 1.2.3.

**Comment by rrrene** [comment]
Strange. "If/else blocks should not have a negated condition in `if`" should be raised.

Will investigate!

**Comment by stevelove** [comment]
Thanks for the fix!

I am curious about the reason for not raising a Code Readability warning for the parentheses themselves. The last bullet for that section in Credo's style guide says the following:
<blockquote>
Conclusively, never use parentheses around the condition of if or unless (since they are macros as well).
</blockquote>
    # preferred way
    if valid?(username) do
      # ...
    end

    # NOT okay
    if( valid?(username) ) do
      # ...
    end

Does this rule only apply to `if( valid?(username) )` and not `if (valid?(username))`?

**Comment by rrrene** [comment]
Hi. You are right. The reason Credo does not raise an issue here is that I simply haven't implemented all the points from the style guide yet.

I tried to acknowledge this in the commit referenced above:

> Fixes part of #78

Let's keep this issue open until it is fully fixed! :+1:

**Comment by stevelove** [comment]
Ah, I missed that. My mistake. Would you like help with the rest of the issue? I'm new to Elixir, but would be happy to take a look.

**Comment by rrrene** [comment]
Absolutely. Be sure to branch from the `release-0.4.0` branch.

**Comment by rrrene** [comment]
FYI: You can use [Credo.Check.Refactor.NegatedConditionsWithElse](https://github.com/rrrene/credo/blob/release-0.4.0/lib/credo/check/refactor/negated_conditions_with_else.ex) as a template (here you can see how to parse `if` statements and it also checks for parentheses in conditions).

Please put the new check in the Readability category. Name could be something like `ParenthesesInCondition` ... or something better ... I am not a native speaker :wink:

**Comment by stevelove** [comment]
`ParenthesesInCondition` seems like a reasonable name to me. I hope to get started on this soon.

**Comment by stevelove** [comment]
I finally found some time to take [a stab at implementing this here](https://github.com/stevelove/credo/commit/5637fa76402925c723683cc075c16edaaab889cf).

A few notes and questions:

- I know Credo has been updated since this issue was opened, but I still branched from `release-0.4.0` just in case. Should I use a different branch now?
- You mentioned putting the new check in Readability, but I found some existing tests for `ParenthesesInCondition` in [Credo.Check.Refactor.ParenthesesInConditionTest](https://github.com/rrrene/credo/blob/release-0.4.0/test/credo/check/refactor/parentheses_in_condition_test.exs). For now, I used those tests and put the new check in the corresponding Refactor. Would you like me to move them all? Otherwise, I will update the `@moduledoc`.
- It seems like `Macro.prewalk` used by `Credo.Code.traverse` does not wrap parenthetical conditions in a `__block__` unless the condition is negated, so I ended up using `Credo.Code.to_tokens` following the large numbers check in my implementation. Let me know if I missed something in the way you suggested that would be better.

**Comment by rrrene** [comment]
Great :)

* The new edge branch is now `master`. I think it was a bad idea on my part to use special release branches in this project. So from now on `master` will be the right branch. always.
* Adding the test in `Refactor` was an error. Please move the test and check to the `Readability` namespace.
* Using `to_tokens` is exactly right! :+1:

Also, let's change the Issue message to 

> The condition of `if` or `unless` should not be wrapped in parentheses.

Thanks for taking the time to work on this. :smile:

**Comment by stevelove** [comment]
I use Credo every day, so I'm glad to help out. 😄
