### ISSUE TITLE
Name redeclaration checks only for 0-arity functions

### ISSUE THREAD

**Issue by michalmuskala** [rrrene/credo#79]
I find it quite strict to apply this rule to every function from `Kernel` or every local function.
I think it's perfectly fine to have a variable called `struct`, since the `Kernel.struct/2` function expects two arguments and can never be confused with a simple `struct` variable - be it by the compiler or humans (although I'm not so sure here).

I can see how this check could be desirable, so I'm not asking to change it all together. I'd love to see ability to configure it to only issue warnings for functions with 0 arity, though.

If you agree I can work on that.

**Comment by rrrene** [comment]
Yep, that is the goal for 0.4.0 ([partially related discussion](https://github.com/rrrene/credo/issues/74)) - if you want to give it a shot, please branch from `release-0.4.0` :heart: :purple_heart: :green_heart: :yellow_heart: :blue_heart:

**Comment by michalmuskala** [comment]
I'm sorry I totally missed the other issue. My searching skills failed me.

I'll close this one in favour of the other and work on the implementation in the meantime.

**Comment by philipgiuliani** [comment]
Cool that you work on that @michalmuskala ! :)
