### ISSUE TITLE
CLI --ignore is ignoring everything when there's a space after the comma

### ISSUE THREAD

**Issue by leandrocp** [rrrene/credo#799]
### Environment

* Credo version (`mix credo -v`): 1.4.0
* Erlang/Elixir version (`elixir -v`): Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:12:12 [ds:12:12:10] [async-threads:1] [hipe] / Elixir 1.10.3 (compiled with Erlang/OTP 22)
* Operating system: macOS 10.15.16 and also on cimg/elixir:1.10.1 (running on CI)

### What were you trying to do?

Running `mix credo --strict --ignore Credo.Check.Readability.MaxLineLength, Credo.Check.Consistency.SpaceAroundOperators`

### Expected outcome

To ignore _only_ those 2 checks _or_ warn that the list of checks should be separated _without_ spaces between them.

### Actual outcome

Looks like it's ignoring _everything_. It runs pretty fast and return exit status 0

### More details

Running as `mix credo --strict --ignore Credo.Check.Readability.MaxLineLength,Credo.Check.Consistency.SpaceAroundOperators` works as expected. The only difference is removing the space after `,` between those 2 checks.

I'm aware that [docs example](https://hexdocs.pm/credo/cli_switches.html#ignore-some-checks) is `mix credo --ignore readability,duplicated` (no space after comma) and shell options should be enclosed, but turns out it's easy to make this mistake :)

**Comment by rrrene** [comment]
This is an interesting point. From a user's perspective it is hard to tell what's going on here.

While we won't be able to change the shell's parsing of the arguments, we can certainly do a better job of highlighting undesirable results.

I added a first iteration validation on `master`. :+1:

**Comment by leandrocp** [comment]
Thanks for the quick response @rrrene

**Comment by rrrene** [comment]
The mentioned improvements are now live in Credo `v1.5.0`. Thanks for highlighting this issue!
