### ISSUE TITLE
compilation error on the release-0.4.0 branch

### ISSUE THREAD

**Issue by karmajunkie** [rrrene/credo#81]
Compiling the project on the `release-0.4.0` branch, I get the following error:

```
== Compilation error on file lib/credo/cli.ex ==
lib/credo/cli/command/suggest.ex:1: warning: redefining module Credo.CLI.Command.Suggest
** (CompileError) lib/credo/cli.ex:90: unknown key :requires for struct Credo.Config
    (elixir) src/elixir_map.erl:185: :elixir_map."-assert_struct_keys/5-lc$^0/1-0-"/5
    (elixir) src/elixir_map.erl:62: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

The commit this branch is currently on for me is 14b3130171fbb6fdfb398ba234e8d8f5eac578a3.

**Comment by rrrene** [comment]
hI @karmajunkie, 

do you have Credo installed as an archive as well? If you installed it via `mix archive.install` to use it as a standalone script, you have to uninstall it to compile another version of it (Credo that is).

**Comment by karmajunkie** [comment]
This may be the problem, will check it out and get back to you!

**Comment by karmajunkie** [comment]
That fixed it, thanks!

**Comment by rrrene** [comment]
No problem :+1:

If find anything, do not hesitate to open an issue. This project thrives on feedback from the community :grin:
