### ISSUE TITLE
1.5.0 tag missing on Github

### ISSUE THREAD

**Issue by ruudk** [rrrene/credo#818]
I see that 1.5.0 is released on [Hex](https://hex.pm/packages/credo/1.5.0) but it's not tagged on [Github](https://github.com/rrrene/credo/tags).

**Comment by rrrene** [comment]
Oh no. Seems like I forgot to push it last night. Will do as soon as I get home! 👍

**Comment by rrrene** [comment]
The `Bump version to 1.5.0` commit is also missing ... Seems like I dropped the ball and did not push anything yesterday. 🤦

**Comment by rrrene** [comment]
Done. Thy formthe heads up!

**Comment by ruudk** [comment]
Thanks!

Might be good to automate this whole flow, maybe there are GitHub actions for publishing to hex and tagging to GitHub.
