### ISSUE TITLE
Should `?(` be exempt from the space after ( consistency check?

### ISSUE THREAD

**Issue by mikestok** [rrrene/credo#82]
I have a piece of code which processes a character list counting up when it meets a `(` and counting down when it meets a `)`.  In the following code the second line gets a consistency comment: `There is no whitespace around parentheses/brackets most of the time, but here there is.`

```
  defp count([], acc), do: acc
  defp count([?( | t], acc), do: count(t, acc + 1)
  defp count([?) | t], acc), do: count(t, acc - 1)
```

I think that in this case the `(` shouldn't be considered as an opening parenthesis as `?(` is a cleaner alternative to `hd('(')` (at least to my Ruby-seasoned eyes).

**Comment by rrrene** [comment]
Absolutely a bug. Will have a look at it tonight! Thx for reporting! :+1:

**Comment by rrrene** [comment]
@mikestok `0.4.0-beta3` should solve this problem. could you check? :shipit:

**Comment by mikestok** [comment]
`0.4.0-beta3` works for me :-) Thanks.
