### ISSUE TITLE
Ignoring checks per directory

### ISSUE THREAD

**Issue by lleger** [rrrene/credo#820]
Is it possible to ignore some checks for an entire directory?

For example: `Credo.Check.Readability.Specs` I'd like on for most of the project, but off for the Phoenix code in `my_app_web/`. Is it possible to ignore all files in that folder?

It seems like some checks have options to ignore things, but that check has no parameters.

I know you can turn the check off for individual files with the inline comments, but I'd like to avoid adding a comment to each file, if possible.

I tried by adding a `.credo.exs` to `my_app_web/` but it sounds like Credo only traverses upward, so it ignored that file.

**Comment by rrrene** [comment]
This is possible since Credo 1.5 via the `:files` param for checks: https://hexdocs.pm/credo/config_file.html

**Comment by lleger** [comment]
Apologies, I figured it was a thing, but didn't see it in the docs! Thanks I'll give this a shot.

**Comment by rrrene** [comment]
Absolutely no problem. I updated [the documentation](https://github.com/rrrene/credo/blob/c4f78a6b1ecc0e5a8994b2f9c0f6c340ecced383/guides/configuration/check_params.md#files) based on your feedback! Will go live on hexdocs with the next patch update.

Thx again! :+1:

**Comment by lleger** [comment]
@rrrene Thanks for the updated docs! I'm wondering, however, if I'm using it wrong.

```
$ mix credo --version
1.5.0
```

```
# .credo.exs
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["*.exs", "config/", "lib/", "priv/", "test/"],
        excluded: []
      },
      checks: [
        {Credo.Check.Readability.Specs, files: %{excluded: ["mix.exs"]}}
      ]
    }
  ]
}
```

But when I run `mix credo`:

```
┃ [R] → Functions should have a @spec type specification.
┃       mix.exs:22:7 #(PhoenixStarter.MixProject.application)
┃ [R] → Functions should have a @spec type specification.
┃       mix.exs:4:7 #(PhoenixStarter.MixProject.project)
```

It seems like it's ignoring the config. Am I doing it wrong?

**Comment by lleger** [comment]
Ok, I think I understand now. I was doing it wrong! In case it helps anyone else, here's my understanding of how it works.

`excluded` and `included` at the check-level filter against each other. The resulting list of files is filtered out of the top-level `files` config.

Setting `excluded` at the check-level won't filter out a file from that check. You have to specify an `included` that doesn't include the files you want. 

In my case, to exclude Phoenix files from the Spec check, I had to instead specify `include` (which is what confused me).

```elixir
# .credo.exs
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["*.exs", "config/", "lib/", "priv/", "test/"],
        excluded: []
      },
      checks: [
        {Credo.Check.Readability.Specs, files: %{included: ["lib/myapp/**/*.ex"]}}
      ]
    }
  ]
}
```

@rrrene Of course please correct me if I'm wrong! 😅

**Comment by rrrene** [comment]
@lleger This is a bug. Thanks for clarifying, this is supposed to work:

```
# .credo.exs
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["*.exs", "config/", "lib/", "priv/", "test/"],
        excluded: []
      },
      checks: [
        {Credo.Check.Readability.Specs, files: %{excluded: ["mix.exs"]}}
      ]
    }
  ]
}
```

I'll look into it after work. 👍

**Comment by rrrene** [comment]
It should now be fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by lleger** [comment]
@rrrene Confirming that master fixes the bug for me! 👏

**Comment by rrrene** [comment]
This is now live in `v1.5.1`. Thx for reporting!

**Comment by lleger** [comment]
Thanks for the quick fix @rrrene!
