### ISSUE TITLE
Credo.Check.Refactor.CyclomaticComplexity: not expected "function is too complex"

### ISSUE THREAD

**Issue by felipelincoln** [rrrene/credo#823]
### Not expected outcome
![image](https://user-images.githubusercontent.com/37600416/98865104-ac7cba80-2449-11eb-8f5c-bee6d0e524d4.png)

### Environment

* Credo version (`mix credo -v`): 1.4.0
* Erlang/Elixir version (`elixir -v`): Elixir 1.10.4 (compiled with Erlang/OTP 22)
* Operating system: docker image elixir:1.10.4-alpine

### What were you trying to do?
I'm using this function. I don't undestand nothing about cyclomatic complexity and this function below is resulting in `cc = 13`
![image](https://user-images.githubusercontent.com/37600416/98866105-31b49f00-244b-11eb-9e95-bb79b506ce1d.png)

### Expected outcome
No warnings
### Actual outcome
![image](https://user-images.githubusercontent.com/37600416/98865104-ac7cba80-2449-11eb-8f5c-bee6d0e524d4.png)

**Comment by w-sanches** [comment]
[This test for the CyclomaticComplexity module](https://github.com/rrrene/credo/blob/master/test/credo/check/refactor/cyclomatic_complexity_test.exs#L51-L64) might help you understand why this is the outcome.
Check the comment in the test showing the composition of the result.

What this check does is basically adding "points" to some operations [as defined in the module itself](https://github.com/rrrene/credo/blob/master/lib/credo/check/refactor/cyclomatic_complexity.ex#L24-L38).
In your case credo is calculating one point for the function definition and another point for each of the twelve case conditions, resulting in 13 points.

You can either refactor the code to avoid using so many conditions inside a case statement or use [inline comments](https://hexdocs.pm/credo/config_comments.html) to disable credo for this specific funciton/file.

**Comment by felipelincoln** [comment]
thank you for the explanation!
Any idea on refactoring this code?

**Comment by w-sanches** [comment]
A possible alternative would be to create a list with all month names and call `Enum.at(months, n - 1)` to get the month in nth position as list index starts with 0.

**Comment by felipelincoln** [comment]
Perfect!
Alright, I though it was a bug with credo for raising a warning on this code but I am convinced that 12 conditions in a case statement are complex enough to be refactored. Thanks a lot @w-sanches :tada:
