### ISSUE TITLE
deps folder gets linted in umbrella project

### ISSUE THREAD

**Issue by almasakchabayev** [rrrene/credo#85]
Hi I have installed credo from master into the root of an umbrella app. When running `mix credo --ignore Consistency` it linted
`3640 mods/funs, found 1081 warnings, 563 refactoring opportunities, 261 code readability issues, 88 software design suggestions.`

most of which look like
`apps/typi/deps/postgrex/lib/postgrex/extensions/numeric.ex:103:50 (Postgrex.Extensions.Numeric.decode_numeric)`

**Comment by rrrene** [comment]
Hi Almas,

this will be fixed in `v0.4.0`. 

Could you re-try with Credo `0.4.0-beta2` to see if it works for you?

**Comment by almasakchabayev** [comment]
It did work thanks :)
