### ISSUE TITLE
mix credo explain fails to display priority correctly 

### ISSUE THREAD

**Issue by spencerdcarlson** [rrrene/credo#854]
### Environment

* Credo version (`mix credo -v`): 
```bash
spencercarlson$ mix credo -v
1.5.5-ref.sdc/sql-adapter.8d624bed6+uncommittedchanges
```
* Erlang/Elixir version (`elixir -v`):
```bash
  $ elixir -v
Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
```
* Operating system:
```bash
spencercarlson$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H114
```

### What were you trying to do?
Execute `mix credo explain Credo.Check.Readability.MaxLineLength`

### Expected outcome
Priority should display a down arrow and low

### Actual outcome
Priority displays ?
<img width="813" alt="before" src="https://user-images.githubusercontent.com/1206303/109349286-f17b0000-7832-11eb-8f3d-135ee4cbafd8.png">

**Comment by spencerdcarlson** [comment]
I created https://github.com/rrrene/credo/pull/853 to address this issue

**Comment by rrrene** [comment]
Closing due to "this has been merged and I forgot to close the issue". Please re-open at your convenience :+1:
