### ISSUE TITLE
Actual module not alphabetically ordered not mentioned

### ISSUE THREAD

**Issue by lobo-tuerto** [rrrene/credo#857]
### Environment

* Credo version (`mix credo -v`): 1.5.5-ref.master.6e9dc6c+uncommittedchanges
* Erlang/Elixir version (`elixir -v`): Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Operating system: Manjaro Linux

### What were you trying to do?

```elixir
alias Surface.Components.Form
alias Surface.Components.Form.{DateInput, TextInput, TextArea}
```

### Expected outcome

I expected it to mention that `Surface.Components.Form.TextArea` is not alphabetically ordered,
not `Surface.Components.Form`.

I wonder if this is easy or possible at all.

### Actual outcome

```text
  Code Readability
┃ 
┃ [R] ↘ The alias `Surface.Components.Form` is not alphabetically ordered among its group.
┃       lib/my_web/live/pages/my_page.ex:9:9 #(MyWeb.MyPage)
```

The alias `Surface.Components.Form` is not alphabetically ordered among its group.
Which threw me there a little bit because of the double `Surface.Components.Form` declaration.

**Comment by rrrene** [comment]
You are right. This is clearly a UX bug. :+1:

**Comment by panoramix360** [comment]
Hello @rrrene! I was looking for an issue to help in the project as I study more and more about Elixir, I choose this issue because it appeared to be simple to resolve, but after some search in the code, I noticed that you already fixed this problem, am I correct?

**Comment by rrrene** [comment]
@panoramix360  Hi, yeah, sorry for being so unresponsive.

@lobo-tuerto  Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by lobo-tuerto** [comment]
@rrrene Issue was addressed sucessfully :)
Thank you!

```text
[R] ↘ The alias `Surface.Components.Form.TextInput` is not alphabetically ordered among its group.
┃       lib/my_web/live/pages/my_page.ex:9:45 #(MyWeb.MyPage)
```

**Comment by rrrene** [comment]
This is part of v1.6.1 💚
