### ISSUE TITLE
StrictModuleLayout check not included after enabling

### ISSUE THREAD

**Issue by florish** [rrrene/credo#862]
### Environment

* Credo version (`mix credo -v`): 1.5.5-ref.master.06722e2+uncommittedchanges
* Erlang/Elixir version (`elixir -v`): Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Operating system: macOS Catalina 10.15.7

### What were you trying to do?

I wanted to enable the `Credo.Check.Readability.StrictModuleLayout` check for my project.

After doing so in `.credo.exs` as follows:

```
-170 {Credo.Check.Readability.StrictModuleLayout, false}, 
+170 {Credo.Check.Readability.StrictModuleLayout, []},
```

The check does not seem to be included when running `mix credo`.

### Expected outcome

I expected to see "running 46 checks" instead of the default "running 45 checks" after enabling `StrictModuleLayout` in `.credo.exs`.

### Actual outcome

Prerequisites:

```
$ mix new strict_module_layout
$ cd strict_module_layout
# Add `:credo` to `deps` in mix.exs...
$ mix deps.get
```

Running credo:

```
$ mix credo
Checking 3 source files ...

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.1 seconds (0.07s to load, 0.03s running 45 checks on 3 files)
3 mods/funs, found no issues.

Showing priority issues: ↑ ↗ →  (use `mix credo explain` to explain issues, `mix credo --help` for options).
$ mix credo gen.config
* creating .credo.exs
```

Then after enabling `StrictModuleLayout` on line 170 in the generated `.credo.exs` file:

```
$ mix credo
Checking 3 source files ...

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.1 seconds (0.07s to load, 0.04s running 45 checks on 3 files)
3 mods/funs, found no issues.
```

Af you can see, the number of checks remains the same.

After enabling `Credo.Check.Readability.Specs` (one of the other "controversial" checks listed), I do see different output:

```
$ mix credo
Checking 3 source files ...

  Code Readability                                                                                                      
┃ 
┃ [R] → Functions should have a @spec type specification.
┃       lib/strict_module_layout.ex:15:7 #(StrictModuleLayout.hello)

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.1 seconds (0.07s to load, 0.06s running 46 checks on 3 files)
3 mods/funs, found 1 code readability issue.

Showing priority issues: ↑ ↗ →  (use `mix credo explain` to explain issues, `mix credo --help` for options).
```

Given these differences, I'm suspecting a bug somewhere in the `StrictModuleLayout` code and/or the flow for enabling checks.

**Comment by NickNeck** [comment]
The `StrictModuleLayout` has `base_priority: :low`, so you have to use `mix credo --strict`.

**Comment by florish** [comment]
> The `StrictModuleLayout` has `base_priority: :low`, so you have to use `mix credo --strict`.

Thanks! Where is this documented? I have been looking for this (and also for the meaning of the tag `:controversial`), but wasn't able to find anything on both subjects.

**Comment by NickNeck** [comment]
You can find documentation with `mix credo suggest --help` and [here](https://hexdocs.pm/credo/suggest_command.html).

**Comment by florish** [comment]
@NickNeck Thanks again! I guess I missed that running `mix credo suggest` is the same as `mix credo`.

As for this issue: obviously, there is no bug then 😄

What might be worth changing, is the following:

I think the default config file hint "just replace `false` with `[]`" here got me confused:

```
        #
        # Controversial and experimental checks (opt-in, just replace `false` with `[]`)
        #
```

This led me to believe that all thecks in this list should automatically work after I replace `false` with `[]`.

As the `:priority` (or `:base_priority`) values are not visible in the `.credo.exs` file, it was not clear to me that I need to be aware of this setting, too.

This is just my feedback. I'm leaving it up to the maintainers to decide whether this needs improvement or not, by means of either fixing or closing this issue.

To be sure: I'd love to help out by improving code and/or documentation, I'm just not sure what's needed in this case!

**Comment by rrrene** [comment]
You are right. The documentation is not comprehensive on this. Thx for bringing this up :+1:

**Comment by rrrene** [comment]
This is part of v1.6.1 💚
