### ISSUE TITLE
Disabled check for a file in `credo.exs` is ignored when running credo for that file

### ISSUE THREAD

**Issue by nickgnd** [rrrene/credo#873]
Hey 👋 
first of all, thanks for all the great work and effort you put in this project. It is part of my daily tools belt and I really enjoy it.

### Precheck

* For bugs, please do a quick search and make sure the bug has not yet been reported here

I searched in the documentation, in the issues and PRs, I couldn't find anything strictly related to my issue.

### Environment

* Credo version (`mix credo -v`): 1.5.5-ref.main.c2c7479+uncommittedchanges
* Erlang/Elixir version (`elixir -v`): 1.11.4 / OTP 24.0.1
* Operating system: macOS Big SUR 11.4

### What were you trying to do?

Running credo for a single file like `mix credo path/to/file.exs` while having a check disabled for that specific file in the `.credo.exs`.

Steps:

- I disabled the `Credo.Check.Readability.Specs` check for a specific file in the `credo.exs`

```elixir
{Credo.Check.Readability.Specs, files: %{excluded: ["lib/example_app.ex"]}},
```

### Expected outcome

Since the check is disabled for that file (`lib/example_app.ex`), I expect to see no `Credo.Check.Readability.Specs` issues when running `mix credo lib/example_app.ex`

### Actual outcome

When I run `mix credo lib/example_app.ex` there is a `Credo.Check.Readability.Specs` issue  ❌

```
❯ mix credo lib/example_app.ex
Checking 1 source file ...

  Code Readability
┃
┃ [R] → Functions should have a @spec type specification.
┃       lib/example_app.ex:15:7 #(ExampleApp.hello)

2 mods/funs, found 1 code readability issue.
```

---

Note, if I run `mix credo` the check configuration is respected.

```
❯ mix credo
Checking 4 source files ...

5 mods/funs, found no issues.
```

Here a repo that can be used to reproduce the error https://github.com/nickgnd/example_app

**Comment by rrrene** [comment]
This is a bug :+1: Thx for reporting it!

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by nickgnd** [comment]
I can confirm, it works greatly! Thanks again for the stunning work 🙇
