### ISSUE TITLE
Spelling Mistake: `supress_output`

### ISSUE THREAD

**Issue by andyl** [rrrene/credo#879]
Buried deep-down in the guts of `Elixir.Credo.CLI.Output.Shell` there is some logic that allows the developer to disable writes to `:stdio`.

The correct spelling for the relevant variable `supress_output` would be `suppress_output`.

I could submit a PR with a fix.  Let me know if you would like me to do that.

**Comment by rrrene** [comment]
> I could submit a PR with a fix. Let me know if you would like me to do that.

Absolutely :+1:
