### ISSUE TITLE
Error on SpandexEcto.TelemetryAdapter

### ISSUE THREAD

**Issue by skas9999** [rrrene/credo#882]
Credo version (mix credo -v): 1.5.4-ref.DVPS-725.3604d036
Erlang/Elixir version (elixir -v): Elixir 1.12.2 (compiled with Erlang/OTP 24)
Operating system: MacOS

### What were you trying to do?
Add Datadog APM code to application so I can monitor performance of app in Datadog

### Expected outcome
Log APM will show in Datadog

### Actual outcome
I got this error when ran mix codebase. 
┃ [R] ↘ The alias `SpandexEcto.TelemetryAdapter` is not alphabetically ordered 
┃       among its group.

**Comment by rrrene** [comment]
Hi, I am not sure what you are asking: You tried to integrate Datadog into your setup and think that Credo is responsible for it not to work?
