### ISSUE TITLE
Confused about hexdocs

### ISSUE THREAD

**Issue by maxdevjs** [rrrene/credo#888]
> Spoiler: completely new to this ecosystem

I am somewhat confused about how `hexdocs` are built.

## First example

`hexdocs v1.5.6` (current version)

[.credo.exs](https://hexdocs.pm/credo/config_file.html) page, [:plugins](https://hexdocs.pm/credo/config_file.html#plugins) section presents a broken [enable and configure plugins](https://hexdocs.pm/credo/plugins.html) link (Page not found).

`repo`

[master](https://github.com/rrrene/credo/tree/master/guides/plugins) has [Creating Plugins](https://github.com/rrrene/credo/blob/master/guides/plugins/creating_plugins.md) and [Using Plugins](https://github.com/rrrene/credo/blob/master/guides/plugins/using_plugins.md) files.

`hexdocs v1.5.6` (current version)

both [Creating Plugins](https://hexdocs.pm/credo/creating_plugins.html) and [Using Plugins](https://hexdocs.pm/credo/using_plugins.html) are available (but not linked), 
but not a working [enable and configure plugins](https://hexdocs.pm/credo/plugins.html) (as [Plugins 101](https://github.com/rrrene/credo/blob/v1.5.6/guides/plugins/plugins.md) is available in `v1.5.6` repo tag).

`hexdocs v1.5.5` (previous version) has a working [Plugins 101](https://hexdocs.pm/credo/1.5.5/plugins.html) (that I'd expect to find for `hexdocs v1.5.6` (current version) instead).

Is it just that the link has not been updated in [v1.5.6 repo tag](https://github.com/rrrene/credo/blob/v1.5.6/guides/configuration/config_file.md)?

## Second example

`hexdocs v1.5.6` (current version): [Basic Usage](https://hexdocs.pm/credo/basic_usage.html) looks the same as `v1.5.6` repo tag 
[Basic Usage](https://github.com/rrrene/credo/blob/v1.5.6/guides/introduction/basic_usage.md) but not as `master` [Basic Usage](https://github.com/rrrene/credo/blob/master/guides/introduction/basic_usage.md).

Am I getting it wrong, or are these `hexdocs` pages somehow mixed?

**Comment by rrrene** [comment]
I re-published the docs for `v1.5.6` and the issues should now be resolved (be sure to shift-reload, as some browsers cache this content quite heavily).

I have to admit that I am not sure how this got mixed up (pun intended) :+1:

**Comment by maxdevjs** [comment]
Thank you.

I see that `master` is currently version `1.6.0-dev`, but not sure which branch is based on...

**Comment by rrrene** [comment]
Not sure what you are asking ... `master` is the branch, `1.6.0-dev` means that this code will become `1.6.0` in the future.

Does that answer the question?

**Comment by maxdevjs** [comment]
I meant if current development is done in another branch.

**Comment by rrrene** [comment]
I'm sorry. English is not my first language, so maybe we are misunderstanding each other:

`master` is the branch where current development is done. That is why the version on `master` is `1.6.0-dev`, because current development is for version `1.6.0`. The `-dev` basically means "in development" 👍

**Comment by maxdevjs** [comment]
> maybe we are misunderstanding each other

Very likely, English is barely my third language :D 

I am completely new to Elixir and I started looking for learning resources.

`credo` is an amazing tool, thanks for creating it.

Back to my previous question, I wanted to understand how development is done in this repo.

I thought that development could happen not in `master` but in a different branch that would be then merged into `master`.

**Comment by rrrene** [comment]
> I thought that development could happen not in `master` but in a different branch that would be then merged into `master` (the "in development" thing is clear).

Contributors make their changes in their forks and open pull requests to get their contributions merged (this works like in most other projects).

I myself sometimes make branches to develop bigger features, but smaller things like bugfixes are committed directly on master, so people can test them directly by setting their dep to `{:credo, github: "rrrene/credo"}`.

> Edit: is [Credo's Elixir Style Guide](https://github.com/rrrene/elixir-style-guide) the general standard used in the Elixir' community?

No, there are other styleguides as well:

* https://github.com/lexmag/elixir-style-guide
* https://github.com/christopheradams/elixir_style_guide

**Comment by maxdevjs** [comment]
Thank you for the explanation.
