### ISSUE TITLE
Credo.Check.Refactor.Apply shouldn't apply if the function name is sourced from a variable

### ISSUE THREAD

**Issue by michaelst** [rrrene/credo#892]
Our function name is sourced from a variable like this
```
apply(stub_module, function, [channel, request])
```
Which means we can't call `stub_module.function(channel, request)` 

Maybe there is a way but I can't seem to find a way. If there is we should add it to the docs. Or if it isn't possible we should have this check ignore this scenario.

**Comment by rrrene** [comment]
Ouch. Thx for the heads up!

It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by michaelst** [comment]
yes it looks like that is fixed now

**Comment by noozo** [comment]
Having this issue in my code while using master. Here's the "offending" code:

```
apply(Outgoing.Subscriptions, String.to_existing_atom("send_#{type}"), [
        subscription
      ])
```
