### ISSUE TITLE
Pipe Chain error on ranges with steps

### ISSUE THREAD

**Issue by sheharyarn** [rrrene/credo#898]
### Environment

* Credo version: 1.5.6
* Erlang version: 23.3
* Elixir version: 1.12.3
* Operating system: macOS Big Sur 11.4

### What were you trying to do?

I have a pipe chain that starts with a range with step. Credo gives the "Pipe Chain must start with raw value" error. Here's the code block.

```elixir
1..limit//1
|> Enum.map(&convert_cell(cells, &1))
|> join_cells()
```

I'm explicitly passing 1 as a step because `limit` can be negative, and we want to ignore those cases.

### Expected outcome

Code passes credo checks without issues.

### Actual outcome

```
 ▲ code/my_app/ mix credo --all
Checking 637 source files (this might take a while) ...

  Refactoring opportunities
┃
┃ [F] → Pipe chain should start with a raw value.
┃       lib/my_app/test_code.ex:114 #(MyApp.TestCode.run)
```

Note that removing the step from the range above causes credo to pass the checks here.

**Comment by rrrene** [comment]
Thx for reporting! :+1:

**Comment by rrrene** [comment]
This is part of `v1.6.4`. Thx for reporting!
