### ISSUE TITLE
Variable `sigil_r` has same name as the `Kernel.sigil_r` macro.

### ISSUE THREAD

**Issue by smeevil** [rrrene/credo#9]
using a case with regex matching results in a warning.

Example : 
case email do
  ~r/@/ -> something       
  _ -> other
end

results in : 
Variable `sigil_r` has same name as the `Kernel.sigil_r` macro.

**Comment by rrrene** [comment]
Ha! That's definitely a bug. Thx for the heads up, will be fixed in next release :+1:

**Comment by smeevil** [comment]
Anytime, awesome tool !

**Comment by rrrene** [comment]
`v0.1.7` contains the fix! :shipit:
