### ISSUE TITLE
How to turn off error so it is not required to write @moduledoc false into hundred of module files

### ISSUE THREAD

**Issue by margusp2heathmont** [rrrene/credo#908]
Is there a setting, so we should not write "@moduledoc false" into hundreds of modules?

**Comment by NickNeck** [comment]
You can disable checks in `.credo.exs`. If you don't have this file then you can create it with `mix credo.gen.config`. You can also ignore checks with `mix credo -i Credo.Check.Readability.ModuleDoc`.

**Comment by rrrene** [comment]
@margusp2heathmont  You can read about the config options in the documentation:

https://hexdocs.pm/credo/config_file.html#content

Configuring checks in general is explained here:

https://hexdocs.pm/credo/check_params.html#content

The check you are refering to is explained here:

https://hexdocs.pm/credo/Credo.Check.Readability.ModuleDoc.html#content
