### ISSUE TITLE
Max line length should ignore regex sigil

### ISSUE THREAD

**Issue by datafoo** [rrrene/credo#912]
### Environment

* Credo version (`mix credo -v`): 1.6.0
* Erlang/Elixir version (`elixir -v`): 1.12.3
* Operating system: [NixOS](https://nixos.org/)

### What were you trying to do?

Add a test with a long regex sigil:

    test "config file with invalid config data" do
      opts =
        TOMLConfigProvider.init(
          "test/support/mysupercharts/fixture/config/#{platform()}/invalid_config.toml"
        )

      assert_raise ArgumentError,
                   ~r<^Invalid configuration file "test/support/mysupercharts/fixture/config/(unix|win32)/invalid_config\.toml": %\{"locations" =\> \[%\{db: %\{hostname: \["can't be blank"\]\}\}, %\{\}\]\}$>,
                   fn -> TOMLConfigProvider.load(@config, opts) end
    end

### Expected outcome

No error since `mix format` was run successfully beforehand.

### Actual outcome

Error: Line is too long.

**Comment by rrrene** [comment]
So we should not only ignore strings, but also sigils by default. Good catch! :+1:

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by datafoo** [comment]
It solves the problem. Thank you!

**Comment by rrrene** [comment]
This is part of `v1.6.4`. Thx for reporting!
