### ISSUE TITLE
What makes this function have such a high ABC?

### ISSUE THREAD

**Issue by bmfay** [rrrene/credo#930]
### Environment

* Credo version (`mix credo -v`): 1.6.1-ref.bf/credo-update.7ca054cf
* Erlang/Elixir version (`elixir -v`): Elixir 1.11.2
* Operating system: Mac OS Catalina

### What were you trying to do?

mix credo some_file

### Expected outcome

Expected it to pass

### Actual outcome

Function is too complex (ABC size is 63, max is 50)

Trying to understand why this function would be considered so complex.  The default max_size is 30, so at 63 this is considered twice as complex as the max.

```
  def build_ship_param_item_data(invoice) do
    ShippingParameterItem
    |> distinct(true)
    |> join(:inner, [spi], assoc(spi, :shipping_parameter))
    |> join(:inner, [spi, sp], assoc(sp, :packing_slips))
    |> join(:inner, [spi, sp, ps], assoc(ps, :packing_slip_items))
    |> join(:inner, [spi, sp, ps, psi], assoc(psi, :item))
    |> join(:inner, [spi, sp, ps, psi, i], assoc(i, :invoice_items))
    |> where([spi, sp, ps, psi, i, ii], ii.invoice_id == ^invoice.id and ii.item_id == spi.item_id)
    |> group_by([spi], spi.id)
    |> select([spi, sp, ps, psi, i, ii], %{
      id: spi.id,
      amount: sum(ii.total_price * (spi.qty_assigned / ii.qty)) / 100,
      quantity: spi.qty_assigned
    })
    |> Repo.all()
  end
```

In the world of ecto and querying, I'd consider this pretty average complexity, but ABC check disagrees.  Not clear from the documentation what goes into it.  https://hexdocs.pm/credo/Credo.Check.Refactor.ABCSize.html#content

I think breaking this out into multiple functions would make it less readable.  Just wondering if anyone has thoughts.  I'd like to use ABC check as it is more often useful than not but I'm finding the number of places I need to add 

```# credo:disable-for-next-line Credo.Check.Refactor.ABCSize```

to be very high.

**Comment by rrrene** [comment]
Hi, sorry for the late reply. 

The check should not count Ecto functions in cases where `Ecto.Query` is imported, so this might a bug.

That said, the check is marked as controversial, since it is unclear whether or not this metric is useful in functional programming at all.
