### ISSUE TITLE
Unused variables should be named consistently, but `__aliases__` does not follow  that convention.

### ISSUE THREAD

**Issue by thomas9911** [rrrene/credo#931]
### Precheck

* For bugs, please do a quick search and make sure the bug has not yet been reported here :heavy_check_mark: 

### Environment

* Credo version (`mix credo -v`):
1.6.1
* Erlang/Elixir version (`elixir -v`):
Elixir 1.13.1 (compiled with Erlang/OTP 22)
* Operating system:
ubunty 18.04

### What were you trying to do?

I have a function that matches on a Module and returns a string:

```elixir
  defp module_to_string(Action), do: "action"
  defp module_to_string(Model), do: "model"
```

edit: maybe for more insights/info these modules are aliased at the top of the file:

```elixir
  alias MyApp.Actions.Action
  alias MyApp.Models.Model
```

### Expected outcome

no report

### Actual outcome

```
Unused variables should be named consistently. It seems your strategy is to name them anonymously (ie. `_`) but `__aliases__` does not follow  that convention.
```

**Comment by rrrene** [comment]
I can't seem to reproduce this. Could you try to come up with a single file that produces this consistency error?

**Comment by thomas9911** [comment]
found the way to reproduce it:

```elixir
defmodule CredoCheck do
  @moduledoc """
  Documentation for `CredoCheck`.
  """

  def module_to_binary(Enum), do: "enum"

  def testing(_), do: :ok
end
```

Run credo with:

```sh
mix credo --enable-disabled-checks Credo.Check.Consistency.UnusedVariableNames
```

**Comment by thomas9911** [comment]
I was looking at the code a bit, maybe a solution could be to add and extra check here: lib/credo/check/consistency/unused_variable_names/collector.ex#L51

```elixir 
  defp unused_variable_name?({name, _, _}) when is_atom(name),
    do: String.starts_with?(Atom.to_string(name), "_")
```

to 

```elixir 
  defp unused_variable_name?({name, _, _}) when is_atom(name) do
    String.starts_with?(Atom.to_string(name), "_") and not String.starts_with?(Atom.to_string(name), "__")
  end
```

ps: untested

**Comment by quatauta** [comment]
After updating Credo version 1.6.1 to 1.6.2, I get a similar message for `__MODULE__`.

```elixir
defmodule Credo931 do
  def open_bank do
    {:ok, account} = GenServer.start_link(__MODULE__, {:open, 0})
    account
  end
end
```

```console
$ mix credo
[...]
  Consistency
┃
┃ [C] ↗ Unused variables should be named consistently. It seems your strategy is to name them anonymously (ie. `_`) but `__MODULE__` does not follow that convention.
┃       [...]/lib/credo-931.ex:3:43 #(Credo931.open_bank)
```

Running Credo with the [change suggested](https://github.com/rrrene/credo/issues/931#issuecomment-1004041065) by @thomas9911 silences the message for me.

**Comment by quatauta** [comment]
At https://github.com/quatauta/credo-issue-931-minimal-example, you can find a kind-of-minimal example project to reproduce the issue. Any comment -- positive, negative, critical -- is very welcome!

**Comment by rrrene** [comment]
Thanks for reproducing this 😀  It is now fixed on `master`, based on the suggestion by @thomas9911 :+1: 

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by quatauta** [comment]
> Thanks for reproducing this 😀 It is now fixed on `master`, based on the suggestion by @thomas9911 👍
> [...]
> Please report back if your issue is solved! 👍

Credo master with a86d3e1 fixes the issue for me! Thank you @rrrene ! 🚀  😄

**Comment by rrrene** [comment]
Great! I will publish a new version of Credo next week :+1:

**Comment by quatauta** [comment]
> Great! I will publish a new version of Credo next week 👍

Thank you so much for your support 💗 I am looking forward to the new version!

**Comment by rrrene** [comment]
This is now live in `v1.6.3`. Thx again!
