### ISSUE TITLE
"Space missing after comma" and "no whitespace around parentheses/brackets most of the time" for interpolations and commas inside strings

### ISSUE THREAD

**Issue by dgigafox** [rrrene/credo#940]
### Environment

* Credo version (`mix credo -v`):  1.6.2
* Erlang/Elixir version (`elixir -v`): Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Operating system:  macOS Catalina v10.15.7

### What were you trying to do?
Run mix credo --strict in a project with these line of codes:
```elixir
defp something do
  "something[#{:hey}]" #<- 1st warning
  String.split("testing,123", ",") #<- 2nd warning
end
```

### Expected outcome
No warning

### Actual outcome
1st warning
[C] ↗ There is no whitespace around parentheses/brackets most of 
┃       the time, but here there is.

2nd warning
[R] → Space missing after comma

**Comment by noozo** [comment]
+1

**Comment by woylie** [comment]
After upgrading from 1.6.1 to 1.6.2, any string with spaces around parentheses like this:

```elixir
" (#{rounds})"
```

Will trigger: `There is no whitespace around parentheses/brackets most of the time, but here there is.`

**Comment by rrrene** [comment]
I've been trying to get tot the bottom of this, but am getting nowhere. Can anyone point to an Open Source repo where this happens?

**Comment by harmon25** [comment]
Don't have a public repo, but here is some code in a private project triggering these.

here is a function that triggers `Space missing after comma`, cause of this `","`
```elixir
def decode_and_clean_list(encoded_list) do
  # "a,b,c"
  encoded_list
  |> String.split(",", trim: true)
  |> Enum.uniq()
end
```

This code triggers `There is no whitespace around parentheses/brackets most of the time, but here there is` from this `"%{#{:test}}"`
```elixir
String.replace("%{test}", "%{#{:test}}", "someval")
```

**Comment by rrrene** [comment]
@dgigafox  @woylie  @noozo @harmon25 I merged the proposed fix by @rubysolo (thx!) ... would you mind running this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

and report back if your issue is solved?

**Comment by woylie** [comment]
@rrrene That fixed it for me, thanks.

**Comment by rrrene** [comment]
Great! I will publish a new version of Credo next week :+1:

**Comment by rrrene** [comment]
This is now live in `v1.6.3`. Thx again!
