### ISSUE TITLE
Ensure correct indentation for content of heredoc

### ISSUE THREAD

**Issue by cubytz** [rrrene/credo#963]
### Precheck

* Proposals for new features should be submitted via: https://github.com/rrrene/credo-proposals
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 1.6.4
* Erlang/Elixir version (`elixir -v`): 1.13.1
* Operating system: MacOS Monterey

### What were you trying to do?

Thank you for the great library! I am trying to keep some harmony in our codebase and was wondering if it is possible to check if the indentation within a comment block is respected. For example, here is the documentation on top of my `Greeter.hello/1` function:

``` elixir
@doc """
  Prints a hello message.

  ## Parameters

    - name: String that represents the name of the person.

  ## Examples

      iex> Greeter.hello("Sean")
      "Hello, Sean"

      iex> Greeter.hello("pete")
      "Hello, pete"

  """
```

I am wondering if it is possible to ensure that this line `  Prints a hello message` returns an error because it is indented and not on the same level as `@doc """`.

### Expected outcome

The contents inside the heredoc should be indented at the same level as the opening and closing """

### Actual outcome

No warning

**Comment by rrrene** [comment]
> I am wondering if it is possible to ensure that this line ` Prints a hello message` returns an error because it is indented and not on the same level as `@doc """`.

This could certainly be done, but I would be hesitant to introduce this as a standard check. I never align my heredocs in the way you describe, since the resulting binary is not affected by it.

But you can create a custom check for Credo to check this, for sure :+1:
