### ISSUE TITLE
can't see the problem with alias list order

### ISSUE THREAD

**Issue by leandroruel** [rrrene/credo#976]
### Precheck

* Proposals for new features should be submitted via: https://github.com/rrrene/credo-proposals
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 1.5.6-ref.develop.73be80a+uncommittedchanges
* Erlang/Elixir version (`elixir -v`): Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Operating system:
Linux Mint
### What were you trying to do?

credo says that this list is in wrong order alphabetically, tried everything and still insists is wrong, what is happening!?

![image](https://user-images.githubusercontent.com/2836002/171745743-ed263369-1d63-415b-823d-689a083a0484.png)

```
alias DataLayer.{
    Accounts,
    AdminFilterGroups,
    Campaigns,
    Categories,
    Deliveries,
    Gateways,
    Groups,
    Invoices,
    Manufacturers,
    Orders,
    Orders.Payment,
    OrderPayments,
    PaymentMethods,
    Products,
    Sellers,
    SettledTransactions,
    SiteCategoryBanners,
    SiteFeaturedCategories,
    SiteFeaturedLinks,
    SiteFeaturedManufacturers,
    SiteHomeBanners,
    SiteShowcases,
    Skus,
    Tenants
  }
```

### Expected outcome

none error

### Actual outcome

R] ↘ The alias `DataLayer` is not alphabetically ordered among its group.
┃       lib/data_layer_web/schema.ex:13:9 (DataLayerWeb.Schema)
┃
┃       alias DataLayer.{
┃             ^^^^^^^^^

**Comment by rrrene** [comment]
Seems to me `Orders` and `Orders.Payment` should go after `OrderPayments`, since `s` comes after `p`.

Please re-open this issue if you have a different opinion 👍
