### ISSUE TITLE
Misinterpreting __MODULE__ in Logger.metadata/1

### ISSUE THREAD

**Issue by kanes115** [rrrene/credo#977]
### Environment

* Credo version (`mix credo -v`): `1.6.1-ref`
* Erlang/Elixir version (`elixir -v`): `Erlang/OTP 24/Elixir 1.13.3`
* Operating system: MacOs Monterey v12.1

### What were you trying to do?
I try to reference current module (the one calling `quote`) inside the quoted block inside Logger.metadata call.
```
    quote do
      with_span unquote(span_name) do
        Logger.metadata(
          trace_id: unquote(__MODULE__).trace_id(),
          span_id: unquote(__MODULE__).span_id()
        )

        unquote(body)
      end
    end
```

### Expected outcome
This should be allowed.

### Actual outcome
```
  Code Readability
┃
┃ [R] → __MODULE__ macro in log message
┃       file_example.ex:35:28 #(Example.example)
┃ [R] → __MODULE__ macro in log message
┃       file_example.exs:34:29 #(Example.example)
```
It seems to be wrong as __MODULE__ is not actually put in a log message.

**Comment by rrrene** [comment]
Could you run `mix credo --verbose` to display the check's name?

**Comment by rrrene** [comment]
Hi, I'm closing this since it does not seem to be an issue with Credo (we don't have issues that produce "macro in log message").

Please feel free to re-open this anytime there is new information! :v:
