### ISSUE TITLE
Credo.Code.Scope.mod_name/1 only works with lower case definition names

### ISSUE THREAD

**Issue by hochata** [rrrene/credo#981]
### Environment

* Credo version (`mix credo -v`): 1.6.4
* Erlang/Elixir version (`elixir -v`): OTP 21, Elixir 1.10.0
* Operating system: Linux

### What were you trying to do?

I tried to the get the module name of some scopes with where the final section of the name start with underscores, like`Module.__after__compile__` and `Module.__using__` but they returned the whole input string.

It seems the current implementation only checks that the last part of a scope starts with a lowercase letter.

What function/macro names are even allowed in Elixir? Would checking if the first letter is an upper case instead would be more robust?

### Expected outcome

```elixir
iex> Credo.Code.Scope.mod_name("Credo.Code.__after_compile__")
"Credo.Code"
```

### Actual outcome

```elixir
iex> Credo.Code.Scope.mod_name("Credo.Code.__after_compile__")
"Credo.Code.__after_compile__"
```

**Comment by rrrene** [comment]
Thy for reporting this! 👍

hochata ***@***.***> schrieb am Fr. 24. Juni 2022 um 21:30:

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by rrrene** [comment]
Thx for reporting this! :+1: It should be be fixed in the latest version of Credo.

If it is not, please feel free to re-open this issue!
