### ISSUE TITLE
Consistency warning "There are no spaces around operators most of the time..." - unary "-" before a float 

### ISSUE THREAD

**Issue by darrenklein** [rrrene/credo#983]
Thank you very much for all of your hard work on this project! I hope that I'm not being redundant - I did look through some back issues, and I found that this seems to have been brought up (and resolved) in https://github.com/rrrene/credo/issues/797, but perhaps I've uncovered an edge case?

### Environment

* Credo version (`mix credo -v`): 1.6.4-ref.main.0de74f77
* Erlang/Elixir version (`elixir -v`): Elixir 1.13.2 (compiled with Erlang/OTP 24)
* Operating system: macOS Monterey v12.4

### What were you trying to do?

I recently made some changes in the file `app/seed.ex`. When running `mix credo app/seed.ex`, I am getting the consistency warning "There are no spaces around operators most of the time, but here there are." pointing to a few uses of `=` and `->`. I realized that these are occurring because the changes that I made include a number of negative float values like so:

```
%{
    loc_1: %{
      id: 2002,
      street: "123 Main Street",
      city: "Town",
      state: "ME",
      postal_code: "00000",
      geom: %Geo.Point{coordinates: {-74.30323, 47.619055}}
    }
}
```

where the `geom` attribute may include a leading unary `-` on one or both of its coordinates. I added about 20 instances or so of this, so it's making credo think that this is how I want my operators to be spaced.

### Expected outcome

No credo warnings (or at least not these!).

### Actual outcome

```
┃ [C] ↗ There are no spaces around operators most of the time, but here there are.
┃       app/seed.ex:3416:36 #(Seed.with_timestamps)
┃ [C] ↗ There are no spaces around operators most of the time, but here there are.
┃       app/seed.ex:3409:16 #(Seed.seed_collection)
┃ [C] ↗ There are no spaces around operators most of the time, but here there are.
┃       app/seed.ex:3404:16 #(Seed.seed_collection)
┃ [C] ↗ There are no spaces around operators most of the time, but here there are.
┃       app/seed.ex:3404:57 #(Seed.seed_collection)
┃ [C] ↗ There are no spaces around operators most of the time, but here there are.
┃       app/seed.ex:3365:53 #(Seed)
┃ [C] ↗ There are no spaces around operators most of the time, but here there are.
┃       app/seed.ex:3354:47 #(Seed)
```

Here's one example of the code in question:

```
# app/seed.ex:3404:16 and app/seed.ex:3404:57
3403  def seed_collection(entity, collection, opts) when is_map(collection) do
3404    collection = Enum.map(collection, fn {_key, entity} -> entity end)
3405    seed_collection(entity, collection, opts)
3406  end
```

The warning will be resolved if I change line 3404 to

```
 collection=Enum.map(collection, fn {_key, entity}->entity end)
```

or if I set my credo config like

```
{Credo.Check.Consistency.SpaceAroundOperators, ignore: [:=, :->]}
```

but neither of those are favorable.

**Comment by rrrene** [comment]
Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by darrenklein** [comment]
@rrrene thank you, this solves the problem! I really appreciate your quick action on this issue and all of your hard work on this project over the years, it's one of my favorite dev tools!

**Comment by rrrene** [comment]
Thx for reporting this! :+1: It should be be fixed in the latest version of Credo.

If it is not, please feel free to re-open this issue!

**Comment by darrenklein** [comment]
Yep, I updated the Hex package to 1.6.6, it's fixed, thank you!
